export const dummyWorkflowJson = {
  blocks: [
    {
      color: '#2BCCBA',
      height: 90,
      icon: 'mdi-flag',
      id: 'G59WQkftZGs7D9JAsua_5',
      left: 54,
      top: 54,
      type: 'START',
      width: 175,
      settings: {
        aiPrediction: {},
        conditions: {
          condition: [],
          groupLogic: 'ALL',
        },
        documentRequired: false,
        dynamicUser: [],
        externalUser: [],
        externalUserMail: [],
        fileSettings: {
          fileCheckList: [],
          partial: false,
        },
        formEditAccess: 'FULL',
        formEditControls: [],
        formSecureControls: [],
        formVisibilityAccess: true,
        forwardedUserAction: 'DEFAULT',
        forwardLabel: '',
        fullApprovalAction: '',
        generateCSV: false,
        generateCSVFields: [],
        generateDocument: {
          allowSubmission: false,
          documentList: [],
        },
        generatePDFFields: [],
        groups: [],
        hasMasterEntriesAction: false,
        initiateBy: ['EMAIL'],
        initiateMode: 'AUTOMATIC',
        isQuickAction: true,
        label: 'Initiator',
        mailInitiate: {
          conditions: {
            attachment: {
              filename: [],
              fileType: [],
              hasFileFormat: 'ANY',
              hasFileName: 'ANY',
              hasOcrData: 'ANY',
              ocrData: [],
              request: 'SINGLE',
            },
            fromAddress: [],
            fromDomain: [],
            hasAttachment: false,
            mailContent: [],
            mailSubject: [],
          },
          connectorId: 10,
          connectorType: 'gmail',
          mailSettingsId: 0,
        },
        mappingFieldsToForm: {
          completedAt: '',
          status: '',
        },
        masterConditions: {
          condition: [],
          masterFormId: 0,
        },
        masterFormEntries: [],
        mlCompareFields: [],
        mlCompareMaster: false,
        mlMasterFormId: 0,
        mlPredictionField: '',
        mlStatusField: '',
        notifications: {
          acknowledgement: {
            attachment: false,
            body: '',
            bodyContent: '',
            emailAttachment: false,
            emailNotify: false,
            notify: false,
            slackAttachment: false,
            slackConnectorId: 0,
            slackContent: '',
            slackContentCopy: '',
            slackHubId: 0,
            slackNotify: false,
            smsContent: '',
            smsNotify: false,
            subject: '',
            subjectContent: '',
            teamsAttachment: false,
            teamsConnectorId: 0,
            teamsContent: '',
            teamsContentCopy: '',
            teamsHubId: 0,
            teamsNotify: false,
            whatsappAttachment: false,
            whatsappConnectorId: 0,
            whatsappContent: '',
            whatsappContentCopy: '',
            whatsappNotify: false,
          },
          inboxNotification: {
            actionButtons: false,
            attachment: false,
            body: '',
            bodyContent: '',
            emailAttachment: false,
            emailNotify: false,
            notify: false,
            slackAttachment: false,
            slackConnectorId: 0,
            slackContent: '',
            slackContentCopy: '',
            slackHubId: 0,
            slackNotify: false,
            smsContent: '',
            smsNotify: false,
            subject: '',
            subjectContent: '',
            teamsAttachment: false,
            teamsConnectorId: 0,
            teamsContent: '',
            teamsContentCopy: '',
            teamsHubId: 0,
            teamsNotify: false,
            whatsappAttachment: false,
            whatsappConnectorId: 0,
            whatsappContent: '',
            whatsappContentCopy: '',
            whatsappNotify: false,
          },
          markCCField: {
            attachment: false,
            body: '',
            bodyContent: '',
            fields: [],
            notify: false,
            subject: '',
            subjectContent: '',
          },
          processStage: {
            alertProcessStage: [],
            attachment: false,
            body: '',
            bodyContent: '',
            notify: false,
            subject: '',
            subjectContent: '',
          },
          userGroup: {
            alertGroup: [],
            alertUser: [],
            attachment: false,
            body: '',
            bodyContent: '',
            notify: false,
            subject: '',
            subjectContent: '',
          },
        },
        partialApprove: true,
        reopen: false,
        reopenBlockId: '',
        slaRules: [],
        slaSettings: {
          emailNotify: true,
          slaMasterFormId: 0,
          slaType: 'STANDARD',
          smsNotify: false,
          workflowFormSLAFieldId: '',
        },
        subWorkflowId: 0,
        toInitiator: false,
        userDomains: [],
        userReply: false,
        users: [],
      },
    },
    {
      color: '#FC5C65',
      height: 90,
      icon: 'mdi-flag',
      id: 'gRBdu25IaIgwy2LCK5yS0',
      left: 1409.000813058978,
      top: 340.50077760733865,
      type: 'END',
      width: 175,
      settings: {
        aiPrediction: {},
        conditions: {
          condition: [],
          groupLogic: 'ALL',
        },
        documentRequired: false,
        dynamicUser: [],
        externalUser: [],
        externalUserMail: [],
        fileSettings: {
          fileCheckList: [],
          partial: false,
        },
        footerText: '',
        formEditAccess: 'FULL',
        formEditControls: [],
        formSecureControls: [],
        formVisibilityAccess: true,
        forwardedUserAction: 'DEFAULT',
        forwardLabel: '',
        fullApprovalAction: '',
        generateCSV: false,
        generateCSVFields: [],
        generateDocument: {
          allowSubmission: false,
          documentList: [],
        },
        generatePDFFields: [],
        groups: [],
        hasFooter: false,
        hasMasterEntriesAction: false,
        initiateBy: ['USER'],
        initiateMode: 'MANUAL',
        isQuickAction: true,
        label: 'Completed',
        mappingFieldsToForm: {
          completedAt: '',
          status: '',
        },
        masterConditions: {
          condition: [],
          masterFormId: 0,
        },
        masterFormEntries: [],
        mlCompareFields: [],
        mlCompareMaster: false,
        mlMasterFormId: 0,
        mlPredictionField: '',
        mlStatusField: '',
        notifications: {
          acknowledgement: {
            attachment: false,
            body: '',
            bodyContent: '',
            emailAttachment: false,
            emailNotify: false,
            notify: false,
            slackAttachment: false,
            slackConnectorId: 0,
            slackContent: '',
            slackContentCopy: '',
            slackHubId: 0,
            slackNotify: false,
            smsContent: '',
            smsNotify: false,
            subject: '',
            subjectContent: '',
            teamsAttachment: false,
            teamsConnectorId: 0,
            teamsContent: '',
            teamsContentCopy: '',
            teamsHubId: 0,
            teamsNotify: false,
            whatsappAttachment: false,
            whatsappConnectorId: 0,
            whatsappContent: '',
            whatsappContentCopy: '',
            whatsappNotify: false,
          },
          inboxNotification: {
            actionButtons: false,
            attachment: false,
            body: '',
            bodyContent: '',
            emailAttachment: false,
            emailNotify: false,
            notify: false,
            slackAttachment: false,
            slackConnectorId: 0,
            slackContent: '',
            slackContentCopy: '',
            slackHubId: 0,
            slackNotify: false,
            smsContent: '',
            smsNotify: false,
            subject: '',
            subjectContent: '',
            teamsAttachment: false,
            teamsConnectorId: 0,
            teamsContent: '',
            teamsContentCopy: '',
            teamsHubId: 0,
            teamsNotify: false,
            whatsappAttachment: false,
            whatsappConnectorId: 0,
            whatsappContent: '',
            whatsappContentCopy: '',
            whatsappNotify: false,
          },
          markCCField: {
            attachment: false,
            body: '',
            bodyContent: '',
            fields: [],
            notify: false,
            subject: '',
            subjectContent: '',
          },
          processStage: {
            alertProcessStage: [],
            attachment: false,
            body: '',
            bodyContent: '',
            notify: false,
            subject: '',
            subjectContent: '',
          },
          userGroup: {
            alertGroup: [],
            alertUser: [],
            attachment: false,
            body: '',
            bodyContent: '',
            notify: false,
            subject: '',
            subjectContent: '',
          },
        },
        partialApprove: true,
        reopen: false,
        reopenBlockId: '',
        slaRules: [],
        slaSettings: {
          emailNotify: true,
          slaMasterFormId: 0,
          slaType: 'STANDARD',
          smsNotify: false,
          workflowFormSLAFieldId: '',
        },
        subWorkflowId: 0,
        toInitiator: false,
        userDomains: [],
        userReply: false,
        users: [],
      },
    },
    {
      color: '#eea557',
      height: 90,
      icon: 'mdi-file-find',
      id: 'AN_VThGrTcn0tDQOUmZ0F',
      left: 54,
      top: 206.0003402032106,
      type: 'OCR',
      width: 175,
      settings: {
        addConditionRule: false,
        aiPrediction: {},
        conditions: {
          condition: [],
          groupLogic: 'ALL',
        },
        documentRequired: false,
        dynamicUser: [],
        externalUser: [],
        externalUserMail: [],
        fileSettings: {
          fileCheckList: [],
          partial: false,
        },
        footerText: '',
        formEditAccess: 'FULL',
        formEditControls: [],
        formSecureControls: [],
        formVisibilityAccess: true,
        forwardedUserAction: 'DEFAULT',
        forwardLabel: '',
        fullApprovalAction: '',
        generateCSV: false,
        generateCSVFields: [],
        generateDocument: {
          allowSubmission: false,
          documentList: [],
        },
        generatePDFFields: [],
        groups: [],
        hasFooter: false,
        hasMasterEntriesAction: false,
        initiateBy: ['USER'],
        initiateMode: 'MANUAL',
        isQuickAction: true,
        label: 'AI OCR 1',
        mappingFieldsToForm: {
          completedAt: '',
          status: '',
        },
        masterConditions: {
          condition: [],
          masterFormId: 0,
        },
        masterFormEntries: [],
        mlCompareFields: [],
        mlCompareMaster: false,
        mlMasterFormId: 0,
        mlPredictionField: '',
        mlStatusField: '',
        notifications: {
          acknowledgement: {
            attachment: false,
            body: '',
            bodyContent: '',
            emailAttachment: false,
            emailNotify: false,
            notify: false,
            slackAttachment: false,
            slackConnectorId: 0,
            slackContent: '',
            slackContentCopy: '',
            slackHubId: 0,
            slackNotify: false,
            smsContent: '',
            smsNotify: false,
            subject: '',
            subjectContent: '',
            teamsAttachment: false,
            teamsConnectorId: 0,
            teamsContent: '',
            teamsContentCopy: '',
            teamsHubId: 0,
            teamsNotify: false,
            whatsappAttachment: false,
            whatsappConnectorId: 0,
            whatsappContent: '',
            whatsappContentCopy: '',
            whatsappNotify: false,
          },
          inboxNotification: {
            actionButtons: false,
            attachment: false,
            body: '',
            bodyContent: '',
            emailAttachment: false,
            emailNotify: false,
            notify: false,
            slackAttachment: false,
            slackConnectorId: 0,
            slackContent: '',
            slackContentCopy: '',
            slackHubId: 0,
            slackNotify: false,
            smsContent: '',
            smsNotify: false,
            subject: '',
            subjectContent: '',
            teamsAttachment: false,
            teamsConnectorId: 0,
            teamsContent: '',
            teamsContentCopy: '',
            teamsHubId: 0,
            teamsNotify: false,
            whatsappAttachment: false,
            whatsappConnectorId: 0,
            whatsappContent: '',
            whatsappContentCopy: '',
            whatsappNotify: false,
          },
          markCCField: {
            attachment: false,
            body: '',
            bodyContent: '',
            fields: [],
            notify: false,
            subject: '',
            subjectContent: '',
          },
          processStage: {
            alertProcessStage: [],
            attachment: false,
            body: '',
            bodyContent: '',
            notify: false,
            subject: '',
            subjectContent: '',
          },
          userGroup: {
            alertGroup: [],
            alertUser: [],
            attachment: false,
            body: '',
            bodyContent: '',
            notify: false,
            subject: '',
            subjectContent: '',
          },
        },
        ocrAgent: {
          ocrEntryId: 0,
          ocrPrompt:
            'You are an expert invoice parser.  Extract data according to the visible table structure and column headers in the invoice.  For every line item, only extract fields that correspond to the table columns for that row (do not include header/shipment fields in line items).  Merge all multi-line content within a single cell into that field (especially for the "description" and "notes").  Shipment/invoice-level fields such as CAR NUMBER, SHIPPING POINT, SHIPMENT NUMBER, CURRENCY, etc., must go ONLY into the "header", not as line item fields.  Use this schema:  {field_mapping}    If a field is missing for a line item or header, use null.  Do not invent fields. Do not add any header or shipment data to any line item. Return ONLY the JSON object, no explanation.  Invoice Text:  {txt}',
          ocrPromptId: 1,
          ocrSpecificInstruction: '',
          outputSchema: 'ARCHIVE',
          promptSchema:
            '{"header":{"car_number":"string or null","shipment_number":"string or null","shipping_point":"string or null","currency":"string or null","invoice_number":"string or null","invoice_date":"string or null","order_number":"string or null","customer_order_number":"string or null","our_order_number":"string or null","sales_order_number":"string or null","purchase_order_number":"string or null","order_date":"string or null","supplier_name":"string or null","supplier_address":"string or null","supplier_phone":"string or null","supplier_email":"string or null","supplier_tax_id":"string or null","customer_name":"string or null","customer_address":"string or null","customer_phone":"string or null","customer_email":"string or null","customer_tax_id":"string or null","ship_to_name":"string or null","ship_to_address":"string or null","bill_to_name":"string or null","bill_to_address":"string or null","remit_to_name":"string or null","remit_to_address":"string or null","tax_id":"string or null","tax_registration_number":"string or null","vat_number":"string or null","payment_terms":"string or null","payment_method":"string or null","payment_reference":"string or null","bank_account_number":"string or null","iban":"string or null","swift_code":"string or null","total_before_tax":"string or null","tax_amount":"string or null","tax_rate":"string or null","shipping_charges":"string or null","discount":"string or null","total_due":"string or null","amount_paid":"string or null","balance_due":"string or null","due_date":"string or null","invoice_status":"string or null","reference_number":"string or null","project_code":"string or null","department":"string or null","contact_person":"string or null","notes":"string or null","additional_info":"string or null"},"line_items":[{"quantity":"string or null","units":"string or null","description":"string or null","footage":"string or null","price":"string or null","amount":"string or null","notes":"string or null"}]}',
          region: 'US & CANADA',
          selectedOcrPrompt: 1,
        },
        partialApprove: true,
        reopen: false,
        reopenBlockId: '',
        slaRules: [],
        slaSettings: {
          emailNotify: true,
          slaMasterFormId: 0,
          slaType: 'STANDARD',
          smsNotify: false,
          workflowFormSLAFieldId: '',
        },
        subWorkflowId: 0,
        toInitiator: false,
        userDomains: [],
        userReply: false,
        users: [],
        setConditionNotification: false,
      },
    },
    {
      color: '#c37df3ff',
      height: 90,
      icon: 'mdi-creation',
      id: 'NhB-AEDaz0WDuB3zOm1kg',
      left: 304.9996622678091,
      top: 161,
      type: 'AP_AGENT',
      width: 175,
      settings: {
        aiPrediction: {},
        apAgent: {
          connectorId: 0,
          decisionApprove: 90,
          decisionPartial: 60,
          decisionReject: 0,
          features: ['DUPLICATE_DETECT', 'BACKORDER_DETECT'],
          fieldScore: [
            {
              id: 'QFr13_VKqcZeNOpTHlBVj',
              label: 'Supplier Name',
              value: 35,
            },
            {
              id: 'GFzbmdwJjsyK4N3-86uL8',
              label: 'PO Number',
              value: 35,
            },
            {
              id: 'JZRlTZMHzNp7eC14J9dZ6',
              label: 'Currency',
              value: 10,
            },
            {
              id: 'renIraRiO-flNSlQdhrtE',
              label: 'Total Due',
              value: 10,
            },
            {
              id: 'Nv5fQ5VJNNvhOnTJ3lUhx',
              label: 'Line Item',
              value: 10,
            },
          ],
          formId: 14,
          invoiceType: 'PO_INVOICE',
          matchingType: '2_WAY_MATCH',
          resource: 'FORM',
          syncGLAccount: 15,
          syncGLAccountRequired: true,
          syncMatterInfo: 13,
          syncMatterInfoRequired: true,
          vendorMasterId: 11,
          vendorValidationRequired: true,
        },
        conditions: {
          condition: [],
          groupLogic: 'ALL',
        },
        documentRequired: false,
        dynamicUser: [],
        externalUser: [],
        externalUserMail: [],
        fileSettings: {
          fileCheckList: [],
          partial: false,
        },
        footerText: '',
        formEditAccess: 'FULL',
        formEditControls: [],
        formSecureControls: [],
        formVisibilityAccess: true,
        forwardedUserAction: 'DEFAULT',
        forwardLabel: '',
        fullApprovalAction: '',
        generateCSV: false,
        generateCSVFields: [],
        generateDocument: {
          allowSubmission: false,
          documentList: [],
        },
        generatePDFFields: [],
        groups: [],
        hasFooter: false,
        hasMasterEntriesAction: false,
        initiateBy: ['USER'],
        initiateMode: 'MANUAL',
        isQuickAction: true,
        label: 'AP AGENT 1',
        mappingFieldsToForm: {
          completedAt: '',
          status: '',
        },
        masterConditions: {
          condition: [],
          masterFormId: 0,
        },
        masterFormEntries: [],
        mlCompareFields: [],
        mlCompareMaster: false,
        mlMasterFormId: 0,
        mlPredictionField: '',
        mlStatusField: '',
        notifications: {
          acknowledgement: {
            attachment: false,
            body: '',
            bodyContent: '',
            emailAttachment: false,
            emailNotify: false,
            notify: false,
            slackAttachment: false,
            slackConnectorId: 0,
            slackContent: '',
            slackContentCopy: '',
            slackHubId: 0,
            slackNotify: false,
            smsContent: '',
            smsNotify: false,
            subject: '',
            subjectContent: '',
            teamsAttachment: false,
            teamsConnectorId: 0,
            teamsContent: '',
            teamsContentCopy: '',
            teamsHubId: 0,
            teamsNotify: false,
            whatsappAttachment: false,
            whatsappConnectorId: 0,
            whatsappContent: '',
            whatsappContentCopy: '',
            whatsappNotify: false,
          },
          inboxNotification: {
            actionButtons: false,
            attachment: false,
            body: '',
            bodyContent: '',
            emailAttachment: false,
            emailNotify: false,
            notify: false,
            slackAttachment: false,
            slackConnectorId: 0,
            slackContent: '',
            slackContentCopy: '',
            slackHubId: 0,
            slackNotify: false,
            smsContent: '',
            smsNotify: false,
            subject: '',
            subjectContent: '',
            teamsAttachment: false,
            teamsConnectorId: 0,
            teamsContent: '',
            teamsContentCopy: '',
            teamsHubId: 0,
            teamsNotify: false,
            whatsappAttachment: false,
            whatsappConnectorId: 0,
            whatsappContent: '',
            whatsappContentCopy: '',
            whatsappNotify: false,
          },
          markCCField: {
            attachment: false,
            body: '',
            bodyContent: '',
            fields: [],
            notify: false,
            subject: '',
            subjectContent: '',
          },
          processStage: {
            alertProcessStage: [],
            attachment: false,
            body: '',
            bodyContent: '',
            notify: false,
            subject: '',
            subjectContent: '',
          },
          userGroup: {
            alertGroup: [],
            alertUser: [],
            attachment: false,
            body: '',
            bodyContent: '',
            notify: false,
            subject: '',
            subjectContent: '',
          },
        },
        partialApprove: true,
        reopen: false,
        reopenBlockId: '',
        slaRules: [],
        slaSettings: {
          emailNotify: true,
          slaMasterFormId: 0,
          slaType: 'STANDARD',
          smsNotify: false,
          workflowFormSLAFieldId: '',
        },
        subWorkflowId: 0,
        toInitiator: false,
        userDomains: [],
        userReply: false,
        users: [],
      },
    },
    {
      color: '#A65EEA',
      height: 90,
      icon: 'mdi-account-multiple',
      id: 'srf66hYmrFs6F1tStUmul',
      left: 841.0002269417367,
      top: 463.50125753686797,
      type: 'INTERNAL_ACTOR',
      width: 175,
      settings: {
        aiPrediction: {},
        conditions: {
          condition: [],
          groupLogic: 'ALL',
        },
        documentRequired: false,
        dynamicUser: ['N-0GtXrVEiP86zJgIHHtf'],
        externalUser: [],
        externalUserMail: [],
        fileSettings: {
          fileCheckList: [],
          partial: false,
        },
        footerText: '',
        formEditAccess: 'FULL',
        formEditControls: [],
        formSecureControls: [],
        formVisibilityAccess: true,
        forwardedUserAction: 'DEFAULT',
        forwardLabel: '',
        fullApprovalAction: '',
        generateCSV: false,
        generateCSVFields: [],
        generateDocument: {
          allowSubmission: false,
          documentList: [],
        },
        generatePDFFields: [],
        groups: [],
        hasFooter: false,
        hasMasterEntriesAction: false,
        initiateBy: ['USER'],
        initiateMode: 'MANUAL',
        isQuickAction: true,
        label: 'Verifier',
        mappingFieldsToForm: {
          completedAt: '',
          status: '',
        },
        masterConditions: {
          condition: [],
          masterFormId: 0,
        },
        masterFormEntries: [],
        mlCompareFields: [],
        mlCompareMaster: false,
        mlMasterFormId: 0,
        mlPredictionField: '',
        mlStatusField: '',
        notifications: {
          acknowledgement: {
            attachment: false,
            body: '',
            bodyContent: '',
            emailAttachment: false,
            emailNotify: false,
            notify: false,
            slackAttachment: false,
            slackConnectorId: 0,
            slackContent: '',
            slackContentCopy: '',
            slackHubId: 0,
            slackNotify: false,
            smsContent: '',
            smsNotify: false,
            subject: '',
            subjectContent: '',
            teamsAttachment: false,
            teamsConnectorId: 0,
            teamsContent: '',
            teamsContentCopy: '',
            teamsHubId: 0,
            teamsNotify: false,
            whatsappAttachment: false,
            whatsappConnectorId: 0,
            whatsappContent: '',
            whatsappContentCopy: '',
            whatsappNotify: false,
          },
          inboxNotification: {
            actionButtons: false,
            attachment: false,
            body: '',
            bodyContent: '',
            emailAttachment: false,
            emailNotify: false,
            notify: false,
            slackAttachment: false,
            slackConnectorId: 0,
            slackContent: '',
            slackContentCopy: '',
            slackHubId: 0,
            slackNotify: false,
            smsContent: '',
            smsNotify: false,
            subject: '',
            subjectContent: '',
            teamsAttachment: false,
            teamsConnectorId: 0,
            teamsContent: '',
            teamsContentCopy: '',
            teamsHubId: 0,
            teamsNotify: false,
            whatsappAttachment: false,
            whatsappConnectorId: 0,
            whatsappContent: '',
            whatsappContentCopy: '',
            whatsappNotify: false,
          },
          markCCField: {
            attachment: false,
            body: '',
            bodyContent: '',
            fields: [],
            notify: false,
            subject: '',
            subjectContent: '',
          },
          processStage: {
            alertProcessStage: [],
            attachment: false,
            body: '',
            bodyContent: '',
            notify: false,
            subject: '',
            subjectContent: '',
          },
          userGroup: {
            alertGroup: [],
            alertUser: [],
            attachment: false,
            body: '',
            bodyContent: '',
            notify: false,
            subject: '',
            subjectContent: '',
          },
        },
        partialApprove: true,
        reopen: false,
        reopenBlockId: '',
        slaRules: [],
        slaSettings: {
          emailNotify: true,
          slaMasterFormId: 0,
          slaType: 'STANDARD',
          smsNotify: false,
          workflowFormSLAFieldId: '',
        },
        subWorkflowId: 0,
        toInitiator: false,
        userDomains: [],
        userReply: false,
        users: [],
      },
    },
    {
      color: '#fd9644',
      height: 90,
      icon: 'mdi-share-variant',
      id: 'zcZU6Mm0RR0N90Wxo2aTv',
      left: 553.0001054296257,
      top: 72,
      type: 'CONDITION',
      width: 175,
      settings: {
        aiPrediction: {},
        conditions: {
          condition: [
            {
              fieldValue: false,
              id: 'b9MxFtyCj0mZP5-W3bQVP',
              logic: 'IS_NOT_EQUALS_TO',
              name: 'N-0GtXrVEiP86zJgIHHtf',
              value: '',
            },
          ],
          groupLogic: 'ALL',
        },
        documentRequired: false,
        dynamicUser: [],
        externalUser: [],
        externalUserMail: [],
        fileSettings: {
          fileCheckList: [],
          partial: false,
        },
        footerText: '',
        formEditAccess: 'FULL',
        formEditControls: [],
        formSecureControls: [],
        formVisibilityAccess: true,
        forwardedUserAction: 'DEFAULT',
        forwardLabel: '',
        fullApprovalAction: '',
        generateCSV: false,
        generateCSVFields: [],
        generateDocument: {
          allowSubmission: false,
          documentList: [],
        },
        generatePDFFields: [],
        groups: [],
        hasFooter: false,
        hasMasterEntriesAction: false,
        initiateBy: ['USER'],
        initiateMode: 'MANUAL',
        isQuickAction: true,
        label: 'Check 1st Approver',
        mappingFieldsToForm: {
          completedAt: '',
          status: '',
        },
        masterConditions: {
          condition: [],
          masterFormId: 0,
        },
        masterFormEntries: [],
        mlCompareFields: [],
        mlCompareMaster: false,
        mlMasterFormId: 0,
        mlPredictionField: '',
        mlStatusField: '',
        notifications: {
          acknowledgement: {
            attachment: false,
            body: '',
            bodyContent: '',
            emailAttachment: false,
            emailNotify: false,
            notify: false,
            slackAttachment: false,
            slackConnectorId: 0,
            slackContent: '',
            slackContentCopy: '',
            slackHubId: 0,
            slackNotify: false,
            smsContent: '',
            smsNotify: false,
            subject: '',
            subjectContent: '',
            teamsAttachment: false,
            teamsConnectorId: 0,
            teamsContent: '',
            teamsContentCopy: '',
            teamsHubId: 0,
            teamsNotify: false,
            whatsappAttachment: false,
            whatsappConnectorId: 0,
            whatsappContent: '',
            whatsappContentCopy: '',
            whatsappNotify: false,
          },
          inboxNotification: {
            actionButtons: false,
            attachment: false,
            body: '',
            bodyContent: '',
            emailAttachment: false,
            emailNotify: false,
            notify: false,
            slackAttachment: false,
            slackConnectorId: 0,
            slackContent: '',
            slackContentCopy: '',
            slackHubId: 0,
            slackNotify: false,
            smsContent: '',
            smsNotify: false,
            subject: '',
            subjectContent: '',
            teamsAttachment: false,
            teamsConnectorId: 0,
            teamsContent: '',
            teamsContentCopy: '',
            teamsHubId: 0,
            teamsNotify: false,
            whatsappAttachment: false,
            whatsappConnectorId: 0,
            whatsappContent: '',
            whatsappContentCopy: '',
            whatsappNotify: false,
          },
          markCCField: {
            attachment: false,
            body: '',
            bodyContent: '',
            fields: [],
            notify: false,
            subject: '',
            subjectContent: '',
          },
          processStage: {
            alertProcessStage: [],
            attachment: false,
            body: '',
            bodyContent: '',
            notify: false,
            subject: '',
            subjectContent: '',
          },
          userGroup: {
            alertGroup: [],
            alertUser: [],
            attachment: false,
            body: '',
            bodyContent: '',
            notify: false,
            subject: '',
            subjectContent: '',
          },
        },
        partialApprove: true,
        reopen: false,
        reopenBlockId: '',
        slaRules: [],
        slaSettings: {
          emailNotify: true,
          slaMasterFormId: 0,
          slaType: 'STANDARD',
          smsNotify: false,
          workflowFormSLAFieldId: '',
        },
        standardCondition: true,
        subWorkflowId: 0,
        toInitiator: false,
        userDomains: [],
        userReply: false,
        users: [],
      },
    },
    {
      color: '#fd9644',
      height: 90,
      icon: 'mdi-share-variant',
      id: 'i5dt5FQHUMCFW8pRkAdd9',
      left: 673.0003198627627,
      top: 179,
      type: 'CONDITION',
      width: 175,
      settings: {
        aiPrediction: {},
        conditions: {
          condition: [
            {
              fieldValue: false,
              id: 'ZIv30ozfReyABd7zzMoxr',
              logic: 'IS_NOT_EQUALS_TO',
              name: 'N-0GtXrVEiP86zJgIHHtf',
              value: '',
            },
          ],
          groupLogic: 'ALL',
        },
        documentRequired: false,
        dynamicUser: [],
        externalUser: [],
        externalUserMail: [],
        fileSettings: {
          fileCheckList: [],
          partial: false,
        },
        footerText: '',
        formEditAccess: 'FULL',
        formEditControls: [],
        formSecureControls: [],
        formVisibilityAccess: true,
        forwardedUserAction: 'DEFAULT',
        forwardLabel: '',
        fullApprovalAction: '',
        generateCSV: false,
        generateCSVFields: [],
        generateDocument: {
          allowSubmission: false,
          documentList: [],
        },
        generatePDFFields: [],
        groups: [],
        hasFooter: false,
        hasMasterEntriesAction: false,
        initiateBy: ['USER'],
        initiateMode: 'MANUAL',
        isQuickAction: true,
        label: 'Check 1st Approver',
        mappingFieldsToForm: {
          completedAt: '',
          status: '',
        },
        masterConditions: {
          condition: [],
          masterFormId: 0,
        },
        masterFormEntries: [],
        mlCompareFields: [],
        mlCompareMaster: false,
        mlMasterFormId: 0,
        mlPredictionField: '',
        mlStatusField: '',
        notifications: {
          acknowledgement: {
            attachment: false,
            body: '',
            bodyContent: '',
            emailAttachment: false,
            emailNotify: false,
            notify: false,
            slackAttachment: false,
            slackConnectorId: 0,
            slackContent: '',
            slackContentCopy: '',
            slackHubId: 0,
            slackNotify: false,
            smsContent: '',
            smsNotify: false,
            subject: '',
            subjectContent: '',
            teamsAttachment: false,
            teamsConnectorId: 0,
            teamsContent: '',
            teamsContentCopy: '',
            teamsHubId: 0,
            teamsNotify: false,
            whatsappAttachment: false,
            whatsappConnectorId: 0,
            whatsappContent: '',
            whatsappContentCopy: '',
            whatsappNotify: false,
          },
          inboxNotification: {
            actionButtons: false,
            attachment: false,
            body: '',
            bodyContent: '',
            emailAttachment: false,
            emailNotify: false,
            notify: false,
            slackAttachment: false,
            slackConnectorId: 0,
            slackContent: '',
            slackContentCopy: '',
            slackHubId: 0,
            slackNotify: false,
            smsContent: '',
            smsNotify: false,
            subject: '',
            subjectContent: '',
            teamsAttachment: false,
            teamsConnectorId: 0,
            teamsContent: '',
            teamsContentCopy: '',
            teamsHubId: 0,
            teamsNotify: false,
            whatsappAttachment: false,
            whatsappConnectorId: 0,
            whatsappContent: '',
            whatsappContentCopy: '',
            whatsappNotify: false,
          },
          markCCField: {
            attachment: false,
            body: '',
            bodyContent: '',
            fields: [],
            notify: false,
            subject: '',
            subjectContent: '',
          },
          processStage: {
            alertProcessStage: [],
            attachment: false,
            body: '',
            bodyContent: '',
            notify: false,
            subject: '',
            subjectContent: '',
          },
          userGroup: {
            alertGroup: [],
            alertUser: [],
            attachment: false,
            body: '',
            bodyContent: '',
            notify: false,
            subject: '',
            subjectContent: '',
          },
        },
        partialApprove: true,
        reopen: false,
        reopenBlockId: '',
        slaRules: [],
        slaSettings: {
          emailNotify: true,
          slaMasterFormId: 0,
          slaType: 'STANDARD',
          smsNotify: false,
          workflowFormSLAFieldId: '',
        },
        standardCondition: true,
        subWorkflowId: 0,
        toInitiator: false,
        userDomains: [],
        userReply: false,
        users: [],
      },
    },
    {
      color: '#fd9644',
      height: 90,
      icon: 'mdi-share-variant',
      id: 'UyFStu1NRNjgXE4UUB31P',
      left: 841.0002269417367,
      top: 291.0008991084853,
      type: 'CONDITION',
      width: 175,
      settings: {
        aiPrediction: {},
        conditions: {
          condition: [
            {
              fieldValue: false,
              id: '8RK-FKkyVvdNP1BoKmbpb',
              logic: 'IS_NOT_EQUALS_TO',
              name: 'N-0GtXrVEiP86zJgIHHtf',
              value: '',
            },
          ],
          groupLogic: 'ALL',
        },
        documentRequired: false,
        dynamicUser: [],
        externalUser: [],
        externalUserMail: [],
        fileSettings: {
          fileCheckList: [],
          partial: false,
        },
        footerText: '',
        formEditAccess: 'FULL',
        formEditControls: [],
        formSecureControls: [],
        formVisibilityAccess: true,
        forwardedUserAction: 'DEFAULT',
        forwardLabel: '',
        fullApprovalAction: '',
        generateCSV: false,
        generateCSVFields: [],
        generateDocument: {
          allowSubmission: false,
          documentList: [],
        },
        generatePDFFields: [],
        groups: [],
        hasFooter: false,
        hasMasterEntriesAction: false,
        initiateBy: ['USER'],
        initiateMode: 'MANUAL',
        isQuickAction: true,
        label: 'Check 1st Approver',
        mappingFieldsToForm: {
          completedAt: '',
          status: '',
        },
        masterConditions: {
          condition: [],
          masterFormId: 0,
        },
        masterFormEntries: [],
        mlCompareFields: [],
        mlCompareMaster: false,
        mlMasterFormId: 0,
        mlPredictionField: '',
        mlStatusField: '',
        notifications: {
          acknowledgement: {
            attachment: false,
            body: '',
            bodyContent: '',
            emailAttachment: false,
            emailNotify: false,
            notify: false,
            slackAttachment: false,
            slackConnectorId: 0,
            slackContent: '',
            slackContentCopy: '',
            slackHubId: 0,
            slackNotify: false,
            smsContent: '',
            smsNotify: false,
            subject: '',
            subjectContent: '',
            teamsAttachment: false,
            teamsConnectorId: 0,
            teamsContent: '',
            teamsContentCopy: '',
            teamsHubId: 0,
            teamsNotify: false,
            whatsappAttachment: false,
            whatsappConnectorId: 0,
            whatsappContent: '',
            whatsappContentCopy: '',
            whatsappNotify: false,
          },
          inboxNotification: {
            actionButtons: false,
            attachment: false,
            body: '',
            bodyContent: '',
            emailAttachment: false,
            emailNotify: false,
            notify: false,
            slackAttachment: false,
            slackConnectorId: 0,
            slackContent: '',
            slackContentCopy: '',
            slackHubId: 0,
            slackNotify: false,
            smsContent: '',
            smsNotify: false,
            subject: '',
            subjectContent: '',
            teamsAttachment: false,
            teamsConnectorId: 0,
            teamsContent: '',
            teamsContentCopy: '',
            teamsHubId: 0,
            teamsNotify: false,
            whatsappAttachment: false,
            whatsappConnectorId: 0,
            whatsappContent: '',
            whatsappContentCopy: '',
            whatsappNotify: false,
          },
          markCCField: {
            attachment: false,
            body: '',
            bodyContent: '',
            fields: [],
            notify: false,
            subject: '',
            subjectContent: '',
          },
          processStage: {
            alertProcessStage: [],
            attachment: false,
            body: '',
            bodyContent: '',
            notify: false,
            subject: '',
            subjectContent: '',
          },
          userGroup: {
            alertGroup: [],
            alertUser: [],
            attachment: false,
            body: '',
            bodyContent: '',
            notify: false,
            subject: '',
            subjectContent: '',
          },
        },
        partialApprove: true,
        reopen: false,
        reopenBlockId: '',
        slaRules: [],
        slaSettings: {
          emailNotify: true,
          slaMasterFormId: 0,
          slaType: 'STANDARD',
          smsNotify: false,
          workflowFormSLAFieldId: '',
        },
        standardCondition: true,
        subWorkflowId: 0,
        toInitiator: false,
        userDomains: [],
        userReply: false,
        users: [],
      },
    },
    {
      color: '#A65EEA',
      height: 90,
      icon: 'mdi-account-multiple',
      id: 'FzKCP3AZN54NcgJt6XuU-',
      left: 1169.000103642683,
      top: 119.50034931579665,
      type: 'INTERNAL_ACTOR',
      width: 175,
      settings: {
        aiPrediction: {},
        conditions: {
          condition: [],
          groupLogic: 'ALL',
        },
        documentRequired: false,
        dynamicUser: [],
        externalUser: [],
        externalUserMail: [],
        fileSettings: {
          fileCheckList: [],
          partial: false,
        },
        footerText: '',
        formEditAccess: 'FULL',
        formEditControls: [],
        formSecureControls: [],
        formVisibilityAccess: true,
        forwardedUserAction: 'DEFAULT',
        forwardLabel: '',
        fullApprovalAction: '',
        generateCSV: false,
        generateCSVFields: [],
        generateDocument: {
          allowSubmission: false,
          documentList: [],
        },
        generatePDFFields: [],
        groups: [],
        hasFooter: false,
        hasMasterEntriesAction: false,
        initiateBy: ['USER'],
        initiateMode: 'MANUAL',
        isQuickAction: true,
        label: 'Approver',
        mappingFieldsToForm: {
          completedAt: '',
          status: '',
        },
        masterConditions: {
          condition: [],
          masterFormId: 0,
        },
        masterFormEntries: [],
        mlCompareFields: [],
        mlCompareMaster: false,
        mlMasterFormId: 0,
        mlPredictionField: '',
        mlStatusField: '',
        notifications: {
          acknowledgement: {
            attachment: false,
            body: '',
            bodyContent: '',
            emailAttachment: false,
            emailNotify: false,
            notify: false,
            slackAttachment: false,
            slackConnectorId: 0,
            slackContent: '',
            slackContentCopy: '',
            slackHubId: 0,
            slackNotify: false,
            smsContent: '',
            smsNotify: false,
            subject: '',
            subjectContent: '',
            teamsAttachment: false,
            teamsConnectorId: 0,
            teamsContent: '',
            teamsContentCopy: '',
            teamsHubId: 0,
            teamsNotify: false,
            whatsappAttachment: false,
            whatsappConnectorId: 0,
            whatsappContent: '',
            whatsappContentCopy: '',
            whatsappNotify: false,
          },
          inboxNotification: {
            actionButtons: false,
            attachment: false,
            body: '',
            bodyContent: '',
            emailAttachment: false,
            emailNotify: false,
            notify: false,
            slackAttachment: false,
            slackConnectorId: 0,
            slackContent: '',
            slackContentCopy: '',
            slackHubId: 0,
            slackNotify: false,
            smsContent: '',
            smsNotify: false,
            subject: '',
            subjectContent: '',
            teamsAttachment: false,
            teamsConnectorId: 0,
            teamsContent: '',
            teamsContentCopy: '',
            teamsHubId: 0,
            teamsNotify: false,
            whatsappAttachment: false,
            whatsappConnectorId: 0,
            whatsappContent: '',
            whatsappContentCopy: '',
            whatsappNotify: false,
          },
          markCCField: {
            attachment: false,
            body: '',
            bodyContent: '',
            fields: [],
            notify: false,
            subject: '',
            subjectContent: '',
          },
          processStage: {
            alertProcessStage: [],
            attachment: false,
            body: '',
            bodyContent: '',
            notify: false,
            subject: '',
            subjectContent: '',
          },
          userGroup: {
            alertGroup: [],
            alertUser: [],
            attachment: false,
            body: '',
            bodyContent: '',
            notify: false,
            subject: '',
            subjectContent: '',
          },
        },
        partialApprove: true,
        reopen: false,
        reopenBlockId: '',
        slaRules: [],
        slaSettings: {
          emailNotify: true,
          slaMasterFormId: 0,
          slaType: 'STANDARD',
          smsNotify: false,
          workflowFormSLAFieldId: '',
        },
        subWorkflowId: 0,
        toInitiator: false,
        userDomains: [],
        userReply: false,
        users: ['4'],
      },
    },
  ],
  blockStatus: 0,
  hasSLASettings: 1,
  initiateUserDomain: [],
  masterFormIds: [],
  mlPredictions: [],
  modifiedBlockIds: [],
  rules: [
    {
      confirm: false,
      fromBlockId: 'G59WQkftZGs7D9JAsua_5',
      id: 'p4nAjf6YU5o8hFveOyqs0',
      left: 228.5,
      passwordAccess: false,
      proceedAction: 'Submit',
      remarks: false,
      signature: false,
      toBlockId: 'AN_VThGrTcn0tDQOUmZ0F',
      top: 98.5,
    },
    {
      confirm: false,
      fromBlockId: 'AN_VThGrTcn0tDQOUmZ0F',
      id: '-6v7uCNRw6Y9TBdLzSbpY',
      left: 448.5,
      passwordAccess: false,
      proceedAction: 'SUCCESS',
      remarks: false,
      signature: false,
      toBlockId: 'NhB-AEDaz0WDuB3zOm1kg',
      top: 138.5,
    },
    {
      addCondition: false,
      confirm: false,
      fromBlockId: 'NhB-AEDaz0WDuB3zOm1kg',
      id: 'ZLry7ea8Fd44yAPQtKXLy',
      left: 668.5,
      passwordAccess: false,
      proceedAction: 'APPROVED',
      remarks: false,
      signature: false,
      toBlockId: 'zcZU6Mm0RR0N90Wxo2aTv',
      top: 178.5,
      settings: {},
    },
    {
      addCondition: false,
      confirm: false,
      fromBlockId: 'NhB-AEDaz0WDuB3zOm1kg',
      id: 'mOCpc9Vcjz1glaEaWE2UR',
      left: 668.5,
      passwordAccess: false,
      proceedAction: 'REJECTED',
      remarks: false,
      signature: false,
      toBlockId: 'i5dt5FQHUMCFW8pRkAdd9',
      top: 178.5,
      settings: {},
    },
    {
      addCondition: false,
      confirm: false,
      fromBlockId: 'NhB-AEDaz0WDuB3zOm1kg',
      id: 'stGp02rB_bNqeJOaL94sJ',
      left: 668.5,
      passwordAccess: false,
      proceedAction: 'PARTIALLY APPROVED',
      remarks: false,
      signature: false,
      toBlockId: 'UyFStu1NRNjgXE4UUB31P',
      top: 178.5,
      settings: {},
    },
    {
      addCondition: false,
      confirm: false,
      fromBlockId: 'srf66hYmrFs6F1tStUmul',
      id: 'df-ev3HdjhlOc7eoump3K',
      left: 1205.5005664608707,
      passwordAccess: false,
      proceedAction: 'Approve',
      remarks: false,
      signature: false,
      toBlockId: 'FzKCP3AZN54NcgJt6XuU-',
      top: 295.0005042297587,
      settings: {},
    },
    {
      addCondition: false,
      confirm: false,
      fromBlockId: 'FzKCP3AZN54NcgJt6XuU-',
      id: 'YzT_sQR8jz89Kr3Oni-Qa',
      left: 1326.000545017557,
      passwordAccess: false,
      remarks: false,
      signature: false,
      toBlockId: 'gRBdu25IaIgwy2LCK5yS0',
      top: 340.0005042297587,
      settings: {},
    },
    {
      addCondition: false,
      confirm: false,
      fromBlockId: 'zcZU6Mm0RR0N90Wxo2aTv',
      id: '8M1B3XZr--TFcDvhA8Y5D',
      left: 930.500468179016,
      passwordAccess: false,
      proceedAction: 'Satisfied',
      remarks: false,
      signature: false,
      toBlockId: 'srf66hYmrFs6F1tStUmul',
      top: 231.50040399131262,
      settings: {},
    },
    {
      addCondition: false,
      confirm: false,
      fromBlockId: 'i5dt5FQHUMCFW8pRkAdd9',
      id: 'FU67FEng_c0FtHEI_a8zw',
      left: 930.500468179016,
      passwordAccess: false,
      proceedAction: 'Satisfied',
      remarks: false,
      signature: false,
      toBlockId: 'srf66hYmrFs6F1tStUmul',
      top: 293.0005042297587,
      settings: {},
    },
    {
      addCondition: false,
      confirm: false,
      fromBlockId: 'UyFStu1NRNjgXE4UUB31P',
      id: 'WcJ4-PtNxhw6zt-RKj3vu',
      left: 848.0000839863119,
      passwordAccess: false,
      proceedAction: 'Satisfied',
      remarks: false,
      signature: false,
      toBlockId: 'srf66hYmrFs6F1tStUmul',
      top: 340.0005042297587,
      settings: {},
    },
    {
      addCondition: false,
      confirm: false,
      fromBlockId: 'zcZU6Mm0RR0N90Wxo2aTv',
      id: 'uuoclQiYLty-CkzKajAQ0',
      left: 843.0004681790158,
      passwordAccess: false,
      proceedAction: 'Not Satisfied',
      remarks: false,
      signature: false,
      toBlockId: 'FzKCP3AZN54NcgJt6XuU-',
      top: 276.50040399131274,
      settings: {},
    },
    {
      addCondition: false,
      confirm: false,
      fromBlockId: 'i5dt5FQHUMCFW8pRkAdd9',
      id: 'YDF5JdumVcg3iMFiRUJyo',
      left: 930.5004681790158,
      passwordAccess: false,
      proceedAction: 'Not Satisfied',
      remarks: false,
      signature: false,
      toBlockId: 'FzKCP3AZN54NcgJt6XuU-',
      top: 384.5005042297587,
      settings: {},
    },
    {
      addCondition: false,
      confirm: false,
      fromBlockId: 'UyFStu1NRNjgXE4UUB31P',
      id: 'DO3l31RQw0wKjJkojj3Nh',
      left: 935.5000839863121,
      passwordAccess: false,
      proceedAction: 'Not Satisfied',
      remarks: false,
      signature: false,
      toBlockId: 'FzKCP3AZN54NcgJt6XuU-',
      top: 447.0009720091733,
      settings: {},
    },
  ],
  settings: {
    general: {
      coordinator: [],
      description: '',
      fileSize: 20,
      initiateUsing: {
        formId: 10,
        repositoryId: 21,
        type: 'FORM',
      },
      kanbanSettings: [],
      linkMasterFormId: 0,
      name: 'BT_AP Agent',
      ocr: {
        credit: 0,
        required: false,
      },
      processNumberPrefix:
        '[{"id":"vi7qXYJty32zExfD6KrDh","key":"seperator","value":"-"},{"id":"la4Bs9-AHNUW1Fw__P6nC","key":"reset","value":"year"},{"id":"JNp3YEcN5F78LhbWNm9-k","key":"prefix","value":"REQ"},{"id":"Zcu4BMMBSy5xEfDLaJI8O","key":"autoIncrement","value":1}]',
      scheduleReport: {},
      slaRules: [],
      slaSettings: {
        emailNotify: true,
        slaMasterFormId: 0,
        slaType: 'STANDARD',
        smsNotify: false,
        timeZone: '',
        workDays: [],
        workflowFormSLAFieldId: '',
        workHours: {
          from: '',
          to: '',
        },
      },
      smtpEmailId: 0,
      superuser: [],
      verifiedDocument: [],
    },
    publish: {
      publishOption: 'PUBLISHED',
      publishSchedule: '',
      unpublishSchedule: '',
    },
  },
}
