import type { DomainField, Report } from './types'
import { DEFAULT_SCHEDULE } from './types'

export const REPORT_DOMAINS = [
  'Accounts Payable',
  'Document Management',
  'Workflow Automation',
  'External Portal',
  'User Sessions & Security',
] as const

export type ReportDomain = (typeof REPORT_DOMAINS)[number]

export const DOMAIN_FIELDS: Record<ReportDomain, DomainField[]> = {
  'Accounts Payable': [
    { id: 'invoiceNumber', label: 'Invoice Number', type: 'Text' },
    { id: 'vendorName', label: 'Vendor Name', type: 'Text' },
    { id: 'invoiceAmount', label: 'Invoice Amount', type: 'Number' },
    { id: 'invoiceStatus', label: 'Invoice Status', type: 'Choice' },
    { id: 'approver', label: 'Approver', type: 'User' },
    { id: 'dueDate', label: 'Due Date', type: 'Date' },
    { id: 'poNumber', label: 'PO Number', type: 'Text' },
    { id: 'costCenter', label: 'Cost Center', type: 'Choice' },
  ],
  'Document Management': [
    { id: 'documentName', label: 'Document Name', type: 'Text' },
    { id: 'repository', label: 'Repository', type: 'Choice' },
    { id: 'fileSize', label: 'File Size (KB)', type: 'Number' },
    { id: 'documentStatus', label: 'Document Status', type: 'Choice' },
    { id: 'owner', label: 'Owner', type: 'User' },
    { id: 'uploadedDate', label: 'Uploaded Date', type: 'Date' },
    { id: 'version', label: 'Version', type: 'Text' },
  ],
  'External Portal': [
    { id: 'portalName', label: 'Portal Name', type: 'Text' },
    { id: 'visitorName', label: 'Visitor Name', type: 'Text' },
    { id: 'submissionCount', label: 'Submission Count', type: 'Number' },
    { id: 'portalStatus', label: 'Portal Status', type: 'Choice' },
    { id: 'contactOwner', label: 'Contact Owner', type: 'User' },
    { id: 'lastVisit', label: 'Last Visit', type: 'Date' },
  ],
  'User Sessions & Security': [
    { id: 'userName', label: 'User Name', type: 'User' },
    { id: 'ipAddress', label: 'IP Address', type: 'Text' },
    { id: 'sessionDuration', label: 'Session Duration (min)', type: 'Number' },
    { id: 'sessionStatus', label: 'Session Status', type: 'Choice' },
    { id: 'device', label: 'Device', type: 'Choice' },
    { id: 'loginTime', label: 'Login Time', type: 'Date' },
  ],
  'Workflow Automation': [
    { id: 'workflowName', label: 'Workflow Name', type: 'Text' },
    { id: 'requestNumber', label: 'Request Number', type: 'Text' },
    { id: 'initiator', label: 'Initiator', type: 'User' },
    { id: 'currentStage', label: 'Current Stage', type: 'Choice' },
    { id: 'workflowStatus', label: 'Workflow Status', type: 'Choice' },
    { id: 'slaHours', label: 'SLA (Hours)', type: 'Number' },
    { id: 'startedDate', label: 'Started Date', type: 'Date' },
  ],
}

export const SAMPLE_ROWS: Record<ReportDomain, Record<string, string>[]> = {
  'Accounts Payable': [
    {
      approver: 'Meera Nair',
      costCenter: 'Finance',
      dueDate: '2026-09-18',
      invoiceAmount: '4,250.00',
      invoiceNumber: 'INV-10231',
      invoiceStatus: 'Pending Approval',
      poNumber: 'PO-5521',
      vendorName: 'Alpha Supplies Co.',
    },
    {
      approver: 'Ravi Kumar',
      costCenter: 'Operations',
      dueDate: '2026-09-22',
      invoiceAmount: '1,180.50',
      invoiceNumber: 'INV-10232',
      invoiceStatus: 'Approved',
      poNumber: 'PO-5522',
      vendorName: 'Bright Logistics',
    },
    {
      approver: 'Meera Nair',
      costCenter: 'Finance',
      dueDate: '2026-09-10',
      invoiceAmount: '9,875.00',
      invoiceNumber: 'INV-10233',
      invoiceStatus: 'Overdue',
      poNumber: 'PO-5523',
      vendorName: 'Crestline Tech',
    },
  ],
  'Document Management': [
    {
      documentName: 'Vendor Agreement 2026.pdf',
      documentStatus: 'Approved',
      fileSize: '1,240',
      owner: 'Sara Ahmed',
      repository: 'Contracts',
      uploadedDate: '2026-08-02',
      version: 'v3',
    },
    {
      documentName: 'Q3 Audit Report.docx',
      documentStatus: 'In Review',
      fileSize: '860',
      owner: 'John Mathew',
      repository: 'Audit',
      uploadedDate: '2026-08-14',
      version: 'v1',
    },
  ],
  'External Portal': [
    {
      contactOwner: 'Fatima Al-Sayed',
      lastVisit: '2026-09-01',
      portalName: 'Supplier Onboarding',
      portalStatus: 'Active',
      submissionCount: '12',
      visitorName: 'Global Traders LLC',
    },
    {
      contactOwner: 'John Mathew',
      lastVisit: '2026-08-29',
      portalName: 'Customer Support',
      portalStatus: 'Inactive',
      submissionCount: '4',
      visitorName: 'Zenith Retail',
    },
  ],
  'User Sessions & Security': [
    {
      device: 'Chrome / Windows',
      ipAddress: '192.168.1.24',
      loginTime: '2026-09-06 09:12',
      sessionDuration: '58',
      sessionStatus: 'Active',
      userName: 'Meera Nair',
    },
    {
      device: 'Safari / macOS',
      ipAddress: '10.0.0.15',
      loginTime: '2026-09-06 08:40',
      sessionDuration: '12',
      sessionStatus: 'Expired',
      userName: 'Ravi Kumar',
    },
  ],
  'Workflow Automation': [
    {
      currentStage: 'Manager Approval',
      initiator: 'Sara Ahmed',
      requestNumber: 'REQ-3391',
      slaHours: '24',
      startedDate: '2026-09-04',
      workflowName: 'Purchase Requisition',
      workflowStatus: 'In Progress',
    },
    {
      currentStage: 'Completed',
      initiator: 'John Mathew',
      requestNumber: 'REQ-3392',
      slaHours: '8',
      startedDate: '2026-09-02',
      workflowName: 'Leave Request',
      workflowStatus: 'Completed',
    },
    {
      currentStage: 'Finance Review',
      initiator: 'Fatima Al-Sayed',
      requestNumber: 'REQ-3393',
      slaHours: '48',
      startedDate: '2026-09-05',
      workflowName: 'Expense Claim',
      workflowStatus: 'Escalated',
    },
  ],
}

export const FILTER_OPERATORS = [
  { label: 'Equals', value: 'equals' },
  { label: 'Not Equals', value: 'notEquals' },
  { label: 'Contains', value: 'contains' },
  { label: 'Greater Than', value: 'greaterThan' },
  { label: 'Less Than', value: 'lessThan' },
  { label: 'Between', value: 'between' },
  { label: 'Is Empty', value: 'isEmpty' },
  { label: 'Is Not Empty', value: 'isNotEmpty' },
]

export const CALC_OPTIONS = [
  { label: 'None', value: 'None' },
  { label: 'Sum', value: 'Sum' },
  { label: 'Average', value: 'Average' },
  { label: 'Count', value: 'Count' },
  { label: 'Min', value: 'Min' },
  { label: 'Max', value: 'Max' },
]

export const SCHEDULE_RECURRENCE_OPTIONS = [
  { label: 'Daily', value: 'Daily' },
  { label: 'Weekly', value: 'Weekly' },
  { label: 'Monthly', value: 'Monthly' },
]

export const SCHEDULE_DAY_OPTIONS = [
  { label: 'Monday', value: 'Monday' },
  { label: 'Tuesday', value: 'Tuesday' },
  { label: 'Wednesday', value: 'Wednesday' },
  { label: 'Thursday', value: 'Thursday' },
  { label: 'Friday', value: 'Friday' },
  { label: 'Saturday', value: 'Saturday' },
  { label: 'Sunday', value: 'Sunday' },
]

export const SCHEDULE_FORMAT_OPTIONS = [
  { label: 'PDF', value: 'PDF' },
  { label: 'Excel', value: 'Excel' },
  { label: 'CSV', value: 'CSV' },
]

export const SCHEDULE_TIMEZONE_OPTIONS = [
  { label: 'UTC', value: 'UTC' },
  { label: 'GST (Dubai)', value: 'GST' },
  { label: 'IST (India)', value: 'IST' },
  { label: 'EST (New York)', value: 'EST' },
]

const now = new Date()
const daysAgo = (days: number) =>
  new Date(now.getTime() - days * 86400000).toISOString()

export const SEED_REPORTS: Report[] = [
  {
    createdAt: daysAgo(40),
    customFields: [],
    description: 'Overview of outstanding vendor invoices and approval status.',
    domain: 'Accounts Payable',
    fields: [
      'invoiceNumber',
      'vendorName',
      'invoiceAmount',
      'invoiceStatus',
      'dueDate',
    ],
    fieldSettings: {
      invoiceAmount: {
        calc: 'Sum',
        colType: 'value',
        label: 'Invoice Amount',
        width: 160,
      },
      invoiceNumber: {
        calc: 'None',
        colType: 'value',
        label: 'Invoice Number',
        width: 160,
      },
      invoiceStatus: {
        calc: 'None',
        colType: 'status',
        label: 'Status',
        statusBase: 'invoiceStatus',
        statusDefault: 'gray',
        statusRules: [
          { color: 'red', id: 'r1', label: 'Overdue', match: 'Overdue' },
          { color: 'green', id: 'r2', label: 'Approved', match: 'Approved' },
          {
            color: 'orange',
            id: 'r3',
            label: 'Pending',
            match: 'Pending Approval',
          },
        ],
        width: 160,
      },
      vendorName: {
        calc: 'None',
        colType: 'value',
        label: 'Vendor Name',
        width: 180,
      },
    },
    filters: [
      {
        field: 'invoiceStatus',
        id: 'f1',
        operator: 'notEquals',
        value: 'Approved',
      },
    ],
    id: 'rpt-1',
    modified: daysAgo(2),
    name: 'Outstanding Invoices',
    owner: 'Meera Nair',
    runs: 128,
    schedule: {
      ...DEFAULT_SCHEDULE,
      recipients: ['meera.nair'],
      subject: 'Outstanding Invoices Report',
    },
    scheduled: true,
    sharedGroups: ['finance-team'],
    sharedUsers: [],
    sourceFormId: '',
    sourceType: 'Workflow',
    status: 'Published',
    visibility: 'Selected Groups',
  },
  {
    createdAt: daysAgo(15),
    customFields: [],
    description: 'Tracks active workflow requests across all departments.',
    domain: 'Workflow Automation',
    fields: [
      'workflowName',
      'requestNumber',
      'initiator',
      'currentStage',
      'workflowStatus',
    ],
    fieldSettings: {
      currentStage: {
        calc: 'None',
        colType: 'value',
        label: 'Current Stage',
        width: 160,
      },
      initiator: {
        calc: 'None',
        colType: 'value',
        label: 'Initiator',
        width: 160,
      },
      requestNumber: {
        calc: 'Count',
        colType: 'value',
        label: 'Request Number',
        width: 150,
      },
      workflowName: {
        calc: 'None',
        colType: 'value',
        label: 'Workflow Name',
        width: 180,
      },
      workflowStatus: {
        calc: 'None',
        colType: 'status',
        label: 'Status',
        statusBase: 'workflowStatus',
        statusDefault: 'gray',
        statusRules: [
          { color: 'green', id: 'r1', label: 'Completed', match: 'Completed' },
          { color: 'red', id: 'r2', label: 'Escalated', match: 'Escalated' },
          {
            color: 'blue',
            id: 'r3',
            label: 'In Progress',
            match: 'In Progress',
          },
        ],
        width: 150,
      },
    },
    filters: [],
    id: 'rpt-2',
    modified: daysAgo(1),
    name: 'Active Workflow Requests',
    owner: 'John Mathew',
    runs: 64,
    schedule: DEFAULT_SCHEDULE,
    scheduled: false,
    sharedGroups: [],
    sharedUsers: [],
    sourceFormId: '',
    sourceType: 'Workflow',
    status: 'Published',
    visibility: 'Private',
  },
  {
    createdAt: daysAgo(5),
    customFields: [],
    description: 'Draft report exploring document repository storage usage.',
    domain: 'Document Management',
    fields: ['documentName', 'repository', 'fileSize', 'documentStatus'],
    fieldSettings: {
      documentName: {
        calc: 'None',
        colType: 'value',
        label: 'Document Name',
        width: 200,
      },
      documentStatus: {
        calc: 'None',
        colType: 'value',
        label: 'Status',
        width: 140,
      },
      fileSize: {
        calc: 'Sum',
        colType: 'value',
        label: 'File Size (KB)',
        width: 140,
      },
      repository: {
        calc: 'None',
        colType: 'value',
        label: 'Repository',
        width: 160,
      },
    },
    filters: [],
    id: 'rpt-3',
    modified: daysAgo(1),
    name: 'Repository Storage Usage',
    owner: 'Sara Ahmed',
    runs: 0,
    schedule: DEFAULT_SCHEDULE,
    scheduled: false,
    sharedGroups: [],
    sharedUsers: [],
    sourceFormId: '',
    sourceType: 'Folder',
    status: 'Draft',
    visibility: 'Private',
  },
  {
    createdAt: daysAgo(60),
    customFields: [],
    description: 'Weekly digest of external portal engagement.',
    domain: 'External Portal',
    fields: [
      'portalName',
      'visitorName',
      'submissionCount',
      'portalStatus',
      'lastVisit',
    ],
    fieldSettings: {
      lastVisit: {
        calc: 'None',
        colType: 'value',
        label: 'Last Visit',
        width: 150,
      },
      portalName: {
        calc: 'None',
        colType: 'value',
        label: 'Portal Name',
        width: 180,
      },
      portalStatus: {
        calc: 'None',
        colType: 'status',
        label: 'Status',
        statusBase: 'portalStatus',
        statusDefault: 'gray',
        statusRules: [
          { color: 'green', id: 'r1', label: 'Active', match: 'Active' },
          { color: 'gray', id: 'r2', label: 'Inactive', match: 'Inactive' },
        ],
        width: 140,
      },
      submissionCount: {
        calc: 'Sum',
        colType: 'value',
        label: 'Submissions',
        width: 140,
      },
      visitorName: {
        calc: 'None',
        colType: 'value',
        label: 'Visitor Name',
        width: 180,
      },
    },
    filters: [
      { field: 'portalStatus', id: 'f1', operator: 'equals', value: 'Active' },
    ],
    id: 'rpt-4',
    modified: daysAgo(7),
    name: 'Portal Engagement Digest',
    owner: 'Fatima Al-Sayed',
    runs: 312,
    schedule: {
      ...DEFAULT_SCHEDULE,
      recipients: ['fatima.alsayed', 'john.mathew'],
      recurrence: 'Weekly',
      subject: 'Weekly Portal Engagement Digest',
    },
    scheduled: true,
    sharedGroups: [],
    sharedUsers: ['john.mathew'],
    sourceFormId: '',
    sourceType: 'Workflow',
    status: 'Published',
    visibility: 'Selected Users',
  },
  {
    createdAt: daysAgo(3),
    customFields: [],
    description: 'Security audit of active and expired user sessions.',
    domain: 'User Sessions & Security',
    fields: [
      'userName',
      'ipAddress',
      'sessionDuration',
      'sessionStatus',
      'loginTime',
    ],
    fieldSettings: {
      ipAddress: {
        calc: 'None',
        colType: 'value',
        label: 'IP Address',
        width: 150,
      },
      loginTime: {
        calc: 'None',
        colType: 'value',
        label: 'Login Time',
        width: 160,
      },
      sessionDuration: {
        calc: 'Average',
        colType: 'value',
        label: 'Duration (min)',
        width: 150,
      },
      sessionStatus: {
        calc: 'None',
        colType: 'status',
        label: 'Status',
        statusBase: 'sessionStatus',
        statusDefault: 'gray',
        statusRules: [
          { color: 'green', id: 'r1', label: 'Active', match: 'Active' },
          { color: 'gray', id: 'r2', label: 'Expired', match: 'Expired' },
        ],
        width: 130,
      },
      userName: {
        calc: 'None',
        colType: 'value',
        label: 'User Name',
        width: 160,
      },
    },
    filters: [],
    id: 'rpt-5',
    modified: daysAgo(3),
    name: 'Session Security Audit',
    owner: 'Meera Nair',
    runs: 9,
    schedule: DEFAULT_SCHEDULE,
    scheduled: false,
    sharedGroups: ['it-admins'],
    sharedUsers: [],
    sourceFormId: '',
    sourceType: 'Workflow',
    status: 'Draft',
    visibility: 'Selected Groups',
  },
]
