version: '3.8'

services:
  app:
    image: ghcr.io/tech-ezofis-git/ezofis-app-v6/app:latest
    ports:
      - "80:80"
    restart: always

  api:
    image: ghcr.io/tech-ezofis-git/ezofis-app-v6/api:latest
    restart: always

  agents:
    image: ghcr.io/tech-ezofis-git/ezofis-app-v6/agents:latest
    restart: always
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: always
