export type AppView='explorer'|'documents'|'details'|'editMetadata'|'aiSummary'|'share'|'workflow'
export type ExplorerView='list'|'grid'
export interface TreeNode{id:string;title:string;parentId?:string;iconKey?:string;children?:TreeNode[]}
export interface FolderItem{id:string;title:string;iconKey?:string;itemsText:string;modifiedText:string;sizeText:string}
export interface FileItem{id:string;name:string;type:string;date:string;amount?:string;status:string;ocr:number;supplier?:string;invoiceNo?:string;poNo?:string;risk?:'low'|'medium'|'high';source?:string;fileUrl?:string}
export interface KeyValue{label:string;value:string}
export interface InfoCardData{id:string;title:string;iconKey:string;rows:KeyValue[]}
export interface DocumentDetail{documentId:string;fileName:string;fileType:string;fileUrl?:string;alert?:{title:string;subtitle:string;badge:string};infoCards:InfoCardData[];lineItems:Array<Record<string,string>>;tabs:{timeline:Array<{title:string;subtitle:string;iconKey:string}>;comments:Array<{author:string;date:string;message:string}>;relatedDocs:Array<{name:string;type:string;status:string}>}}
export interface MetadataSection{id:string;title:string;fields:Array<{key:string;label:string;type:'text'|'date'|'select';value:string;required?:boolean;options?:string[]}>}
export interface AiSummaryData{documentId:string;engineTitle:string;engineSubtitle:string;confidence:number;summary:string;facts:Array<{label:string;value:string}>;checks:Array<{label:string;status:string;iconKey:string}>;recommendations:string[];insight:string}
export interface ShareData{documentId:string;invitePermissions:string[];sharedWith:Array<{initials:string;name:string;email:string;permission:string;date:string}>;link:string;permissions:Array<{label:string;text:string;iconKey:string}>}
export interface WorkflowData{documentId:string;document:{name:string;supplier:string;amount:string;date:string;status:string};templates:Array<{id:string;title:string;description:string;levels:string;eta:string;recommended?:boolean}>;approvers:Array<{id:string;name:string}>;priorities:string[]}
