export const dummyWorkflowJson = {
  "blocks": [
    {
      "id": "G59WQkftZGs7D9JAsua_5",
      "left": 54,
      "top": 54,
      "width": 175,
      "height": 90,
      "color": "#2BCCBA",
      "icon": "mdi-flag",
      "type": "START",
      "settings": {
        "label": "Initiator",
        "initiateMode": "AUTOMATIC",
        "initiateBy": [
          "EMAIL"
        ],
        "users": [],
        "groups": [],
        "userDomains": [],
        "dynamicUser": [],
        "externalUser": [],
        "externalUserMail": [],
        "forwardLabel": "",
        "forwardedUserAction": "DEFAULT",
        "partialApprove": true,
        "fullApprovalAction": "",
        "formEditAccess": "FULL",
        "formEditControls": [],
        "formVisibilityAccess": true,
        "formSecureControls": [],
        "documentRequired": false,
        "generatePDFFields": [],
        "generateCSV": false,
        "generateCSVFields": [],
        "reopen": false,
        "reopenBlockId": "",
        "conditions": {
          "groupLogic": "ALL",
          "condition": []
        },
        "masterConditions": {
          "masterFormId": 0,
          "condition": []
        },
        "notifications": {
          "acknowledgement": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "emailNotify": false,
            "smsNotify": false,
            "smsContent": "",
            "slackNotify": false,
            "slackContent": "",
            "slackContentCopy": "",
            "slackConnectorId": 0,
            "slackHubId": 0,
            "teamsNotify": false,
            "teamsContent": "",
            "teamsContentCopy": "",
            "teamsConnectorId": 0,
            "teamsHubId": 0,
            "emailAttachment": false,
            "slackAttachment": false,
            "teamsAttachment": false,
            "whatsappNotify": false,
            "whatsappContent": "",
            "whatsappContentCopy": "",
            "whatsappConnectorId": 0,
            "whatsappAttachment": false
          },
          "inboxNotification": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "actionButtons": false,
            "emailNotify": false,
            "smsNotify": false,
            "smsContent": "",
            "slackNotify": false,
            "slackContent": "",
            "slackContentCopy": "",
            "slackConnectorId": 0,
            "slackHubId": 0,
            "teamsNotify": false,
            "teamsContent": "",
            "teamsContentCopy": "",
            "teamsConnectorId": 0,
            "teamsHubId": 0,
            "emailAttachment": false,
            "slackAttachment": false,
            "teamsAttachment": false,
            "whatsappNotify": false,
            "whatsappContent": "",
            "whatsappContentCopy": "",
            "whatsappConnectorId": 0,
            "whatsappAttachment": false
          },
          "markCCField": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "fields": []
          },
          "processStage": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "alertProcessStage": []
          },
          "userGroup": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "alertUser": [],
            "alertGroup": []
          }
        },
        "slaSettings": {
          "slaType": "STANDARD",
          "slaMasterFormId": 0,
          "workflowFormSLAFieldId": "",
          "emailNotify": true,
          "smsNotify": false
        },
        "slaRules": [],
        "fileSettings": {
          "fileCheckList": [],
          "partial": false
        },
        "userReply": false,
        "toInitiator": false,
        "isQuickAction": true,
        "mlCompareMaster": false,
        "mlMasterFormId": 0,
        "mlCompareFields": [],
        "mlPredictionField": "",
        "mlStatusField": "",
        "subWorkflowId": 0,
        "aiPrediction": {},
        "hasMasterEntriesAction": false,
        "masterFormEntries": [],
        "generateDocument": {
          "documentList": [],
          "allowSubmission": false
        },
        "mappingFieldsToForm": {
          "status": "",
          "completedAt": ""
        },
        "mailInitiate": {
          "mailSettingsId": 0,
          "connectorType": "gmail",
          "connectorId": 10,
          "conditions": {
            "hasAttachment": false,
            "attachment": {
              "hasFileName": "ANY",
              "hasFileFormat": "ANY",
              "hasOcrData": "ANY",
              "filename": [],
              "fileType": [],
              "ocrData": [],
              "request": "SINGLE"
            },
            "mailSubject": [],
            "mailContent": [],
            "fromAddress": [],
            "fromDomain": []
          }
        }
      }
    },
    {
      "id": "gRBdu25IaIgwy2LCK5yS0",
      "left": 1409.000813058978,
      "top": 340.50077760733865,
      "width": 175,
      "height": 90,
      "color": "#FC5C65",
      "icon": "mdi-flag",
      "type": "END",
      "settings": {
        "label": "Completed",
        "initiateMode": "MANUAL",
        "initiateBy": [
          "USER"
        ],
        "users": [],
        "groups": [],
        "userDomains": [],
        "dynamicUser": [],
        "externalUser": [],
        "externalUserMail": [],
        "forwardLabel": "",
        "forwardedUserAction": "DEFAULT",
        "partialApprove": true,
        "fullApprovalAction": "",
        "formEditAccess": "FULL",
        "formEditControls": [],
        "formVisibilityAccess": true,
        "formSecureControls": [],
        "documentRequired": false,
        "generatePDFFields": [],
        "hasFooter": false,
        "footerText": "",
        "generateCSV": false,
        "generateCSVFields": [],
        "reopen": false,
        "reopenBlockId": "",
        "conditions": {
          "groupLogic": "ALL",
          "condition": []
        },
        "masterConditions": {
          "masterFormId": 0,
          "condition": []
        },
        "notifications": {
          "acknowledgement": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "emailNotify": false,
            "smsNotify": false,
            "smsContent": "",
            "slackNotify": false,
            "slackContent": "",
            "slackContentCopy": "",
            "slackConnectorId": 0,
            "slackHubId": 0,
            "teamsNotify": false,
            "teamsContent": "",
            "teamsContentCopy": "",
            "teamsConnectorId": 0,
            "teamsHubId": 0,
            "emailAttachment": false,
            "slackAttachment": false,
            "teamsAttachment": false,
            "whatsappNotify": false,
            "whatsappContent": "",
            "whatsappContentCopy": "",
            "whatsappConnectorId": 0,
            "whatsappAttachment": false
          },
          "inboxNotification": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "actionButtons": false,
            "emailNotify": false,
            "smsNotify": false,
            "smsContent": "",
            "slackNotify": false,
            "slackContent": "",
            "slackContentCopy": "",
            "slackConnectorId": 0,
            "slackHubId": 0,
            "teamsNotify": false,
            "teamsContent": "",
            "teamsContentCopy": "",
            "teamsConnectorId": 0,
            "teamsHubId": 0,
            "emailAttachment": false,
            "slackAttachment": false,
            "teamsAttachment": false,
            "whatsappNotify": false,
            "whatsappContent": "",
            "whatsappContentCopy": "",
            "whatsappConnectorId": 0,
            "whatsappAttachment": false
          },
          "markCCField": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "fields": []
          },
          "processStage": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "alertProcessStage": []
          },
          "userGroup": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "alertUser": [],
            "alertGroup": []
          }
        },
        "slaSettings": {
          "slaType": "STANDARD",
          "slaMasterFormId": 0,
          "workflowFormSLAFieldId": "",
          "emailNotify": true,
          "smsNotify": false
        },
        "slaRules": [],
        "fileSettings": {
          "fileCheckList": [],
          "partial": false
        },
        "userReply": false,
        "toInitiator": false,
        "isQuickAction": true,
        "mlCompareMaster": false,
        "mlMasterFormId": 0,
        "mlCompareFields": [],
        "mlPredictionField": "",
        "mlStatusField": "",
        "subWorkflowId": 0,
        "aiPrediction": {},
        "hasMasterEntriesAction": false,
        "masterFormEntries": [],
        "generateDocument": {
          "documentList": [],
          "allowSubmission": false
        },
        "mappingFieldsToForm": {
          "status": "",
          "completedAt": ""
        }
      }
    },
    {
      "id": "AN_VThGrTcn0tDQOUmZ0F",
      "left": 54,
      "top": 206.0003402032106,
      "width": 175,
      "height": 90,
      "color": "#eea557",
      "icon": "mdi-file-find",
      "type": "OCR",
      "settings": {
        "label": "AI OCR 1",
        "initiateMode": "MANUAL",
        "initiateBy": [
          "USER"
        ],
        "users": [],
        "groups": [],
        "userDomains": [],
        "dynamicUser": [],
        "externalUser": [],
        "externalUserMail": [],
        "forwardLabel": "",
        "forwardedUserAction": "DEFAULT",
        "partialApprove": true,
        "fullApprovalAction": "",
        "formEditAccess": "FULL",
        "formEditControls": [],
        "formVisibilityAccess": true,
        "formSecureControls": [],
        "documentRequired": false,
        "generatePDFFields": [],
        "generateCSV": false,
        "generateCSVFields": [],
        "reopen": false,
        "reopenBlockId": "",
        "conditions": {
          "groupLogic": "ALL",
          "condition": []
        },
        "masterConditions": {
          "masterFormId": 0,
          "condition": []
        },
        "notifications": {
          "acknowledgement": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "emailNotify": false,
            "smsNotify": false,
            "smsContent": "",
            "slackNotify": false,
            "slackContent": "",
            "slackContentCopy": "",
            "slackConnectorId": 0,
            "slackHubId": 0,
            "teamsNotify": false,
            "teamsContent": "",
            "teamsContentCopy": "",
            "teamsConnectorId": 0,
            "teamsHubId": 0,
            "emailAttachment": false,
            "slackAttachment": false,
            "teamsAttachment": false,
            "whatsappNotify": false,
            "whatsappContent": "",
            "whatsappContentCopy": "",
            "whatsappConnectorId": 0,
            "whatsappAttachment": false
          },
          "inboxNotification": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "actionButtons": false,
            "emailNotify": false,
            "smsNotify": false,
            "smsContent": "",
            "slackNotify": false,
            "slackContent": "",
            "slackContentCopy": "",
            "slackConnectorId": 0,
            "slackHubId": 0,
            "teamsNotify": false,
            "teamsContent": "",
            "teamsContentCopy": "",
            "teamsConnectorId": 0,
            "teamsHubId": 0,
            "emailAttachment": false,
            "slackAttachment": false,
            "teamsAttachment": false,
            "whatsappNotify": false,
            "whatsappContent": "",
            "whatsappContentCopy": "",
            "whatsappConnectorId": 0,
            "whatsappAttachment": false
          },
          "markCCField": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "fields": []
          },
          "processStage": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "alertProcessStage": []
          },
          "userGroup": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "alertUser": [],
            "alertGroup": []
          }
        },
        "slaSettings": {
          "slaType": "STANDARD",
          "slaMasterFormId": 0,
          "workflowFormSLAFieldId": "",
          "emailNotify": true,
          "smsNotify": false
        },
        "slaRules": [],
        "ocrAgent": {
          "region": "US & CANADA",
          "selectedOcrPrompt": 1,
          "ocrPrompt": "You are an expert invoice parser.  Extract data according to the visible table structure and column headers in the invoice.  For every line item, only extract fields that correspond to the table columns for that row (do not include header/shipment fields in line items).  Merge all multi-line content within a single cell into that field (especially for the \"description\" and \"notes\").  Shipment/invoice-level fields such as CAR NUMBER, SHIPPING POINT, SHIPMENT NUMBER, CURRENCY, etc., must go ONLY into the \"header\", not as line item fields.  Use this schema:  {field_mapping}    If a field is missing for a line item or header, use null.  Do not invent fields. Do not add any header or shipment data to any line item. Return ONLY the JSON object, no explanation.  Invoice Text:  {txt}",
          "ocrPromptId": 1,
          "ocrSpecificInstruction": "",
          "ocrEntryId": 0,
          "outputSchema": "ARCHIVE",
          "promptSchema": "{\"header\":{\"car_number\":\"string or null\",\"shipment_number\":\"string or null\",\"shipping_point\":\"string or null\",\"currency\":\"string or null\",\"invoice_number\":\"string or null\",\"invoice_date\":\"string or null\",\"order_number\":\"string or null\",\"customer_order_number\":\"string or null\",\"our_order_number\":\"string or null\",\"sales_order_number\":\"string or null\",\"purchase_order_number\":\"string or null\",\"order_date\":\"string or null\",\"supplier_name\":\"string or null\",\"supplier_address\":\"string or null\",\"supplier_phone\":\"string or null\",\"supplier_email\":\"string or null\",\"supplier_tax_id\":\"string or null\",\"customer_name\":\"string or null\",\"customer_address\":\"string or null\",\"customer_phone\":\"string or null\",\"customer_email\":\"string or null\",\"customer_tax_id\":\"string or null\",\"ship_to_name\":\"string or null\",\"ship_to_address\":\"string or null\",\"bill_to_name\":\"string or null\",\"bill_to_address\":\"string or null\",\"remit_to_name\":\"string or null\",\"remit_to_address\":\"string or null\",\"tax_id\":\"string or null\",\"tax_registration_number\":\"string or null\",\"vat_number\":\"string or null\",\"payment_terms\":\"string or null\",\"payment_method\":\"string or null\",\"payment_reference\":\"string or null\",\"bank_account_number\":\"string or null\",\"iban\":\"string or null\",\"swift_code\":\"string or null\",\"total_before_tax\":\"string or null\",\"tax_amount\":\"string or null\",\"tax_rate\":\"string or null\",\"shipping_charges\":\"string or null\",\"discount\":\"string or null\",\"total_due\":\"string or null\",\"amount_paid\":\"string or null\",\"balance_due\":\"string or null\",\"due_date\":\"string or null\",\"invoice_status\":\"string or null\",\"reference_number\":\"string or null\",\"project_code\":\"string or null\",\"department\":\"string or null\",\"contact_person\":\"string or null\",\"notes\":\"string or null\",\"additional_info\":\"string or null\"},\"line_items\":[{\"quantity\":\"string or null\",\"units\":\"string or null\",\"description\":\"string or null\",\"footage\":\"string or null\",\"price\":\"string or null\",\"amount\":\"string or null\",\"notes\":\"string or null\"}]}"
        },
        "fileSettings": {
          "fileCheckList": [],
          "partial": false
        },
        "userReply": false,
        "toInitiator": false,
        "isQuickAction": true,
        "mlCompareMaster": false,
        "mlMasterFormId": 0,
        "mlCompareFields": [],
        "mlPredictionField": "",
        "mlStatusField": "",
        "subWorkflowId": 0,
        "aiPrediction": {},
        "hasMasterEntriesAction": false,
        "masterFormEntries": [],
        "generateDocument": {
          "documentList": [],
          "allowSubmission": false
        },
        "mappingFieldsToForm": {
          "status": "",
          "completedAt": ""
        },
        "hasFooter": false,
        "footerText": "",
        "addConditionRule": false,
        "setConditionNotification": false
      }
    },
    {
      "id": "NhB-AEDaz0WDuB3zOm1kg",
      "left": 304.9996622678091,
      "top": 161,
      "width": 175,
      "height": 90,
      "color": "#c37df3ff",
      "icon": "mdi-creation",
      "type": "AP_AGENT",
      "settings": {
        "label": "AP AGENT 1",
        "initiateMode": "MANUAL",
        "initiateBy": [
          "USER"
        ],
        "users": [],
        "groups": [],
        "userDomains": [],
        "dynamicUser": [],
        "externalUser": [],
        "externalUserMail": [],
        "forwardLabel": "",
        "forwardedUserAction": "DEFAULT",
        "partialApprove": true,
        "fullApprovalAction": "",
        "formEditAccess": "FULL",
        "formEditControls": [],
        "formVisibilityAccess": true,
        "formSecureControls": [],
        "documentRequired": false,
        "generatePDFFields": [],
        "generateCSV": false,
        "generateCSVFields": [],
        "reopen": false,
        "reopenBlockId": "",
        "conditions": {
          "groupLogic": "ALL",
          "condition": []
        },
        "masterConditions": {
          "masterFormId": 0,
          "condition": []
        },
        "notifications": {
          "acknowledgement": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "emailNotify": false,
            "smsNotify": false,
            "smsContent": "",
            "slackNotify": false,
            "slackContent": "",
            "slackContentCopy": "",
            "slackConnectorId": 0,
            "slackHubId": 0,
            "teamsNotify": false,
            "teamsContent": "",
            "teamsContentCopy": "",
            "teamsConnectorId": 0,
            "teamsHubId": 0,
            "emailAttachment": false,
            "slackAttachment": false,
            "teamsAttachment": false,
            "whatsappNotify": false,
            "whatsappContent": "",
            "whatsappContentCopy": "",
            "whatsappConnectorId": 0,
            "whatsappAttachment": false
          },
          "inboxNotification": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "actionButtons": false,
            "emailNotify": false,
            "smsNotify": false,
            "smsContent": "",
            "slackNotify": false,
            "slackContent": "",
            "slackContentCopy": "",
            "slackConnectorId": 0,
            "slackHubId": 0,
            "teamsNotify": false,
            "teamsContent": "",
            "teamsContentCopy": "",
            "teamsConnectorId": 0,
            "teamsHubId": 0,
            "emailAttachment": false,
            "slackAttachment": false,
            "teamsAttachment": false,
            "whatsappNotify": false,
            "whatsappContent": "",
            "whatsappContentCopy": "",
            "whatsappConnectorId": 0,
            "whatsappAttachment": false
          },
          "markCCField": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "fields": []
          },
          "processStage": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "alertProcessStage": []
          },
          "userGroup": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "alertUser": [],
            "alertGroup": []
          }
        },
        "slaSettings": {
          "slaType": "STANDARD",
          "slaMasterFormId": 0,
          "workflowFormSLAFieldId": "",
          "emailNotify": true,
          "smsNotify": false
        },
        "slaRules": [],
        "apAgent": {
          "fieldScore": [
            {
              "id": "QFr13_VKqcZeNOpTHlBVj",
              "label": "Supplier Name",
              "value": 35
            },
            {
              "id": "GFzbmdwJjsyK4N3-86uL8",
              "label": "PO Number",
              "value": 35
            },
            {
              "id": "JZRlTZMHzNp7eC14J9dZ6",
              "label": "Currency",
              "value": 10
            },
            {
              "id": "renIraRiO-flNSlQdhrtE",
              "label": "Total Due",
              "value": 10
            },
            {
              "id": "Nv5fQ5VJNNvhOnTJ3lUhx",
              "label": "Line Item",
              "value": 10
            }
          ],
          "decisionApprove": 90,
          "decisionPartial": 60,
          "decisionReject": 0,
          "formId": 14,
          "resource": "FORM",
          "features": [
            "DUPLICATE_DETECT",
            "BACKORDER_DETECT"
          ],
          "connectorId": 0,
          "invoiceType": "PO_INVOICE",
          "matchingType": "2_WAY_MATCH",
          "vendorValidationRequired": true,
          "vendorMasterId": 11,
          "syncGLAccountRequired": true,
          "syncGLAccount": 15,
          "syncMatterInfoRequired": true,
          "syncMatterInfo": 13
        },
        "fileSettings": {
          "fileCheckList": [],
          "partial": false
        },
        "userReply": false,
        "toInitiator": false,
        "isQuickAction": true,
        "mlCompareMaster": false,
        "mlMasterFormId": 0,
        "mlCompareFields": [],
        "mlPredictionField": "",
        "mlStatusField": "",
        "subWorkflowId": 0,
        "aiPrediction": {},
        "hasMasterEntriesAction": false,
        "masterFormEntries": [],
        "generateDocument": {
          "documentList": [],
          "allowSubmission": false
        },
        "mappingFieldsToForm": {
          "status": "",
          "completedAt": ""
        },
        "hasFooter": false,
        "footerText": ""
      }
    },
    {
      "id": "srf66hYmrFs6F1tStUmul",
      "left": 841.0002269417367,
      "top": 463.50125753686797,
      "width": 175,
      "height": 90,
      "color": "#A65EEA",
      "icon": "mdi-account-multiple",
      "type": "INTERNAL_ACTOR",
      "settings": {
        "label": "Verifier",
        "initiateMode": "MANUAL",
        "initiateBy": [
          "USER"
        ],
        "users": [],
        "groups": [],
        "userDomains": [],
        "dynamicUser": [
          "N-0GtXrVEiP86zJgIHHtf"
        ],
        "externalUser": [],
        "externalUserMail": [],
        "forwardLabel": "",
        "forwardedUserAction": "DEFAULT",
        "partialApprove": true,
        "fullApprovalAction": "",
        "formEditAccess": "FULL",
        "formEditControls": [],
        "formVisibilityAccess": true,
        "formSecureControls": [],
        "documentRequired": false,
        "generatePDFFields": [],
        "generateCSV": false,
        "generateCSVFields": [],
        "reopen": false,
        "reopenBlockId": "",
        "conditions": {
          "groupLogic": "ALL",
          "condition": []
        },
        "masterConditions": {
          "masterFormId": 0,
          "condition": []
        },
        "notifications": {
          "acknowledgement": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "emailNotify": false,
            "smsNotify": false,
            "smsContent": "",
            "slackNotify": false,
            "slackContent": "",
            "slackContentCopy": "",
            "slackConnectorId": 0,
            "slackHubId": 0,
            "teamsNotify": false,
            "teamsContent": "",
            "teamsContentCopy": "",
            "teamsConnectorId": 0,
            "teamsHubId": 0,
            "emailAttachment": false,
            "slackAttachment": false,
            "teamsAttachment": false,
            "whatsappNotify": false,
            "whatsappContent": "",
            "whatsappContentCopy": "",
            "whatsappConnectorId": 0,
            "whatsappAttachment": false
          },
          "inboxNotification": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "actionButtons": false,
            "emailNotify": false,
            "smsNotify": false,
            "smsContent": "",
            "slackNotify": false,
            "slackContent": "",
            "slackContentCopy": "",
            "slackConnectorId": 0,
            "slackHubId": 0,
            "teamsNotify": false,
            "teamsContent": "",
            "teamsContentCopy": "",
            "teamsConnectorId": 0,
            "teamsHubId": 0,
            "emailAttachment": false,
            "slackAttachment": false,
            "teamsAttachment": false,
            "whatsappNotify": false,
            "whatsappContent": "",
            "whatsappContentCopy": "",
            "whatsappConnectorId": 0,
            "whatsappAttachment": false
          },
          "markCCField": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "fields": []
          },
          "processStage": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "alertProcessStage": []
          },
          "userGroup": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "alertUser": [],
            "alertGroup": []
          }
        },
        "slaSettings": {
          "slaType": "STANDARD",
          "slaMasterFormId": 0,
          "workflowFormSLAFieldId": "",
          "emailNotify": true,
          "smsNotify": false
        },
        "slaRules": [],
        "fileSettings": {
          "fileCheckList": [],
          "partial": false
        },
        "userReply": false,
        "toInitiator": false,
        "isQuickAction": true,
        "mlCompareMaster": false,
        "mlMasterFormId": 0,
        "mlCompareFields": [],
        "mlPredictionField": "",
        "mlStatusField": "",
        "subWorkflowId": 0,
        "aiPrediction": {},
        "hasMasterEntriesAction": false,
        "masterFormEntries": [],
        "generateDocument": {
          "documentList": [],
          "allowSubmission": false
        },
        "mappingFieldsToForm": {
          "status": "",
          "completedAt": ""
        },
        "hasFooter": false,
        "footerText": ""
      }
    },
    {
      "id": "zcZU6Mm0RR0N90Wxo2aTv",
      "left": 553.0001054296257,
      "top": 72,
      "width": 175,
      "height": 90,
      "color": "#fd9644",
      "icon": "mdi-share-variant",
      "type": "CONDITION",
      "settings": {
        "label": "Check 1st Approver",
        "initiateMode": "MANUAL",
        "initiateBy": [
          "USER"
        ],
        "users": [],
        "groups": [],
        "userDomains": [],
        "dynamicUser": [],
        "externalUser": [],
        "externalUserMail": [],
        "forwardLabel": "",
        "forwardedUserAction": "DEFAULT",
        "partialApprove": true,
        "fullApprovalAction": "",
        "formEditAccess": "FULL",
        "formEditControls": [],
        "formVisibilityAccess": true,
        "formSecureControls": [],
        "documentRequired": false,
        "generatePDFFields": [],
        "hasFooter": false,
        "footerText": "",
        "generateCSV": false,
        "generateCSVFields": [],
        "reopen": false,
        "reopenBlockId": "",
        "standardCondition": true,
        "conditions": {
          "groupLogic": "ALL",
          "condition": [
            {
              "id": "b9MxFtyCj0mZP5-W3bQVP",
              "name": "N-0GtXrVEiP86zJgIHHtf",
              "logic": "IS_NOT_EQUALS_TO",
              "value": "",
              "fieldValue": false
            }
          ]
        },
        "masterConditions": {
          "masterFormId": 0,
          "condition": []
        },
        "notifications": {
          "acknowledgement": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "emailNotify": false,
            "smsNotify": false,
            "smsContent": "",
            "slackNotify": false,
            "slackContent": "",
            "slackContentCopy": "",
            "slackConnectorId": 0,
            "slackHubId": 0,
            "teamsNotify": false,
            "teamsContent": "",
            "teamsContentCopy": "",
            "teamsConnectorId": 0,
            "teamsHubId": 0,
            "emailAttachment": false,
            "slackAttachment": false,
            "teamsAttachment": false,
            "whatsappNotify": false,
            "whatsappContent": "",
            "whatsappContentCopy": "",
            "whatsappConnectorId": 0,
            "whatsappAttachment": false
          },
          "inboxNotification": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "actionButtons": false,
            "emailNotify": false,
            "smsNotify": false,
            "smsContent": "",
            "slackNotify": false,
            "slackContent": "",
            "slackContentCopy": "",
            "slackConnectorId": 0,
            "slackHubId": 0,
            "teamsNotify": false,
            "teamsContent": "",
            "teamsContentCopy": "",
            "teamsConnectorId": 0,
            "teamsHubId": 0,
            "emailAttachment": false,
            "slackAttachment": false,
            "teamsAttachment": false,
            "whatsappNotify": false,
            "whatsappContent": "",
            "whatsappContentCopy": "",
            "whatsappConnectorId": 0,
            "whatsappAttachment": false
          },
          "markCCField": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "fields": []
          },
          "processStage": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "alertProcessStage": []
          },
          "userGroup": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "alertUser": [],
            "alertGroup": []
          }
        },
        "slaSettings": {
          "slaType": "STANDARD",
          "slaMasterFormId": 0,
          "workflowFormSLAFieldId": "",
          "emailNotify": true,
          "smsNotify": false
        },
        "slaRules": [],
        "fileSettings": {
          "fileCheckList": [],
          "partial": false
        },
        "userReply": false,
        "toInitiator": false,
        "isQuickAction": true,
        "mlCompareMaster": false,
        "mlMasterFormId": 0,
        "mlCompareFields": [],
        "mlPredictionField": "",
        "mlStatusField": "",
        "subWorkflowId": 0,
        "aiPrediction": {},
        "hasMasterEntriesAction": false,
        "masterFormEntries": [],
        "generateDocument": {
          "documentList": [],
          "allowSubmission": false
        },
        "mappingFieldsToForm": {
          "status": "",
          "completedAt": ""
        }
      }
    },
    {
      "id": "i5dt5FQHUMCFW8pRkAdd9",
      "left": 673.0003198627627,
      "top": 179,
      "width": 175,
      "height": 90,
      "color": "#fd9644",
      "icon": "mdi-share-variant",
      "type": "CONDITION",
      "settings": {
        "label": "Check 1st Approver",
        "initiateMode": "MANUAL",
        "initiateBy": [
          "USER"
        ],
        "users": [],
        "groups": [],
        "userDomains": [],
        "dynamicUser": [],
        "externalUser": [],
        "externalUserMail": [],
        "forwardLabel": "",
        "forwardedUserAction": "DEFAULT",
        "partialApprove": true,
        "fullApprovalAction": "",
        "formEditAccess": "FULL",
        "formEditControls": [],
        "formVisibilityAccess": true,
        "formSecureControls": [],
        "documentRequired": false,
        "generatePDFFields": [],
        "hasFooter": false,
        "footerText": "",
        "generateCSV": false,
        "generateCSVFields": [],
        "reopen": false,
        "reopenBlockId": "",
        "standardCondition": true,
        "conditions": {
          "groupLogic": "ALL",
          "condition": [
            {
              "id": "ZIv30ozfReyABd7zzMoxr",
              "name": "N-0GtXrVEiP86zJgIHHtf",
              "logic": "IS_NOT_EQUALS_TO",
              "value": "",
              "fieldValue": false
            }
          ]
        },
        "masterConditions": {
          "masterFormId": 0,
          "condition": []
        },
        "notifications": {
          "acknowledgement": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "emailNotify": false,
            "smsNotify": false,
            "smsContent": "",
            "slackNotify": false,
            "slackContent": "",
            "slackContentCopy": "",
            "slackConnectorId": 0,
            "slackHubId": 0,
            "teamsNotify": false,
            "teamsContent": "",
            "teamsContentCopy": "",
            "teamsConnectorId": 0,
            "teamsHubId": 0,
            "emailAttachment": false,
            "slackAttachment": false,
            "teamsAttachment": false,
            "whatsappNotify": false,
            "whatsappContent": "",
            "whatsappContentCopy": "",
            "whatsappConnectorId": 0,
            "whatsappAttachment": false
          },
          "inboxNotification": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "actionButtons": false,
            "emailNotify": false,
            "smsNotify": false,
            "smsContent": "",
            "slackNotify": false,
            "slackContent": "",
            "slackContentCopy": "",
            "slackConnectorId": 0,
            "slackHubId": 0,
            "teamsNotify": false,
            "teamsContent": "",
            "teamsContentCopy": "",
            "teamsConnectorId": 0,
            "teamsHubId": 0,
            "emailAttachment": false,
            "slackAttachment": false,
            "teamsAttachment": false,
            "whatsappNotify": false,
            "whatsappContent": "",
            "whatsappContentCopy": "",
            "whatsappConnectorId": 0,
            "whatsappAttachment": false
          },
          "markCCField": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "fields": []
          },
          "processStage": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "alertProcessStage": []
          },
          "userGroup": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "alertUser": [],
            "alertGroup": []
          }
        },
        "slaSettings": {
          "slaType": "STANDARD",
          "slaMasterFormId": 0,
          "workflowFormSLAFieldId": "",
          "emailNotify": true,
          "smsNotify": false
        },
        "slaRules": [],
        "fileSettings": {
          "fileCheckList": [],
          "partial": false
        },
        "userReply": false,
        "toInitiator": false,
        "isQuickAction": true,
        "mlCompareMaster": false,
        "mlMasterFormId": 0,
        "mlCompareFields": [],
        "mlPredictionField": "",
        "mlStatusField": "",
        "subWorkflowId": 0,
        "aiPrediction": {},
        "hasMasterEntriesAction": false,
        "masterFormEntries": [],
        "generateDocument": {
          "documentList": [],
          "allowSubmission": false
        },
        "mappingFieldsToForm": {
          "status": "",
          "completedAt": ""
        }
      }
    },
    {
      "id": "UyFStu1NRNjgXE4UUB31P",
      "left": 841.0002269417367,
      "top": 291.0008991084853,
      "width": 175,
      "height": 90,
      "color": "#fd9644",
      "icon": "mdi-share-variant",
      "type": "CONDITION",
      "settings": {
        "label": "Check 1st Approver",
        "initiateMode": "MANUAL",
        "initiateBy": [
          "USER"
        ],
        "users": [],
        "groups": [],
        "userDomains": [],
        "dynamicUser": [],
        "externalUser": [],
        "externalUserMail": [],
        "forwardLabel": "",
        "forwardedUserAction": "DEFAULT",
        "partialApprove": true,
        "fullApprovalAction": "",
        "formEditAccess": "FULL",
        "formEditControls": [],
        "formVisibilityAccess": true,
        "formSecureControls": [],
        "documentRequired": false,
        "generatePDFFields": [],
        "hasFooter": false,
        "footerText": "",
        "generateCSV": false,
        "generateCSVFields": [],
        "reopen": false,
        "reopenBlockId": "",
        "standardCondition": true,
        "conditions": {
          "groupLogic": "ALL",
          "condition": [
            {
              "id": "8RK-FKkyVvdNP1BoKmbpb",
              "name": "N-0GtXrVEiP86zJgIHHtf",
              "logic": "IS_NOT_EQUALS_TO",
              "value": "",
              "fieldValue": false
            }
          ]
        },
        "masterConditions": {
          "masterFormId": 0,
          "condition": []
        },
        "notifications": {
          "acknowledgement": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "emailNotify": false,
            "smsNotify": false,
            "smsContent": "",
            "slackNotify": false,
            "slackContent": "",
            "slackContentCopy": "",
            "slackConnectorId": 0,
            "slackHubId": 0,
            "teamsNotify": false,
            "teamsContent": "",
            "teamsContentCopy": "",
            "teamsConnectorId": 0,
            "teamsHubId": 0,
            "emailAttachment": false,
            "slackAttachment": false,
            "teamsAttachment": false,
            "whatsappNotify": false,
            "whatsappContent": "",
            "whatsappContentCopy": "",
            "whatsappConnectorId": 0,
            "whatsappAttachment": false
          },
          "inboxNotification": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "actionButtons": false,
            "emailNotify": false,
            "smsNotify": false,
            "smsContent": "",
            "slackNotify": false,
            "slackContent": "",
            "slackContentCopy": "",
            "slackConnectorId": 0,
            "slackHubId": 0,
            "teamsNotify": false,
            "teamsContent": "",
            "teamsContentCopy": "",
            "teamsConnectorId": 0,
            "teamsHubId": 0,
            "emailAttachment": false,
            "slackAttachment": false,
            "teamsAttachment": false,
            "whatsappNotify": false,
            "whatsappContent": "",
            "whatsappContentCopy": "",
            "whatsappConnectorId": 0,
            "whatsappAttachment": false
          },
          "markCCField": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "fields": []
          },
          "processStage": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "alertProcessStage": []
          },
          "userGroup": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "alertUser": [],
            "alertGroup": []
          }
        },
        "slaSettings": {
          "slaType": "STANDARD",
          "slaMasterFormId": 0,
          "workflowFormSLAFieldId": "",
          "emailNotify": true,
          "smsNotify": false
        },
        "slaRules": [],
        "fileSettings": {
          "fileCheckList": [],
          "partial": false
        },
        "userReply": false,
        "toInitiator": false,
        "isQuickAction": true,
        "mlCompareMaster": false,
        "mlMasterFormId": 0,
        "mlCompareFields": [],
        "mlPredictionField": "",
        "mlStatusField": "",
        "subWorkflowId": 0,
        "aiPrediction": {},
        "hasMasterEntriesAction": false,
        "masterFormEntries": [],
        "generateDocument": {
          "documentList": [],
          "allowSubmission": false
        },
        "mappingFieldsToForm": {
          "status": "",
          "completedAt": ""
        }
      }
    },
    {
      "id": "FzKCP3AZN54NcgJt6XuU-",
      "left": 1169.000103642683,
      "top": 119.50034931579665,
      "width": 175,
      "height": 90,
      "color": "#A65EEA",
      "icon": "mdi-account-multiple",
      "type": "INTERNAL_ACTOR",
      "settings": {
        "label": "Approver",
        "initiateMode": "MANUAL",
        "initiateBy": [
          "USER"
        ],
        "users": [
          "4"
        ],
        "groups": [],
        "userDomains": [],
        "dynamicUser": [],
        "externalUser": [],
        "externalUserMail": [],
        "forwardLabel": "",
        "forwardedUserAction": "DEFAULT",
        "partialApprove": true,
        "fullApprovalAction": "",
        "formEditAccess": "FULL",
        "formEditControls": [],
        "formVisibilityAccess": true,
        "formSecureControls": [],
        "documentRequired": false,
        "generatePDFFields": [],
        "hasFooter": false,
        "footerText": "",
        "generateCSV": false,
        "generateCSVFields": [],
        "reopen": false,
        "reopenBlockId": "",
        "conditions": {
          "groupLogic": "ALL",
          "condition": []
        },
        "masterConditions": {
          "masterFormId": 0,
          "condition": []
        },
        "notifications": {
          "acknowledgement": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "emailNotify": false,
            "smsNotify": false,
            "smsContent": "",
            "slackNotify": false,
            "slackContent": "",
            "slackContentCopy": "",
            "slackConnectorId": 0,
            "slackHubId": 0,
            "teamsNotify": false,
            "teamsContent": "",
            "teamsContentCopy": "",
            "teamsConnectorId": 0,
            "teamsHubId": 0,
            "emailAttachment": false,
            "slackAttachment": false,
            "teamsAttachment": false,
            "whatsappNotify": false,
            "whatsappContent": "",
            "whatsappContentCopy": "",
            "whatsappConnectorId": 0,
            "whatsappAttachment": false
          },
          "inboxNotification": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "actionButtons": false,
            "emailNotify": false,
            "smsNotify": false,
            "smsContent": "",
            "slackNotify": false,
            "slackContent": "",
            "slackContentCopy": "",
            "slackConnectorId": 0,
            "slackHubId": 0,
            "teamsNotify": false,
            "teamsContent": "",
            "teamsContentCopy": "",
            "teamsConnectorId": 0,
            "teamsHubId": 0,
            "emailAttachment": false,
            "slackAttachment": false,
            "teamsAttachment": false,
            "whatsappNotify": false,
            "whatsappContent": "",
            "whatsappContentCopy": "",
            "whatsappConnectorId": 0,
            "whatsappAttachment": false
          },
          "markCCField": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "fields": []
          },
          "processStage": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "alertProcessStage": []
          },
          "userGroup": {
            "notify": false,
            "subject": "",
            "subjectContent": "",
            "body": "",
            "bodyContent": "",
            "attachment": false,
            "alertUser": [],
            "alertGroup": []
          }
        },
        "slaSettings": {
          "slaType": "STANDARD",
          "slaMasterFormId": 0,
          "workflowFormSLAFieldId": "",
          "emailNotify": true,
          "smsNotify": false
        },
        "slaRules": [],
        "fileSettings": {
          "fileCheckList": [],
          "partial": false
        },
        "userReply": false,
        "toInitiator": false,
        "isQuickAction": true,
        "mlCompareMaster": false,
        "mlMasterFormId": 0,
        "mlCompareFields": [],
        "mlPredictionField": "",
        "mlStatusField": "",
        "subWorkflowId": 0,
        "aiPrediction": {},
        "hasMasterEntriesAction": false,
        "masterFormEntries": [],
        "generateDocument": {
          "documentList": [],
          "allowSubmission": false
        },
        "mappingFieldsToForm": {
          "status": "",
          "completedAt": ""
        }
      }
    }
  ],
  "rules": [
    {
      "id": "p4nAjf6YU5o8hFveOyqs0",
      "left": 228.5,
      "top": 98.5,
      "fromBlockId": "G59WQkftZGs7D9JAsua_5",
      "toBlockId": "AN_VThGrTcn0tDQOUmZ0F",
      "remarks": false,
      "passwordAccess": false,
      "confirm": false,
      "signature": false,
      "proceedAction": "Submit"
    },
    {
      "id": "-6v7uCNRw6Y9TBdLzSbpY",
      "left": 448.5,
      "top": 138.5,
      "fromBlockId": "AN_VThGrTcn0tDQOUmZ0F",
      "toBlockId": "NhB-AEDaz0WDuB3zOm1kg",
      "proceedAction": "SUCCESS",
      "remarks": false,
      "passwordAccess": false,
      "confirm": false,
      "signature": false
    },
    {
      "id": "ZLry7ea8Fd44yAPQtKXLy",
      "left": 668.5,
      "top": 178.5,
      "fromBlockId": "NhB-AEDaz0WDuB3zOm1kg",
      "toBlockId": "zcZU6Mm0RR0N90Wxo2aTv",
      "proceedAction": "APPROVED",
      "remarks": false,
      "passwordAccess": false,
      "confirm": false,
      "signature": false,
      "addCondition": false,
      "settings": {}
    },
    {
      "id": "mOCpc9Vcjz1glaEaWE2UR",
      "left": 668.5,
      "top": 178.5,
      "fromBlockId": "NhB-AEDaz0WDuB3zOm1kg",
      "toBlockId": "i5dt5FQHUMCFW8pRkAdd9",
      "proceedAction": "REJECTED",
      "remarks": false,
      "passwordAccess": false,
      "confirm": false,
      "signature": false,
      "addCondition": false,
      "settings": {}
    },
    {
      "id": "stGp02rB_bNqeJOaL94sJ",
      "left": 668.5,
      "top": 178.5,
      "fromBlockId": "NhB-AEDaz0WDuB3zOm1kg",
      "toBlockId": "UyFStu1NRNjgXE4UUB31P",
      "proceedAction": "PARTIALLY APPROVED",
      "remarks": false,
      "passwordAccess": false,
      "confirm": false,
      "signature": false,
      "addCondition": false,
      "settings": {}
    },
    {
      "id": "df-ev3HdjhlOc7eoump3K",
      "left": 1205.5005664608707,
      "top": 295.0005042297587,
      "fromBlockId": "srf66hYmrFs6F1tStUmul",
      "toBlockId": "FzKCP3AZN54NcgJt6XuU-",
      "proceedAction": "Approve",
      "remarks": false,
      "passwordAccess": false,
      "confirm": false,
      "signature": false,
      "addCondition": false,
      "settings": {}
    },
    {
      "id": "YzT_sQR8jz89Kr3Oni-Qa",
      "left": 1326.000545017557,
      "top": 340.0005042297587,
      "fromBlockId": "FzKCP3AZN54NcgJt6XuU-",
      "toBlockId": "gRBdu25IaIgwy2LCK5yS0",
      "remarks": false,
      "passwordAccess": false,
      "confirm": false,
      "signature": false,
      "addCondition": false,
      "settings": {}
    },
    {
      "id": "8M1B3XZr--TFcDvhA8Y5D",
      "left": 930.500468179016,
      "top": 231.50040399131262,
      "fromBlockId": "zcZU6Mm0RR0N90Wxo2aTv",
      "toBlockId": "srf66hYmrFs6F1tStUmul",
      "proceedAction": "Satisfied",
      "remarks": false,
      "passwordAccess": false,
      "confirm": false,
      "signature": false,
      "addCondition": false,
      "settings": {}
    },
    {
      "id": "FU67FEng_c0FtHEI_a8zw",
      "left": 930.500468179016,
      "top": 293.0005042297587,
      "fromBlockId": "i5dt5FQHUMCFW8pRkAdd9",
      "toBlockId": "srf66hYmrFs6F1tStUmul",
      "proceedAction": "Satisfied",
      "remarks": false,
      "passwordAccess": false,
      "confirm": false,
      "signature": false,
      "addCondition": false,
      "settings": {}
    },
    {
      "id": "WcJ4-PtNxhw6zt-RKj3vu",
      "left": 848.0000839863119,
      "top": 340.0005042297587,
      "fromBlockId": "UyFStu1NRNjgXE4UUB31P",
      "toBlockId": "srf66hYmrFs6F1tStUmul",
      "proceedAction": "Satisfied",
      "remarks": false,
      "passwordAccess": false,
      "confirm": false,
      "signature": false,
      "addCondition": false,
      "settings": {}
    },
    {
      "id": "uuoclQiYLty-CkzKajAQ0",
      "left": 843.0004681790158,
      "top": 276.50040399131274,
      "fromBlockId": "zcZU6Mm0RR0N90Wxo2aTv",
      "toBlockId": "FzKCP3AZN54NcgJt6XuU-",
      "proceedAction": "Not Satisfied",
      "remarks": false,
      "passwordAccess": false,
      "confirm": false,
      "signature": false,
      "addCondition": false,
      "settings": {}
    },
    {
      "id": "YDF5JdumVcg3iMFiRUJyo",
      "left": 930.5004681790158,
      "top": 384.5005042297587,
      "fromBlockId": "i5dt5FQHUMCFW8pRkAdd9",
      "toBlockId": "FzKCP3AZN54NcgJt6XuU-",
      "proceedAction": "Not Satisfied",
      "remarks": false,
      "passwordAccess": false,
      "confirm": false,
      "signature": false,
      "addCondition": false,
      "settings": {}
    },
    {
      "id": "DO3l31RQw0wKjJkojj3Nh",
      "left": 935.5000839863121,
      "top": 447.0009720091733,
      "fromBlockId": "UyFStu1NRNjgXE4UUB31P",
      "toBlockId": "FzKCP3AZN54NcgJt6XuU-",
      "proceedAction": "Not Satisfied",
      "remarks": false,
      "passwordAccess": false,
      "confirm": false,
      "signature": false,
      "addCondition": false,
      "settings": {}
    }
  ],
  "settings": {
    "general": {
      "name": "BT_AP Agent",
      "description": "",
      "initiateUsing": {
        "type": "FORM",
        "repositoryId": 21,
        "formId": 10
      },
      "ocr": {
        "credit": 0,
        "required": false
      },
      "processNumberPrefix": "[{\"id\":\"vi7qXYJty32zExfD6KrDh\",\"key\":\"seperator\",\"value\":\"-\"},{\"id\":\"la4Bs9-AHNUW1Fw__P6nC\",\"key\":\"reset\",\"value\":\"year\"},{\"id\":\"JNp3YEcN5F78LhbWNm9-k\",\"key\":\"prefix\",\"value\":\"REQ\"},{\"id\":\"Zcu4BMMBSy5xEfDLaJI8O\",\"key\":\"autoIncrement\",\"value\":1}]",
      "linkMasterFormId": 0,
      "smtpEmailId": 0,
      "coordinator": [],
      "superuser": [],
      "fileSize": 20,
      "slaSettings": {
        "workDays": [],
        "workHours": {
          "from": "",
          "to": ""
        },
        "timeZone": "",
        "slaType": "STANDARD",
        "slaMasterFormId": 0,
        "workflowFormSLAFieldId": "",
        "emailNotify": true,
        "smsNotify": false
      },
      "slaRules": [],
      "kanbanSettings": [],
      "scheduleReport": {},
      "verifiedDocument": []
    },
    "publish": {
      "publishOption": "PUBLISHED",
      "publishSchedule": "",
      "unpublishSchedule": ""
    }
  },
  "modifiedBlockIds": [],
  "blockStatus": 0,
  "mlPredictions": [],
  "hasSLASettings": 1,
  "initiateUserDomain": [],
  "masterFormIds": []
};
