import type { NotificationItem } from './types'

const minutesAgo = (minutes: number) =>
  new Date(Date.now() - minutes * 60_000).toISOString()

const actor = (name: string, email: string) => ({ email, name })

export function buildMockNotifications(): NotificationItem[] {
  return [
    // Requests / Workflow instances
    {
      actor: actor('You', 'me@company.com'),
      category: 'request.submitted',
      createdAtUtc: minutesAgo(180),
      data: {
        processId: 'proc-10245',
        requestNo: 'REQ-10245',
        transactionId: 'proc-10245',
        workflowId: 'wf-101',
      },
      id: 'req-submitted-1',
      isRead: true,
      message: 'Your request has been submitted to Manager Approval.',
      severity: 'info',
      target: {
        route: 'requests',
        search: {
          processId: 'proc-10245',
          transactionId: 'proc-10245',
          workflowId: 'wf-101',
        },
      },
      title: 'Request REQ-10245 submitted',
    },
    {
      actor: actor('Workflow Engine', 'system@company.com'),
      category: 'request.assigned',
      createdAtUtc: minutesAgo(25),
      data: {
        processId: 'proc-10248',
        requestNo: 'REQ-10248',
        stageName: 'Manager Approval',
        tab: 'Details',
        transactionId: 'proc-10248',
        workflowId: 'wf-101',
      },
      id: 'req-assigned-1',
      isRead: false,
      message: "You've been assigned to Manager Approval for REQ-10248.",
      severity: 'workflow',
      target: {
        route: 'requests',
        search: {
          processId: 'proc-10248',
          tab: 'Details',
          transactionId: 'proc-10248',
          workflowId: 'wf-101',
        },
      },
      title: 'Action required: REQ-10248',
    },
    {
      actor: actor('Jane Cooper', 'jane.cooper@company.com'),
      category: 'request.approved',
      createdAtUtc: minutesAgo(60),
      data: {
        processId: 'proc-10230',
        requestNo: 'REQ-10230',
        transactionId: 'proc-10230',
        workflowId: 'wf-101',
      },
      id: 'req-approved-1',
      isRead: false,
      message: 'Jane Cooper approved Manager Approval.',
      severity: 'success',
      target: {
        route: 'requests',
        search: {
          processId: 'proc-10230',
          transactionId: 'proc-10230',
          workflowId: 'wf-101',
        },
      },
      title: 'Request REQ-10230 approved',
    },
    {
      actor: actor('Alex Morgan', 'alex.morgan@company.com'),
      category: 'request.rejected',
      createdAtUtc: minutesAgo(240),
      data: {
        processId: 'proc-10221',
        requestNo: 'REQ-10221',
        transactionId: 'proc-10221',
        workflowId: 'wf-101',
      },
      id: 'req-rejected-1',
      isRead: true,
      message: 'Alex Morgan rejected Finance Review.',
      severity: 'error',
      target: {
        route: 'requests',
        search: {
          processId: 'proc-10221',
          transactionId: 'proc-10221',
          workflowId: 'wf-101',
        },
      },
      title: 'Request REQ-10221 rejected',
    },
    {
      actor: actor('Priya Singh', 'priya.singh@company.com'),
      category: 'request.commented',
      createdAtUtc: minutesAgo(12),
      data: {
        processId: 'proc-10245',
        requestNo: 'REQ-10245',
        tab: 'Comments',
        transactionId: 'proc-10245',
        workflowId: 'wf-101',
      },
      id: 'req-commented-1',
      isRead: false,
      message: 'Priya Singh commented: "Can you confirm the PO number?"',
      severity: 'info',
      target: {
        route: 'requests',
        search: {
          processId: 'proc-10245',
          tab: 'Comments',
          transactionId: 'proc-10245',
          workflowId: 'wf-101',
        },
      },
      title: 'New comment on REQ-10245',
    },
    {
      actor: actor('Alex Morgan', 'alex.morgan@company.com'),
      category: 'request.reopened',
      createdAtUtc: minutesAgo(400),
      data: {
        processId: 'proc-10199',
        requestNo: 'REQ-10199',
        transactionId: 'proc-10199',
        workflowId: 'wf-101',
      },
      id: 'req-reopened-1',
      isRead: true,
      message: 'Alex Morgan reopened this request for further action.',
      severity: 'warning',
      target: {
        route: 'requests',
        search: {
          processId: 'proc-10199',
          transactionId: 'proc-10199',
          workflowId: 'wf-101',
        },
      },
      title: 'Request REQ-10199 reopened',
    },
    {
      category: 'request.completed',
      createdAtUtc: minutesAgo(1440),
      data: {
        processId: 'proc-10180',
        requestNo: 'REQ-10180',
        tab: 'History',
        transactionId: 'proc-10180',
        workflowId: 'wf-101',
      },
      id: 'req-completed-1',
      isRead: true,
      message: 'Workflow finished — no further action needed.',
      severity: 'success',
      target: {
        route: 'requests',
        search: {
          processId: 'proc-10180',
          tab: 'History',
          transactionId: 'proc-10180',
          workflowId: 'wf-101',
        },
      },
      title: 'Request REQ-10180 completed',
    },

    // AI/OCR processing
    {
      category: 'ocr.processing_completed',
      createdAtUtc: minutesAgo(5),
      data: {
        fileName: 'INV-8841.pdf',
        jobId: 'job-8841',
        processId: 'proc-88410',
        transactionId: 'proc-88410',
        workflowId: 'wf-101',
      },
      id: 'ocr-completed-1',
      isRead: false,
      message: 'Invoice data extracted and matched. Ready for review.',
      severity: 'success',
      target: {
        route: 'requests',
        search: {
          processId: 'proc-88410',
          transactionId: 'proc-88410',
          workflowId: 'wf-101',
        },
      },
      title: 'INV-8841.pdf processed',
    },
    {
      category: 'ocr.discrepancy_found',
      createdAtUtc: minutesAgo(18),
      // Multi-transaction instance: this discrepancy belongs to the 2nd
      // transaction (a re-submitted line item) within instance proc-90120,
      // so transactionId is distinct from processId — not defaulted.
      data: {
        discrepancyCount: 2,
        fileName: 'PO_9012.pdf',
        jobId: 'job-9012',
        processId: 'proc-90120',
        tab: 'Details',
        transactionId: 'proc-90120-tx2',
        workflowId: 'wf-101',
      },
      id: 'ocr-discrepancy-1',
      isRead: false,
      message: 'Field mismatches vs. PO/GL need your review before approval.',
      severity: 'warning',
      target: {
        route: 'requests',
        search: {
          processId: 'proc-90120',
          tab: 'Details',
          transactionId: 'proc-90120-tx2',
          workflowId: 'wf-101',
        },
      },
      title: '2 discrepancies found in PO_9012.pdf',
    },
    {
      category: 'ocr.processing_failed',
      createdAtUtc: minutesAgo(1500),
      data: {
        fileName: 'PO_8841.pdf',
        jobId: 'job-8841b',
        processId: 'proc-88411',
        transactionId: 'proc-88411',
        workflowId: 'wf-101',
      },
      id: 'ocr-failed-1',
      isRead: true,
      message: "We couldn't extract data from this file. Try re-uploading.",
      severity: 'error',
      target: {
        route: 'requests',
        search: {
          processId: 'proc-88411',
          transactionId: 'proc-88411',
          workflowId: 'wf-101',
        },
      },
      title: 'Failed to process PO_8841.pdf',
    },

    // Sign Requests
    {
      actor: actor('Legal Team', 'legal@company.com'),
      category: 'signrequest.awaiting_signature',
      createdAtUtc: minutesAgo(30),
      data: {
        documentName: 'MSA_2026.pdf',
        inviteToken: 'inv-8f21c9',
        signRequestId: 'sr-1',
      },
      id: 'sign-awaiting-1',
      isRead: false,
      message: 'Legal Team sent you a document to sign.',
      severity: 'workflow',
      target: {
        params: { _splat: 'inv-8f21c9' },
        route: 'sign-request',
        search: { email: 'me@company.com' },
      },
      title: 'Signature requested: MSA_2026.pdf',
    },
    {
      actor: actor('Vendor X', 'contact@vendorx.com'),
      category: 'signrequest.signed',
      createdAtUtc: minutesAgo(90),
      data: {
        documentName: 'NDA_VendorX.pdf',
        inviteToken: 'inv-2b77aa',
        signRequestId: 'sr-2',
      },
      id: 'sign-signed-1',
      isRead: true,
      message: 'Vendor X completed signing.',
      severity: 'success',
      target: { params: { _splat: 'inv-2b77aa' }, route: 'sign-request' },
      title: 'NDA_VendorX.pdf signed',
    },
    {
      actor: actor('Alex Morgan', 'alex.morgan@company.com'),
      category: 'signrequest.cancelled',
      createdAtUtc: minutesAgo(600),
      data: {
        documentName: 'SOW_Q1.pdf',
        inviteToken: 'inv-9c44de',
        signRequestId: 'sr-3',
      },
      id: 'sign-cancelled-1',
      isRead: true,
      message: 'Alex Morgan cancelled the signing request for SOW_Q1.pdf.',
      severity: 'error',
      target: { route: 'folders' },
      title: 'Sign request cancelled',
    },
    {
      category: 'signrequest.expiring_soon',
      createdAtUtc: minutesAgo(45),
      data: {
        documentName: 'Renewal_2026.pdf',
        expiresAtUtc: minutesAgo(-1200),
        inviteToken: 'inv-5514fe',
        signRequestId: 'sr-4',
      },
      id: 'sign-expiring-1',
      isRead: false,
      message: 'This request expires in 20h. Sign it now.',
      severity: 'warning',
      target: { params: { _splat: 'inv-5514fe' }, route: 'sign-request' },
      title: 'Signature expiring soon: Renewal_2026.pdf',
    },

    // Forms / Form Entries
    {
      actor: actor('Sam Wilson', 'sam.wilson@company.com'),
      category: 'form.entry_submitted',
      createdAtUtc: minutesAgo(15),
      data: {
        entryId: 'entry-9981',
        formId: 'form-501',
        formName: 'Vendor Onboarding',
      },
      id: 'form-entry-1',
      isRead: false,
      message: 'Sam Wilson submitted a response.',
      severity: 'info',
      target: {
        params: { formId: 'form-501' },
        route: 'form-entries',
        search: { entryId: 'entry-9981' },
      },
      title: 'New entry on Vendor Onboarding',
    },
    {
      category: 'form.published',
      createdAtUtc: minutesAgo(720),
      data: { formId: 'form-502', formName: 'Expense Claim' },
      id: 'form-published-1',
      isRead: true,
      message: 'Your form is now live and accepting entries.',
      severity: 'success',
      target: { params: { formId: 'form-502' }, route: 'form-builder' },
      title: 'Expense Claim published',
    },

    // Folders / Documents
    {
      category: 'folder.item_uploaded',
      createdAtUtc: minutesAgo(3),
      data: {
        folderId: 'folder-finance',
        itemId: 'item-5510',
        itemName: 'MasterData_Q1.xlsx',
        repositoryId: 'repo-1',
      },
      id: 'folder-uploaded-1',
      isRead: false,
      message: 'Your file was added to Finance / Master Data.',
      severity: 'success',
      target: {
        route: 'folders',
        search: {
          folderId: 'folder-finance',
          itemId: 'item-5510',
          repositoryId: 'repo-1',
        },
      },
      title: 'MasterData_Q1.xlsx uploaded',
    },
    {
      actor: actor('Priya Singh', 'priya.singh@company.com'),
      category: 'folder.item_shared',
      createdAtUtc: minutesAgo(50),
      data: {
        folderId: 'folder-legal',
        itemId: 'item-6602',
        itemName: 'Contract_Renewal.pdf',
        repositoryId: 'repo-1',
      },
      id: 'folder-shared-1',
      isRead: false,
      message: 'You now have access to this document.',
      severity: 'info',
      target: {
        route: 'folders',
        search: {
          folderId: 'folder-legal',
          itemId: 'item-6602',
          repositoryId: 'repo-1',
        },
      },
      title: 'Priya Singh shared Contract_Renewal.pdf with you',
    },
    {
      actor: actor('Alex Morgan', 'alex.morgan@company.com'),
      category: 'folder.share_revoked',
      createdAtUtc: minutesAgo(1000),
      data: { itemName: 'Budget_2025.xlsx', repositoryId: 'repo-1' },
      id: 'folder-revoked-1',
      isRead: true,
      message: 'Alex Morgan removed your access to this document.',
      severity: 'warning',
      target: { route: 'folders' },
      title: 'Access revoked: Budget_2025.xlsx',
    },
    {
      actor: actor('Jane Cooper', 'jane.cooper@company.com'),
      category: 'folder.commented',
      createdAtUtc: minutesAgo(80),
      data: {
        folderId: 'folder-hr',
        itemId: 'item-7710',
        itemName: 'Onboarding_Checklist.docx',
        repositoryId: 'repo-1',
      },
      id: 'folder-commented-1',
      isRead: true,
      message: 'Jane Cooper commented on your document.',
      severity: 'info',
      target: {
        route: 'folders',
        search: {
          folderId: 'folder-hr',
          itemId: 'item-7710',
          repositoryId: 'repo-1',
        },
      },
      title: 'New comment on Onboarding_Checklist.docx',
    },
    {
      actor: actor('Alex Morgan', 'alex.morgan@company.com'),
      category: 'folder.security_changed',
      createdAtUtc: minutesAgo(2000),
      data: {
        folderId: 'folder-finance',
        itemName: 'Finance / Master Data',
        repositoryId: 'repo-1',
      },
      id: 'folder-security-1',
      isRead: true,
      message: 'Alex Morgan updated permissions.',
      severity: 'warning',
      target: {
        route: 'folders',
        search: { folderId: 'folder-finance', repositoryId: 'repo-1' },
      },
      title: 'Security settings changed on Finance / Master Data',
    },

    // Support Tickets
    {
      category: 'ticket.created',
      createdAtUtc: minutesAgo(200),
      data: { jiraSynced: true, ticketId: '4821' },
      id: 'ticket-created-1',
      isRead: true,
      message: 'Your support ticket was created and synced to Jira.',
      severity: 'success',
      target: { route: 'support-tickets', search: { tab: 'support-tickets' } },
      title: 'Ticket #4821 created',
    },
    {
      category: 'ticket.sync_failed',
      createdAtUtc: minutesAgo(20),
      data: { jiraSynced: false, ticketId: '4822' },
      id: 'ticket-sync-failed-1',
      isRead: false,
      message: "Ticket saved, but Jira sync failed. We'll retry automatically.",
      severity: 'warning',
      target: { route: 'support-tickets', search: { tab: 'support-tickets' } },
      title: 'Ticket #4822 created (sync pending)',
    },

    // Settings / Admin
    {
      actor: actor('Alex Morgan', 'alex.morgan@company.com'),
      category: 'admin.user_added',
      createdAtUtc: minutesAgo(3000),
      data: { targetUserId: 'user-77', targetUserName: 'Sam Wilson' },
      id: 'admin-user-added-1',
      isRead: true,
      message: 'Alex Morgan invited a new user.',
      severity: 'info',
      target: { route: 'settings' },
      title: 'Sam Wilson added to your team',
    },
    {
      actor: actor('Alex Morgan', 'alex.morgan@company.com'),
      category: 'admin.role_changed',
      createdAtUtc: minutesAgo(4200),
      data: { targetUserId: 'me' },
      id: 'admin-role-changed-1',
      isRead: true,
      message: 'Alex Morgan changed your role. Some access may have changed.',
      severity: 'warning',
      target: { route: 'settings' },
      title: 'Your permissions were updated',
    },
  ]
}

export const mockNotifications: NotificationItem[] = buildMockNotifications()
