import {
    Archive,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    Bot,
    Building2,
    Calendar,
    CheckCircle2,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    Clock,
    Copy,
    Download,
    Edit3,
    Eye,
    FileText,
    Folder,
    FolderPlus,
    Grid2X2,
    Inbox,
    List,
    Mail,
    MoreHorizontal,
    Printer,
    RefreshCcw,
    Search,
    Send,
    Share2,
    Shield,
    Sparkles,
    Tag,
    Trash2,
    Upload,
    Users,
    XCircle,
    Zap,
    Filter,
    Save,
    Loader2,
    PlayCircle,
} from 'lucide-react'

export const iconMap = {
    archive: Archive,

    arrowLeft: ArrowLeft,
    arrowRight: ArrowRight,
    arrowUp: ArrowUp,
    arrowDown: ArrowDown,

    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    chevronUp: ChevronUp,
    chevronDown: ChevronDown,
    play: PlayCircle,
    bot: Bot,
    building: Building2,
    calendar: Calendar,
    check: CheckCircle2,
    checkCircle: CheckCircle2,
    clock: Clock,
    copy: Copy,
    download: Download,
    edit: Edit3,
    eye: Eye,
    fileText: FileText,
    fileStack: FileText,
    filter: Filter,
    folder: Folder,
    folderPlus: FolderPlus,
    grid: Grid2X2,
    inbox: Inbox,
    list: List,
    mail: Mail,
    more: MoreHorizontal,
    printer: Printer,
    refresh: RefreshCcw,
    search: Search,
    save: Save,
    send: Send,
    share: Share2,
    shield: Shield,
    sparkles: Sparkles,
    tag: Tag,
    trash: Trash2,
    upload: Upload,
    users: Users,
    x: XCircle,
    xCircle: XCircle,
    zap: Zap,
    loader: Loader2,
    spinner: Loader2,
}

export function DynamicIcon({
    name,
    className,
}: {
    name?: string
    className?: string
}) {
    const Icon = (iconMap as any)[name || 'fileText'] || FileText
    return <Icon className={className || 'h-4 w-4'} />
}