import {
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Banknote,
  Bot,
  Building2,
  Calendar,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Copy,
  CreditCard,
  Download,
  Edit3,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Folder,
  FolderPlus,
  Grid2X2,
  Inbox,
  List,
  Loader2,
  Mail,
  MapPin,
  MessageSquare,
  MoreHorizontal,
  Paperclip,
  PlayCircle,
  Printer,
  Receipt,
  RefreshCcw,
  Save,
  Search,
  Send,
  Share2,
  Shield,
  Sparkles,
  Tag,
  Trash2,
  Upload,
  Users,
  XCircle,
  Zap,
} from 'lucide-react'

export const iconMap = {
  address: MapPin,

  amount: Banknote,
  archive: Archive,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,

  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  bot: Bot,
  building: Building2,
  calendar: Calendar,
  card: CreditCard,
  check: CheckCircle2,
  checkCircle: CheckCircle2,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  clock: Clock,
  copy: Copy,
  currency: Banknote,
  date: Calendar,
  document: FileText,
  download: Download,
  edit: Edit3,
  eye: Eye,
  eyeOff: EyeOff,
  fileStack: FileText,
  fileText: FileText,
  filter: Filter,
  folder: Folder,
  folderPlus: FolderPlus,
  grid: Grid2X2,
  inbox: Inbox,
  list: List,
  loader: Loader2,
  mail: Mail,
  messageSquare: MessageSquare,
  more: MoreHorizontal,
  paperclip: Paperclip,
  play: PlayCircle,
  printer: Printer,
  refresh: RefreshCcw,
  save: Save,
  search: Search,
  send: Send,
  share: Share2,
  shield: Shield,
  sparkles: Sparkles,
  spinner: Loader2,
  tag: Tag,
  tax: Receipt,
  trash: Trash2,
  upload: Upload,
  users: Users,
  x: XCircle,
  xCircle: XCircle,
  zap: Zap,
}

export function DynamicIcon({
  className,
  name,
  onClick,
}: {
  className?: string
  name?: string
  onClick?: React.MouseEventHandler<SVGSVGElement>
}) {
  const Icon = (iconMap as any)[name || 'fileText'] || FileText
  return <Icon className={className || 'h-4 w-4'} onClick={onClick} />
}
