/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteRouteImport } from './routes/stories/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as RouteRouteImport } from './routes/route'
import { Route as StoriesIndexRouteImport } from './routes/stories/index'
import { Route as OnBoardingIndexRouteImport } from './routes/on-boarding/index'
import { Route as StoriesTooltipRouteImport } from './routes/stories/tooltip'
import { Route as StoriesToastRouteImport } from './routes/stories/toast'
import { Route as StoriesTabsRouteImport } from './routes/stories/tabs'
import { Route as StoriesTableRouteImport } from './routes/stories/table'
import { Route as StoriesStepperRouteImport } from './routes/stories/stepper'
import { Route as StoriesScrollAreaRouteImport } from './routes/stories/scroll-area'
import { Route as StoriesPopoverRouteImport } from './routes/stories/popover'
import { Route as StoriesPaginationRouteImport } from './routes/stories/pagination'
import { Route as StoriesModalRouteImport } from './routes/stories/modal'
import { Route as StoriesMenuRouteImport } from './routes/stories/menu'
import { Route as StoriesInputTimeRouteImport } from './routes/stories/input-time'
import { Route as StoriesInputTextareaRouteImport } from './routes/stories/input-textarea'
import { Route as StoriesInputTextRouteImport } from './routes/stories/input-text'
import { Route as StoriesInputSwitchGroupRouteImport } from './routes/stories/input-switch-group'
import { Route as StoriesInputSwitchRouteImport } from './routes/stories/input-switch'
import { Route as StoriesInputSelectMultipleRouteImport } from './routes/stories/input-select-multiple'
import { Route as StoriesInputSelectRouteImport } from './routes/stories/input-select'
import { Route as StoriesInputRadioGroupRouteImport } from './routes/stories/input-radio-group'
import { Route as StoriesInputRadioCardRouteImport } from './routes/stories/input-radio-card'
import { Route as StoriesInputRadioRouteImport } from './routes/stories/input-radio'
import { Route as StoriesInputPinRouteImport } from './routes/stories/input-pin'
import { Route as StoriesInputPasswordRouteImport } from './routes/stories/input-password'
import { Route as StoriesInputNumberRouteImport } from './routes/stories/input-number'
import { Route as StoriesInputDateRouteImport } from './routes/stories/input-date'
import { Route as StoriesInputCheckboxGroupRouteImport } from './routes/stories/input-checkbox-group'
import { Route as StoriesInputCheckboxCardRouteImport } from './routes/stories/input-checkbox-card'
import { Route as StoriesInputCheckboxRouteImport } from './routes/stories/input-checkbox'
import { Route as StoriesIndicatorRouteImport } from './routes/stories/indicator'
import { Route as StoriesIconButtonRouteImport } from './routes/stories/icon-button'
import { Route as StoriesHighlightRouteImport } from './routes/stories/highlight'
import { Route as StoriesEmptyStateRouteImport } from './routes/stories/empty-state'
import { Route as StoriesDrawerRouteImport } from './routes/stories/drawer'
import { Route as StoriesDividerRouteImport } from './routes/stories/divider'
import { Route as StoriesDataTableRouteImport } from './routes/stories/data-table'
import { Route as StoriesButtonRouteImport } from './routes/stories/button'
import { Route as StoriesBadgeRouteImport } from './routes/stories/badge'
import { Route as StoriesAvatarRouteImport } from './routes/stories/avatar'
import { Route as StoriesAiIconRouteImport } from './routes/stories/ai-icon'
import { Route as OnBoardingTokenRouteImport } from './routes/on-boarding/$token'
import { Route as AuthSignUpIndexRouteImport } from './routes/_auth/sign-up/index'
import { Route as AuthSignInIndexRouteImport } from './routes/_auth/sign-in/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/_auth/reset-password/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/_auth/forgot-password/index'

const StoriesRouteRoute = StoriesRouteRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteRoute = RouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const OnBoardingIndexRoute = OnBoardingIndexRouteImport.update({
  id: '/on-boarding/',
  path: '/on-boarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesTooltipRoute = StoriesTooltipRouteImport.update({
  id: '/tooltip',
  path: '/tooltip',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesToastRoute = StoriesToastRouteImport.update({
  id: '/toast',
  path: '/toast',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesTabsRoute = StoriesTabsRouteImport.update({
  id: '/tabs',
  path: '/tabs',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesTableRoute = StoriesTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesStepperRoute = StoriesStepperRouteImport.update({
  id: '/stepper',
  path: '/stepper',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesScrollAreaRoute = StoriesScrollAreaRouteImport.update({
  id: '/scroll-area',
  path: '/scroll-area',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesPopoverRoute = StoriesPopoverRouteImport.update({
  id: '/popover',
  path: '/popover',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesPaginationRoute = StoriesPaginationRouteImport.update({
  id: '/pagination',
  path: '/pagination',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesModalRoute = StoriesModalRouteImport.update({
  id: '/modal',
  path: '/modal',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesMenuRoute = StoriesMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesInputTimeRoute = StoriesInputTimeRouteImport.update({
  id: '/input-time',
  path: '/input-time',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesInputTextareaRoute = StoriesInputTextareaRouteImport.update({
  id: '/input-textarea',
  path: '/input-textarea',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesInputTextRoute = StoriesInputTextRouteImport.update({
  id: '/input-text',
  path: '/input-text',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesInputSwitchGroupRoute = StoriesInputSwitchGroupRouteImport.update({
  id: '/input-switch-group',
  path: '/input-switch-group',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesInputSwitchRoute = StoriesInputSwitchRouteImport.update({
  id: '/input-switch',
  path: '/input-switch',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesInputSelectMultipleRoute =
  StoriesInputSelectMultipleRouteImport.update({
    id: '/input-select-multiple',
    path: '/input-select-multiple',
    getParentRoute: () => StoriesRouteRoute,
  } as any)
const StoriesInputSelectRoute = StoriesInputSelectRouteImport.update({
  id: '/input-select',
  path: '/input-select',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesInputRadioGroupRoute = StoriesInputRadioGroupRouteImport.update({
  id: '/input-radio-group',
  path: '/input-radio-group',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesInputRadioCardRoute = StoriesInputRadioCardRouteImport.update({
  id: '/input-radio-card',
  path: '/input-radio-card',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesInputRadioRoute = StoriesInputRadioRouteImport.update({
  id: '/input-radio',
  path: '/input-radio',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesInputPinRoute = StoriesInputPinRouteImport.update({
  id: '/input-pin',
  path: '/input-pin',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesInputPasswordRoute = StoriesInputPasswordRouteImport.update({
  id: '/input-password',
  path: '/input-password',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesInputNumberRoute = StoriesInputNumberRouteImport.update({
  id: '/input-number',
  path: '/input-number',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesInputDateRoute = StoriesInputDateRouteImport.update({
  id: '/input-date',
  path: '/input-date',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesInputCheckboxGroupRoute =
  StoriesInputCheckboxGroupRouteImport.update({
    id: '/input-checkbox-group',
    path: '/input-checkbox-group',
    getParentRoute: () => StoriesRouteRoute,
  } as any)
const StoriesInputCheckboxCardRoute =
  StoriesInputCheckboxCardRouteImport.update({
    id: '/input-checkbox-card',
    path: '/input-checkbox-card',
    getParentRoute: () => StoriesRouteRoute,
  } as any)
const StoriesInputCheckboxRoute = StoriesInputCheckboxRouteImport.update({
  id: '/input-checkbox',
  path: '/input-checkbox',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesIndicatorRoute = StoriesIndicatorRouteImport.update({
  id: '/indicator',
  path: '/indicator',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesIconButtonRoute = StoriesIconButtonRouteImport.update({
  id: '/icon-button',
  path: '/icon-button',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesHighlightRoute = StoriesHighlightRouteImport.update({
  id: '/highlight',
  path: '/highlight',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesEmptyStateRoute = StoriesEmptyStateRouteImport.update({
  id: '/empty-state',
  path: '/empty-state',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesDrawerRoute = StoriesDrawerRouteImport.update({
  id: '/drawer',
  path: '/drawer',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesDividerRoute = StoriesDividerRouteImport.update({
  id: '/divider',
  path: '/divider',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesDataTableRoute = StoriesDataTableRouteImport.update({
  id: '/data-table',
  path: '/data-table',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesButtonRoute = StoriesButtonRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesBadgeRoute = StoriesBadgeRouteImport.update({
  id: '/badge',
  path: '/badge',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesAvatarRoute = StoriesAvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const StoriesAiIconRoute = StoriesAiIconRouteImport.update({
  id: '/ai-icon',
  path: '/ai-icon',
  getParentRoute: () => StoriesRouteRoute,
} as any)
const OnBoardingTokenRoute = OnBoardingTokenRouteImport.update({
  id: '/on-boarding/$token',
  path: '/on-boarding/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof RouteRoute
  '/stories': typeof StoriesRouteRouteWithChildren
  '/on-boarding/$token': typeof OnBoardingTokenRoute
  '/stories/ai-icon': typeof StoriesAiIconRoute
  '/stories/avatar': typeof StoriesAvatarRoute
  '/stories/badge': typeof StoriesBadgeRoute
  '/stories/button': typeof StoriesButtonRoute
  '/stories/data-table': typeof StoriesDataTableRoute
  '/stories/divider': typeof StoriesDividerRoute
  '/stories/drawer': typeof StoriesDrawerRoute
  '/stories/empty-state': typeof StoriesEmptyStateRoute
  '/stories/highlight': typeof StoriesHighlightRoute
  '/stories/icon-button': typeof StoriesIconButtonRoute
  '/stories/indicator': typeof StoriesIndicatorRoute
  '/stories/input-checkbox': typeof StoriesInputCheckboxRoute
  '/stories/input-checkbox-card': typeof StoriesInputCheckboxCardRoute
  '/stories/input-checkbox-group': typeof StoriesInputCheckboxGroupRoute
  '/stories/input-date': typeof StoriesInputDateRoute
  '/stories/input-number': typeof StoriesInputNumberRoute
  '/stories/input-password': typeof StoriesInputPasswordRoute
  '/stories/input-pin': typeof StoriesInputPinRoute
  '/stories/input-radio': typeof StoriesInputRadioRoute
  '/stories/input-radio-card': typeof StoriesInputRadioCardRoute
  '/stories/input-radio-group': typeof StoriesInputRadioGroupRoute
  '/stories/input-select': typeof StoriesInputSelectRoute
  '/stories/input-select-multiple': typeof StoriesInputSelectMultipleRoute
  '/stories/input-switch': typeof StoriesInputSwitchRoute
  '/stories/input-switch-group': typeof StoriesInputSwitchGroupRoute
  '/stories/input-text': typeof StoriesInputTextRoute
  '/stories/input-textarea': typeof StoriesInputTextareaRoute
  '/stories/input-time': typeof StoriesInputTimeRoute
  '/stories/menu': typeof StoriesMenuRoute
  '/stories/modal': typeof StoriesModalRoute
  '/stories/pagination': typeof StoriesPaginationRoute
  '/stories/popover': typeof StoriesPopoverRoute
  '/stories/scroll-area': typeof StoriesScrollAreaRoute
  '/stories/stepper': typeof StoriesStepperRoute
  '/stories/table': typeof StoriesTableRoute
  '/stories/tabs': typeof StoriesTabsRoute
  '/stories/toast': typeof StoriesToastRoute
  '/stories/tooltip': typeof StoriesTooltipRoute
  '/on-boarding': typeof OnBoardingIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
  '/sign-in': typeof AuthSignInIndexRoute
  '/sign-up': typeof AuthSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof RouteRoute
  '/on-boarding/$token': typeof OnBoardingTokenRoute
  '/stories/ai-icon': typeof StoriesAiIconRoute
  '/stories/avatar': typeof StoriesAvatarRoute
  '/stories/badge': typeof StoriesBadgeRoute
  '/stories/button': typeof StoriesButtonRoute
  '/stories/data-table': typeof StoriesDataTableRoute
  '/stories/divider': typeof StoriesDividerRoute
  '/stories/drawer': typeof StoriesDrawerRoute
  '/stories/empty-state': typeof StoriesEmptyStateRoute
  '/stories/highlight': typeof StoriesHighlightRoute
  '/stories/icon-button': typeof StoriesIconButtonRoute
  '/stories/indicator': typeof StoriesIndicatorRoute
  '/stories/input-checkbox': typeof StoriesInputCheckboxRoute
  '/stories/input-checkbox-card': typeof StoriesInputCheckboxCardRoute
  '/stories/input-checkbox-group': typeof StoriesInputCheckboxGroupRoute
  '/stories/input-date': typeof StoriesInputDateRoute
  '/stories/input-number': typeof StoriesInputNumberRoute
  '/stories/input-password': typeof StoriesInputPasswordRoute
  '/stories/input-pin': typeof StoriesInputPinRoute
  '/stories/input-radio': typeof StoriesInputRadioRoute
  '/stories/input-radio-card': typeof StoriesInputRadioCardRoute
  '/stories/input-radio-group': typeof StoriesInputRadioGroupRoute
  '/stories/input-select': typeof StoriesInputSelectRoute
  '/stories/input-select-multiple': typeof StoriesInputSelectMultipleRoute
  '/stories/input-switch': typeof StoriesInputSwitchRoute
  '/stories/input-switch-group': typeof StoriesInputSwitchGroupRoute
  '/stories/input-text': typeof StoriesInputTextRoute
  '/stories/input-textarea': typeof StoriesInputTextareaRoute
  '/stories/input-time': typeof StoriesInputTimeRoute
  '/stories/menu': typeof StoriesMenuRoute
  '/stories/modal': typeof StoriesModalRoute
  '/stories/pagination': typeof StoriesPaginationRoute
  '/stories/popover': typeof StoriesPopoverRoute
  '/stories/scroll-area': typeof StoriesScrollAreaRoute
  '/stories/stepper': typeof StoriesStepperRoute
  '/stories/table': typeof StoriesTableRoute
  '/stories/tabs': typeof StoriesTabsRoute
  '/stories/toast': typeof StoriesToastRoute
  '/stories/tooltip': typeof StoriesTooltipRoute
  '/on-boarding': typeof OnBoardingIndexRoute
  '/stories': typeof StoriesIndexRoute
  '/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
  '/sign-in': typeof AuthSignInIndexRoute
  '/sign-up': typeof AuthSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof RouteRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/stories': typeof StoriesRouteRouteWithChildren
  '/on-boarding/$token': typeof OnBoardingTokenRoute
  '/stories/ai-icon': typeof StoriesAiIconRoute
  '/stories/avatar': typeof StoriesAvatarRoute
  '/stories/badge': typeof StoriesBadgeRoute
  '/stories/button': typeof StoriesButtonRoute
  '/stories/data-table': typeof StoriesDataTableRoute
  '/stories/divider': typeof StoriesDividerRoute
  '/stories/drawer': typeof StoriesDrawerRoute
  '/stories/empty-state': typeof StoriesEmptyStateRoute
  '/stories/highlight': typeof StoriesHighlightRoute
  '/stories/icon-button': typeof StoriesIconButtonRoute
  '/stories/indicator': typeof StoriesIndicatorRoute
  '/stories/input-checkbox': typeof StoriesInputCheckboxRoute
  '/stories/input-checkbox-card': typeof StoriesInputCheckboxCardRoute
  '/stories/input-checkbox-group': typeof StoriesInputCheckboxGroupRoute
  '/stories/input-date': typeof StoriesInputDateRoute
  '/stories/input-number': typeof StoriesInputNumberRoute
  '/stories/input-password': typeof StoriesInputPasswordRoute
  '/stories/input-pin': typeof StoriesInputPinRoute
  '/stories/input-radio': typeof StoriesInputRadioRoute
  '/stories/input-radio-card': typeof StoriesInputRadioCardRoute
  '/stories/input-radio-group': typeof StoriesInputRadioGroupRoute
  '/stories/input-select': typeof StoriesInputSelectRoute
  '/stories/input-select-multiple': typeof StoriesInputSelectMultipleRoute
  '/stories/input-switch': typeof StoriesInputSwitchRoute
  '/stories/input-switch-group': typeof StoriesInputSwitchGroupRoute
  '/stories/input-text': typeof StoriesInputTextRoute
  '/stories/input-textarea': typeof StoriesInputTextareaRoute
  '/stories/input-time': typeof StoriesInputTimeRoute
  '/stories/menu': typeof StoriesMenuRoute
  '/stories/modal': typeof StoriesModalRoute
  '/stories/pagination': typeof StoriesPaginationRoute
  '/stories/popover': typeof StoriesPopoverRoute
  '/stories/scroll-area': typeof StoriesScrollAreaRoute
  '/stories/stepper': typeof StoriesStepperRoute
  '/stories/table': typeof StoriesTableRoute
  '/stories/tabs': typeof StoriesTabsRoute
  '/stories/toast': typeof StoriesToastRoute
  '/stories/tooltip': typeof StoriesTooltipRoute
  '/on-boarding/': typeof OnBoardingIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/_auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/_auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/_auth/sign-in/': typeof AuthSignInIndexRoute
  '/_auth/sign-up/': typeof AuthSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/stories'
    | '/on-boarding/$token'
    | '/stories/ai-icon'
    | '/stories/avatar'
    | '/stories/badge'
    | '/stories/button'
    | '/stories/data-table'
    | '/stories/divider'
    | '/stories/drawer'
    | '/stories/empty-state'
    | '/stories/highlight'
    | '/stories/icon-button'
    | '/stories/indicator'
    | '/stories/input-checkbox'
    | '/stories/input-checkbox-card'
    | '/stories/input-checkbox-group'
    | '/stories/input-date'
    | '/stories/input-number'
    | '/stories/input-password'
    | '/stories/input-pin'
    | '/stories/input-radio'
    | '/stories/input-radio-card'
    | '/stories/input-radio-group'
    | '/stories/input-select'
    | '/stories/input-select-multiple'
    | '/stories/input-switch'
    | '/stories/input-switch-group'
    | '/stories/input-text'
    | '/stories/input-textarea'
    | '/stories/input-time'
    | '/stories/menu'
    | '/stories/modal'
    | '/stories/pagination'
    | '/stories/popover'
    | '/stories/scroll-area'
    | '/stories/stepper'
    | '/stories/table'
    | '/stories/tabs'
    | '/stories/toast'
    | '/stories/tooltip'
    | '/on-boarding'
    | '/stories/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/on-boarding/$token'
    | '/stories/ai-icon'
    | '/stories/avatar'
    | '/stories/badge'
    | '/stories/button'
    | '/stories/data-table'
    | '/stories/divider'
    | '/stories/drawer'
    | '/stories/empty-state'
    | '/stories/highlight'
    | '/stories/icon-button'
    | '/stories/indicator'
    | '/stories/input-checkbox'
    | '/stories/input-checkbox-card'
    | '/stories/input-checkbox-group'
    | '/stories/input-date'
    | '/stories/input-number'
    | '/stories/input-password'
    | '/stories/input-pin'
    | '/stories/input-radio'
    | '/stories/input-radio-card'
    | '/stories/input-radio-group'
    | '/stories/input-select'
    | '/stories/input-select-multiple'
    | '/stories/input-switch'
    | '/stories/input-switch-group'
    | '/stories/input-text'
    | '/stories/input-textarea'
    | '/stories/input-time'
    | '/stories/menu'
    | '/stories/modal'
    | '/stories/pagination'
    | '/stories/popover'
    | '/stories/scroll-area'
    | '/stories/stepper'
    | '/stories/table'
    | '/stories/tabs'
    | '/stories/toast'
    | '/stories/tooltip'
    | '/on-boarding'
    | '/stories'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/stories'
    | '/on-boarding/$token'
    | '/stories/ai-icon'
    | '/stories/avatar'
    | '/stories/badge'
    | '/stories/button'
    | '/stories/data-table'
    | '/stories/divider'
    | '/stories/drawer'
    | '/stories/empty-state'
    | '/stories/highlight'
    | '/stories/icon-button'
    | '/stories/indicator'
    | '/stories/input-checkbox'
    | '/stories/input-checkbox-card'
    | '/stories/input-checkbox-group'
    | '/stories/input-date'
    | '/stories/input-number'
    | '/stories/input-password'
    | '/stories/input-pin'
    | '/stories/input-radio'
    | '/stories/input-radio-card'
    | '/stories/input-radio-group'
    | '/stories/input-select'
    | '/stories/input-select-multiple'
    | '/stories/input-switch'
    | '/stories/input-switch-group'
    | '/stories/input-text'
    | '/stories/input-textarea'
    | '/stories/input-time'
    | '/stories/menu'
    | '/stories/modal'
    | '/stories/pagination'
    | '/stories/popover'
    | '/stories/scroll-area'
    | '/stories/stepper'
    | '/stories/table'
    | '/stories/tabs'
    | '/stories/toast'
    | '/stories/tooltip'
    | '/on-boarding/'
    | '/stories/'
    | '/_auth/forgot-password/'
    | '/_auth/reset-password/'
    | '/_auth/sign-in/'
    | '/_auth/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RouteRoute: typeof RouteRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  StoriesRouteRoute: typeof StoriesRouteRouteWithChildren
  OnBoardingTokenRoute: typeof OnBoardingTokenRoute
  OnBoardingIndexRoute: typeof OnBoardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/on-boarding/': {
      id: '/on-boarding/'
      path: '/on-boarding'
      fullPath: '/on-boarding'
      preLoaderRoute: typeof OnBoardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/tooltip': {
      id: '/stories/tooltip'
      path: '/tooltip'
      fullPath: '/stories/tooltip'
      preLoaderRoute: typeof StoriesTooltipRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/toast': {
      id: '/stories/toast'
      path: '/toast'
      fullPath: '/stories/toast'
      preLoaderRoute: typeof StoriesToastRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/tabs': {
      id: '/stories/tabs'
      path: '/tabs'
      fullPath: '/stories/tabs'
      preLoaderRoute: typeof StoriesTabsRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/table': {
      id: '/stories/table'
      path: '/table'
      fullPath: '/stories/table'
      preLoaderRoute: typeof StoriesTableRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/stepper': {
      id: '/stories/stepper'
      path: '/stepper'
      fullPath: '/stories/stepper'
      preLoaderRoute: typeof StoriesStepperRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/scroll-area': {
      id: '/stories/scroll-area'
      path: '/scroll-area'
      fullPath: '/stories/scroll-area'
      preLoaderRoute: typeof StoriesScrollAreaRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/popover': {
      id: '/stories/popover'
      path: '/popover'
      fullPath: '/stories/popover'
      preLoaderRoute: typeof StoriesPopoverRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/pagination': {
      id: '/stories/pagination'
      path: '/pagination'
      fullPath: '/stories/pagination'
      preLoaderRoute: typeof StoriesPaginationRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/modal': {
      id: '/stories/modal'
      path: '/modal'
      fullPath: '/stories/modal'
      preLoaderRoute: typeof StoriesModalRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/menu': {
      id: '/stories/menu'
      path: '/menu'
      fullPath: '/stories/menu'
      preLoaderRoute: typeof StoriesMenuRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/input-time': {
      id: '/stories/input-time'
      path: '/input-time'
      fullPath: '/stories/input-time'
      preLoaderRoute: typeof StoriesInputTimeRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/input-textarea': {
      id: '/stories/input-textarea'
      path: '/input-textarea'
      fullPath: '/stories/input-textarea'
      preLoaderRoute: typeof StoriesInputTextareaRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/input-text': {
      id: '/stories/input-text'
      path: '/input-text'
      fullPath: '/stories/input-text'
      preLoaderRoute: typeof StoriesInputTextRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/input-switch-group': {
      id: '/stories/input-switch-group'
      path: '/input-switch-group'
      fullPath: '/stories/input-switch-group'
      preLoaderRoute: typeof StoriesInputSwitchGroupRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/input-switch': {
      id: '/stories/input-switch'
      path: '/input-switch'
      fullPath: '/stories/input-switch'
      preLoaderRoute: typeof StoriesInputSwitchRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/input-select-multiple': {
      id: '/stories/input-select-multiple'
      path: '/input-select-multiple'
      fullPath: '/stories/input-select-multiple'
      preLoaderRoute: typeof StoriesInputSelectMultipleRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/input-select': {
      id: '/stories/input-select'
      path: '/input-select'
      fullPath: '/stories/input-select'
      preLoaderRoute: typeof StoriesInputSelectRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/input-radio-group': {
      id: '/stories/input-radio-group'
      path: '/input-radio-group'
      fullPath: '/stories/input-radio-group'
      preLoaderRoute: typeof StoriesInputRadioGroupRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/input-radio-card': {
      id: '/stories/input-radio-card'
      path: '/input-radio-card'
      fullPath: '/stories/input-radio-card'
      preLoaderRoute: typeof StoriesInputRadioCardRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/input-radio': {
      id: '/stories/input-radio'
      path: '/input-radio'
      fullPath: '/stories/input-radio'
      preLoaderRoute: typeof StoriesInputRadioRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/input-pin': {
      id: '/stories/input-pin'
      path: '/input-pin'
      fullPath: '/stories/input-pin'
      preLoaderRoute: typeof StoriesInputPinRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/input-password': {
      id: '/stories/input-password'
      path: '/input-password'
      fullPath: '/stories/input-password'
      preLoaderRoute: typeof StoriesInputPasswordRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/input-number': {
      id: '/stories/input-number'
      path: '/input-number'
      fullPath: '/stories/input-number'
      preLoaderRoute: typeof StoriesInputNumberRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/input-date': {
      id: '/stories/input-date'
      path: '/input-date'
      fullPath: '/stories/input-date'
      preLoaderRoute: typeof StoriesInputDateRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/input-checkbox-group': {
      id: '/stories/input-checkbox-group'
      path: '/input-checkbox-group'
      fullPath: '/stories/input-checkbox-group'
      preLoaderRoute: typeof StoriesInputCheckboxGroupRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/input-checkbox-card': {
      id: '/stories/input-checkbox-card'
      path: '/input-checkbox-card'
      fullPath: '/stories/input-checkbox-card'
      preLoaderRoute: typeof StoriesInputCheckboxCardRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/input-checkbox': {
      id: '/stories/input-checkbox'
      path: '/input-checkbox'
      fullPath: '/stories/input-checkbox'
      preLoaderRoute: typeof StoriesInputCheckboxRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/indicator': {
      id: '/stories/indicator'
      path: '/indicator'
      fullPath: '/stories/indicator'
      preLoaderRoute: typeof StoriesIndicatorRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/icon-button': {
      id: '/stories/icon-button'
      path: '/icon-button'
      fullPath: '/stories/icon-button'
      preLoaderRoute: typeof StoriesIconButtonRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/highlight': {
      id: '/stories/highlight'
      path: '/highlight'
      fullPath: '/stories/highlight'
      preLoaderRoute: typeof StoriesHighlightRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/empty-state': {
      id: '/stories/empty-state'
      path: '/empty-state'
      fullPath: '/stories/empty-state'
      preLoaderRoute: typeof StoriesEmptyStateRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/drawer': {
      id: '/stories/drawer'
      path: '/drawer'
      fullPath: '/stories/drawer'
      preLoaderRoute: typeof StoriesDrawerRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/divider': {
      id: '/stories/divider'
      path: '/divider'
      fullPath: '/stories/divider'
      preLoaderRoute: typeof StoriesDividerRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/data-table': {
      id: '/stories/data-table'
      path: '/data-table'
      fullPath: '/stories/data-table'
      preLoaderRoute: typeof StoriesDataTableRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/button': {
      id: '/stories/button'
      path: '/button'
      fullPath: '/stories/button'
      preLoaderRoute: typeof StoriesButtonRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/badge': {
      id: '/stories/badge'
      path: '/badge'
      fullPath: '/stories/badge'
      preLoaderRoute: typeof StoriesBadgeRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/avatar': {
      id: '/stories/avatar'
      path: '/avatar'
      fullPath: '/stories/avatar'
      preLoaderRoute: typeof StoriesAvatarRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/stories/ai-icon': {
      id: '/stories/ai-icon'
      path: '/ai-icon'
      fullPath: '/stories/ai-icon'
      preLoaderRoute: typeof StoriesAiIconRouteImport
      parentRoute: typeof StoriesRouteRoute
    }
    '/on-boarding/$token': {
      id: '/on-boarding/$token'
      path: '/on-boarding/$token'
      fullPath: '/on-boarding/$token'
      preLoaderRoute: typeof OnBoardingTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up/': {
      id: '/_auth/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in/': {
      id: '/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password/': {
      id: '/_auth/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password/': {
      id: '/_auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface StoriesRouteRouteChildren {
  StoriesAiIconRoute: typeof StoriesAiIconRoute
  StoriesAvatarRoute: typeof StoriesAvatarRoute
  StoriesBadgeRoute: typeof StoriesBadgeRoute
  StoriesButtonRoute: typeof StoriesButtonRoute
  StoriesDataTableRoute: typeof StoriesDataTableRoute
  StoriesDividerRoute: typeof StoriesDividerRoute
  StoriesDrawerRoute: typeof StoriesDrawerRoute
  StoriesEmptyStateRoute: typeof StoriesEmptyStateRoute
  StoriesHighlightRoute: typeof StoriesHighlightRoute
  StoriesIconButtonRoute: typeof StoriesIconButtonRoute
  StoriesIndicatorRoute: typeof StoriesIndicatorRoute
  StoriesInputCheckboxRoute: typeof StoriesInputCheckboxRoute
  StoriesInputCheckboxCardRoute: typeof StoriesInputCheckboxCardRoute
  StoriesInputCheckboxGroupRoute: typeof StoriesInputCheckboxGroupRoute
  StoriesInputDateRoute: typeof StoriesInputDateRoute
  StoriesInputNumberRoute: typeof StoriesInputNumberRoute
  StoriesInputPasswordRoute: typeof StoriesInputPasswordRoute
  StoriesInputPinRoute: typeof StoriesInputPinRoute
  StoriesInputRadioRoute: typeof StoriesInputRadioRoute
  StoriesInputRadioCardRoute: typeof StoriesInputRadioCardRoute
  StoriesInputRadioGroupRoute: typeof StoriesInputRadioGroupRoute
  StoriesInputSelectRoute: typeof StoriesInputSelectRoute
  StoriesInputSelectMultipleRoute: typeof StoriesInputSelectMultipleRoute
  StoriesInputSwitchRoute: typeof StoriesInputSwitchRoute
  StoriesInputSwitchGroupRoute: typeof StoriesInputSwitchGroupRoute
  StoriesInputTextRoute: typeof StoriesInputTextRoute
  StoriesInputTextareaRoute: typeof StoriesInputTextareaRoute
  StoriesInputTimeRoute: typeof StoriesInputTimeRoute
  StoriesMenuRoute: typeof StoriesMenuRoute
  StoriesModalRoute: typeof StoriesModalRoute
  StoriesPaginationRoute: typeof StoriesPaginationRoute
  StoriesPopoverRoute: typeof StoriesPopoverRoute
  StoriesScrollAreaRoute: typeof StoriesScrollAreaRoute
  StoriesStepperRoute: typeof StoriesStepperRoute
  StoriesTableRoute: typeof StoriesTableRoute
  StoriesTabsRoute: typeof StoriesTabsRoute
  StoriesToastRoute: typeof StoriesToastRoute
  StoriesTooltipRoute: typeof StoriesTooltipRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

const StoriesRouteRouteChildren: StoriesRouteRouteChildren = {
  StoriesAiIconRoute: StoriesAiIconRoute,
  StoriesAvatarRoute: StoriesAvatarRoute,
  StoriesBadgeRoute: StoriesBadgeRoute,
  StoriesButtonRoute: StoriesButtonRoute,
  StoriesDataTableRoute: StoriesDataTableRoute,
  StoriesDividerRoute: StoriesDividerRoute,
  StoriesDrawerRoute: StoriesDrawerRoute,
  StoriesEmptyStateRoute: StoriesEmptyStateRoute,
  StoriesHighlightRoute: StoriesHighlightRoute,
  StoriesIconButtonRoute: StoriesIconButtonRoute,
  StoriesIndicatorRoute: StoriesIndicatorRoute,
  StoriesInputCheckboxRoute: StoriesInputCheckboxRoute,
  StoriesInputCheckboxCardRoute: StoriesInputCheckboxCardRoute,
  StoriesInputCheckboxGroupRoute: StoriesInputCheckboxGroupRoute,
  StoriesInputDateRoute: StoriesInputDateRoute,
  StoriesInputNumberRoute: StoriesInputNumberRoute,
  StoriesInputPasswordRoute: StoriesInputPasswordRoute,
  StoriesInputPinRoute: StoriesInputPinRoute,
  StoriesInputRadioRoute: StoriesInputRadioRoute,
  StoriesInputRadioCardRoute: StoriesInputRadioCardRoute,
  StoriesInputRadioGroupRoute: StoriesInputRadioGroupRoute,
  StoriesInputSelectRoute: StoriesInputSelectRoute,
  StoriesInputSelectMultipleRoute: StoriesInputSelectMultipleRoute,
  StoriesInputSwitchRoute: StoriesInputSwitchRoute,
  StoriesInputSwitchGroupRoute: StoriesInputSwitchGroupRoute,
  StoriesInputTextRoute: StoriesInputTextRoute,
  StoriesInputTextareaRoute: StoriesInputTextareaRoute,
  StoriesInputTimeRoute: StoriesInputTimeRoute,
  StoriesMenuRoute: StoriesMenuRoute,
  StoriesModalRoute: StoriesModalRoute,
  StoriesPaginationRoute: StoriesPaginationRoute,
  StoriesPopoverRoute: StoriesPopoverRoute,
  StoriesScrollAreaRoute: StoriesScrollAreaRoute,
  StoriesStepperRoute: StoriesStepperRoute,
  StoriesTableRoute: StoriesTableRoute,
  StoriesTabsRoute: StoriesTabsRoute,
  StoriesToastRoute: StoriesToastRoute,
  StoriesTooltipRoute: StoriesTooltipRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}

const StoriesRouteRouteWithChildren = StoriesRouteRoute._addFileChildren(
  StoriesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RouteRoute: RouteRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  StoriesRouteRoute: StoriesRouteRouteWithChildren,
  OnBoardingTokenRoute: OnBoardingTokenRoute,
  OnBoardingIndexRoute: OnBoardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
