"""Pydantic models for the Report Agent (Phase 1 Dynamic Prompt & Phase 2 Report Plan)."""
from __future__ import annotations

from typing import Any, Optional
from pydantic import AliasChoices, BaseModel, ConfigDict, Field


class ReportAgentTemplate(BaseModel):
    """Business-level definition of a report template (no database column names)."""

    id: str
    title: str
    domain: str
    description: str


class DiscoveredField(BaseModel):
    """A single database column discovered during schema inspection."""

    table: str
    column: str
    type: str


class MissingField(BaseModel):
    """A business field needed by a template that is absent from the schema."""

    field: str
    status: str = "missing"
    reason: str = "No database field or calculable source was found."


class GeneratePromptRequest(BaseModel):
    """Input payload when requesting dynamic prompt generation for a template."""

    template_id: str = Field(
        ...,
        validation_alias=AliasChoices("templateId", "template_id", "id"),
        description="Template identifier (e.g. tpl-pending-workflow-requests).",
    )
    title: Optional[str] = Field(
        default=None,
        description="Optional template title (will be loaded from template registry if omitted).",
    )
    domain: Optional[str] = Field(
        default=None,
        description="Optional domain category (will be loaded from template registry if omitted).",
    )
    description: Optional[str] = Field(
        default=None,
        description="Optional description (will be loaded from template registry if omitted).",
    )
    tenant_id: Optional[str] = Field(
        default=None,
        validation_alias=AliasChoices("tenantId", "tenant_id", "TenantId"),
        description="Optional tenant UUID for multi-tenant database connection.",
    )


class GeneratePromptResponse(BaseModel):
    """Output payload with discovered schema and generated prompt."""

    template_id: str = Field(..., serialization_alias="templateId")
    title: str
    domain: str
    discovered_tables: list[str] = Field(default_factory=list, serialization_alias="discoveredTables")
    discovered_fields: list[DiscoveredField] = Field(
        default_factory=list, serialization_alias="discoveredFields"
    )
    missing_fields: list[MissingField] = Field(
        default_factory=list, serialization_alias="missingFields"
    )
    prompt: str


# --- Phase 2: Report Plan Models ---


class BusinessFilter(BaseModel):
    """A business-level filter extracted from prompt text."""

    concept: str
    operator: str = "="
    value: Any = None
    raw_text: Optional[str] = None


class BusinessSort(BaseModel):
    """A business-level sort criteria extracted from prompt text."""

    concept: str
    direction: str = "ASC"


class PromptIntent(BaseModel):
    """Structured business intent extracted from user prompt text."""

    title: Optional[str] = None
    description: Optional[str] = None
    requested_tables: list[str] = Field(default_factory=list)
    requested_fields: list[str] = Field(default_factory=list)
    requested_filters: list[BusinessFilter] = Field(default_factory=list)
    group_by_concepts: list[str] = Field(default_factory=list)
    sort_concepts: list[BusinessSort] = Field(default_factory=list)
    requested_calculations: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


class ReportColumn(BaseModel):
    """A column included in the report plan."""

    field: str
    label: str
    type: str
    format: Optional[str] = None


class ReportFilter(BaseModel):
    """A filter condition in the report plan."""

    field: str
    operator: str  # =, !=, IN, NOT IN, >, <, >=, <=, IS NULL, IS NOT NULL, LIKE, ILIKE, BETWEEN
    value: Any


class ReportCalculation(BaseModel):
    """A calculated or aggregated field in the report plan."""

    label: str
    expression: str
    type: str = "text"


class ReportSort(BaseModel):
    """Sort criteria in the report plan."""

    field: str
    direction: str = "ASC"  # ASC or DESC


class ReportSource(BaseModel):
    """Data source definition for the report plan."""

    table: str
    schema_name: Optional[str] = Field(default=None, serialization_alias="schemaName")
    joins: list[dict[str, Any]] = Field(default_factory=list)


class ReportPlan(BaseModel):
    """Structured report plan generated by the Report Agent."""

    title: str
    description: str
    template_id: str = Field(..., serialization_alias="templateId")
    source: ReportSource
    columns: list[ReportColumn] = Field(default_factory=list)
    filters: list[ReportFilter] = Field(default_factory=list)
    calculations: list[ReportCalculation] = Field(default_factory=list)
    group_by: list[str] = Field(default_factory=list, serialization_alias="groupBy")
    order_by: list[ReportSort] = Field(default_factory=list, serialization_alias="orderBy")
    status_rules: list[dict[str, Any]] = Field(default_factory=list, serialization_alias="statusRules")
    warnings: list[str] = Field(default_factory=list)


class DataQuery(BaseModel):
    """Safe read-only query generated from the report plan."""

    sql: str
    read_only: bool = Field(default=True, serialization_alias="readOnly")
    limit: int = 50


class ReportData(BaseModel):
    """Execution results returned by the database query."""

    row_count: int = Field(default=0, serialization_alias="rowCount")
    columns: list[str] = Field(default_factory=list)
    rows: list[dict[str, Any]] = Field(default_factory=list)


class ReportValidation(BaseModel):
    """Validation report checking schema, SQL safety, and data integrity."""

    valid: bool = True
    errors: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    checks: dict[str, bool] = Field(default_factory=dict)


class DiscoveredSchemaSummary(BaseModel):
    """Discovered schema container."""

    tables: list[str] = Field(default_factory=list)
    fields: list[DiscoveredField] = Field(default_factory=list)


class GenerateReportPlanRequest(BaseModel):
    """Input payload to generate a Report Plan and query live database data."""

    prompt: Optional[str] = Field(
        default=None,
        description="Dynamic report prompt from Phase 1 containing Title and Discovered database schema.",
    )
    template_id: Optional[str] = Field(
        default=None,
        validation_alias=AliasChoices("templateId", "template_id", "id"),
        description="Optional template identifier (e.g. tpl-pending-workflow-requests) or title.",
    )
    discovered_schema: Optional[DiscoveredSchemaSummary] = Field(
        default=None,
        validation_alias=AliasChoices("discoveredSchema", "discovered_schema"),
        description="Optional Phase 1 schema for client context. The server always re-discovers and validates fields from the live database before planning.",
    )
    tenant_id: Optional[str] = Field(
        default=None,
        validation_alias=AliasChoices("tenantId", "tenant_id", "TenantId"),
        description="Optional tenant UUID for multi-tenant database connection.",
    )
    limit: Optional[int] = Field(
        default=50,
        ge=1,
        le=500,
        description="Maximum rows to fetch for report data preview (default 50).",
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "prompt": "string",
                "tenantId": "string",
            },
            "examples": [
                {
                    "prompt": "string",
                    "tenantId": "string",
                }
            ],
        }
    )


class GenerateReportPlanResponse(BaseModel):
    """Complete Phase 2 output: Report Plan + Safe SQL + Live Data + Validation."""

    template_id: str = Field(..., serialization_alias="templateId")
    report_plan: ReportPlan = Field(..., serialization_alias="reportPlan")
    database_schema: DiscoveredSchemaSummary = Field(..., serialization_alias="databaseSchema")
    data_query: DataQuery = Field(..., serialization_alias="dataQuery")
    data: ReportData
    validation: ReportValidation
