"""PDF Generation Engine for EZOFIS AI Orchestrator.

Converts arbitrary or structured JSON data into elegant, professional,
publication-quality PDF documents using ReportLab.
"""
from __future__ import annotations

import base64
import html
import io
import json
import logging
import os
import re
import tempfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

import fitz  # PyMuPDF for page inspection and validation
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch, mm
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.pdf_skills.rules import (
    format_cell_value,
    infer_document_title,
    resolve_theme,
    sanitize_filename,
)
from app.pdf_skills.template_renderer import (
    is_pdfme_template,
    render_pdfme_template_to_pdf,
)

logger = logging.getLogger("orchestrator.pdf_skills")


@dataclass
class PdfGenerationResult:
    status: str
    filename: str
    file_path: str
    pdf_bytes: bytes
    pdf_base64: str
    page_count: int
    file_size_bytes: int
    title: str
    generated_at: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "status": self.status,
            "filename": self.filename,
            "file_path": self.file_path,
            "pdf_base64": self.pdf_base64,
            "page_count": self.page_count,
            "file_size_bytes": self.file_size_bytes,
            "title": self.title,
            "generated_at": self.generated_at,
        }


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas that adds running headers, footers, and dynamic page counts."""

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self._saved_page_states: list[dict[str, Any]] = []
        self.doc_title = "Document"
        self.theme_colors = resolve_theme(None)

    def showPage(self) -> None:
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self) -> None:
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_page_decorations(self, page_count: int) -> None:
        self.saveState()
        w, h = self._pagesize
        left = 40.0
        right = w - 40.0

        primary_col = colors.HexColor(self.theme_colors.get("primary", "#1E40AF"))
        muted_col = colors.HexColor(self.theme_colors.get("text_muted", "#64748B"))
        border_col = colors.HexColor(self.theme_colors.get("border", "#E2E8F0"))

        # Header (pages > 1)
        if self._pageNumber > 1:
            self.setFont("Helvetica-Bold", 8)
            self.setFillColor(primary_col)
            self.drawString(left, h - 28.0, "EZOFIS")

            self.setFont("Helvetica", 8)
            self.setFillColor(muted_col)
            short_title = self.doc_title[:45] + ("..." if len(self.doc_title) > 45 else "")
            self.drawString(left + 45.0, h - 28.0, f"|  {short_title}")

            self.setStrokeColor(border_col)
            self.setLineWidth(0.6)
            self.line(left, h - 34.0, right, h - 34.0)

        # Footer (all pages)
        self.setStrokeColor(border_col)
        self.setLineWidth(0.6)
        self.line(left, 36.0, right, 36.0)

        self.setFont("Helvetica", 8)
        self.setFillColor(muted_col)
        self.drawString(left, 24.0, "Generated by EZOFIS AI Orchestrator")

        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(right, 24.0, page_str)

        self.restoreState()


def _make_styles(theme: dict[str, str]) -> dict[str, ParagraphStyle]:
    sample = getSampleStyleSheet()

    primary = colors.HexColor(theme.get("primary", "#1E40AF"))
    secondary = colors.HexColor(theme.get("secondary", "#3B82F6"))
    text_color = colors.HexColor(theme.get("text", "#0F172A"))
    muted_color = colors.HexColor(theme.get("text_muted", "#64748B"))

    return {
        "title": ParagraphStyle(
            "DocTitle",
            parent=sample["Normal"],
            fontName="Helvetica-Bold",
            fontSize=20,
            leading=24,
            textColor=primary,
            spaceAfter=4,
        ),
        "subtitle": ParagraphStyle(
            "DocSubtitle",
            parent=sample["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=muted_color,
            spaceAfter=12,
        ),
        "section_h1": ParagraphStyle(
            "SectionH1",
            parent=sample["Normal"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=17,
            textColor=primary,
            spaceBefore=14,
            spaceAfter=6,
            keepWithNext=True,
        ),
        "section_h2": ParagraphStyle(
            "SectionH2",
            parent=sample["Normal"],
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=15,
            textColor=secondary,
            spaceBefore=10,
            spaceAfter=4,
            keepWithNext=True,
        ),
        "body": ParagraphStyle(
            "DocBody",
            parent=sample["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=13,
            textColor=text_color,
            spaceAfter=4,
        ),
        "body_bold": ParagraphStyle(
            "DocBodyBold",
            parent=sample["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=13,
            textColor=text_color,
        ),
        "meta_label": ParagraphStyle(
            "MetaLabel",
            parent=sample["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=11,
            textColor=muted_color,
        ),
        "meta_val": ParagraphStyle(
            "MetaValue",
            parent=sample["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=12,
            textColor=text_color,
        ),
        "table_cell": ParagraphStyle(
            "TableCell",
            parent=sample["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=11.5,
            textColor=text_color,
        ),
        "table_cell_bold": ParagraphStyle(
            "TableCellBold",
            parent=sample["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8.5,
            leading=11.5,
            textColor=text_color,
        ),
        "table_cell_right": ParagraphStyle(
            "TableCellRight",
            parent=sample["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=11.5,
            alignment=2,  # TA_RIGHT
            textColor=text_color,
        ),
        "table_head": ParagraphStyle(
            "TableHead",
            parent=sample["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=12,
            textColor=colors.HexColor(theme.get("table_head_text", "#FFFFFF")),
        ),
        "table_head_right": ParagraphStyle(
            "TableHeadRight",
            parent=sample["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=12,
            alignment=2,  # TA_RIGHT
            textColor=colors.HexColor(theme.get("table_head_text", "#FFFFFF")),
        ),
        "badge": ParagraphStyle(
            "BadgeText",
            parent=sample["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=10,
            textColor=primary,
        ),
    }


def _load_image_reader(image_source: Optional[str]) -> Optional[Any]:
    """Loads an ImageReader or path from a base64 data URL or local file path."""
    if not image_source or not isinstance(image_source, str):
        return None
    raw = image_source.strip()
    if not raw:
        return None
    try:
        if "base64," in raw:
            raw = raw.split("base64,", 1)[1]
        decoded = base64.b64decode(raw)
        return io.BytesIO(decoded)
    except Exception:
        pass
    if os.path.isfile(raw):
        return raw
    return None


def _build_header_banner(
    title: str,
    subtitle: Optional[str],
    date_str: str,
    theme: dict[str, str],
    styles: dict[str, ParagraphStyle],
    usable_width: float,
    logo_source: Optional[str] = None,
    workflow_name: Optional[str] = None,
) -> list[Any]:
    elements: list[Any] = []

    primary = colors.HexColor(theme.get("primary", "#1E40AF"))
    accent = colors.HexColor(theme.get("accent", "#60A5FA"))
    border_col = colors.HexColor(theme.get("border", "#E2E8F0"))

    # Brand / Workflow info
    brand_text = f"<b>EZOFIS</b> &nbsp;<font color='#64748B'>|</font>&nbsp; {html.escape(workflow_name)}" if workflow_name else "<b>EZOFIS</b> &nbsp;<font color='#64748B'>|</font>&nbsp; Enterprise Document Platform"

    # Top brand bar
    top_bar = Table(
        [
            [
                Paragraph(brand_text, styles["meta_label"]),
                Paragraph(f"Date: <b>{html.escape(date_str)}</b>", styles["table_cell_right"]),
            ]
        ],
        colWidths=[usable_width * 0.65, usable_width * 0.35],
    )
    top_bar.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )
    elements.append(top_bar)
    elements.append(HRFlowable(width="100%", thickness=0.8, color=border_col, spaceAfter=8, spaceBefore=4))

    # Title & Subtitle
    elements.append(Paragraph(html.escape(title), styles["title"]))
    if subtitle:
        elements.append(Paragraph(html.escape(subtitle), styles["subtitle"]))
    else:
        elements.append(Spacer(1, 4))

    return elements


def _build_metadata_box(
    metadata_items: list[tuple[str, str]],
    theme: dict[str, str],
    styles: dict[str, ParagraphStyle],
    usable_width: float,
) -> Optional[Table]:
    if not metadata_items:
        return None

    bg_card = colors.HexColor(theme.get("bg_card", "#F8FAFC"))
    border_col = colors.HexColor(theme.get("border", "#E2E8F0"))

    # Determine if 2-col (label, val) or 4-col (label1, val1, label2, val2) is better
    use_4col = len(metadata_items) >= 4

    rows: list[list[Any]] = []
    if use_4col:
        col_w = [usable_width * 0.20, usable_width * 0.30, usable_width * 0.20, usable_width * 0.30]
        for i in range(0, len(metadata_items), 2):
            k1, v1 = metadata_items[i]
            p_k1 = Paragraph(html.escape(k1.replace("_", " ").title()), styles["meta_label"])
            p_v1 = Paragraph(html.escape(v1), styles["meta_val"])
            if i + 1 < len(metadata_items):
                k2, v2 = metadata_items[i + 1]
                p_k2 = Paragraph(html.escape(k2.replace("_", " ").title()), styles["meta_label"])
                p_v2 = Paragraph(html.escape(v2), styles["meta_val"])
            else:
                p_k2, p_v2 = Paragraph("", styles["meta_label"]), Paragraph("", styles["meta_val"])
            rows.append([p_k1, p_v1, p_k2, p_v2])
    else:
        col_w = [usable_width * 0.35, usable_width * 0.65]
        for k, v in metadata_items:
            p_k = Paragraph(html.escape(k.replace("_", " ").title()), styles["meta_label"])
            p_v = Paragraph(html.escape(v), styles["meta_val"])
            rows.append([p_k, p_v])

    t = Table(rows, colWidths=col_w)
    t.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), bg_card),
                ("BOX", (0, 0), (-1, -1), 0.8, border_col),
                ("INNERGRID", (0, 0), (-1, -1), 0.4, border_col),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ]
        )
    )
    return t


def _build_table_from_list_of_dicts(
    records: list[dict[str, Any]],
    theme: dict[str, str],
    styles: dict[str, ParagraphStyle],
    usable_width: float,
) -> Optional[Table]:
    if not records or not isinstance(records[0], dict):
        return None

    # Extract columns from union of keys in records
    cols: list[str] = []
    for r in records:
        if isinstance(r, dict):
            for k in r.keys():
                if k not in cols:
                    cols.append(k)

    if not cols:
        return None

    # Cap to max 8 columns for readability on A4
    if len(cols) > 8:
        cols = cols[:8]

    table_head_bg = colors.HexColor(theme.get("table_head_bg", "#1E40AF"))
    table_alt_bg = colors.HexColor(theme.get("table_alt_bg", "#F1F5F9"))
    border_col = colors.HexColor(theme.get("border", "#E2E8F0"))

    # Compute column weights based on header names and samples
    weights: list[float] = []
    numeric_cols: set[int] = set()

    for idx, col in enumerate(cols):
        max_len = len(str(col))
        is_num = True
        for r in records[:15]:
            if isinstance(r, dict):
                v_str = str(r.get(col, ""))
                max_len = max(max_len, len(v_str))
                val = r.get(col)
                if val is not None and not isinstance(val, (int, float)):
                    # Check if currency or numeric string
                    cleaned = v_str.replace("$", "").replace(",", "").strip()
                    try:
                        float(cleaned)
                    except ValueError:
                        is_num = False
        if is_num and len(records) > 0:
            numeric_cols.add(idx)
        weights.append(min(max(max_len, 6), 35))

    total_weight = sum(weights) or 1.0
    col_widths = [(w / total_weight) * usable_width for w in weights]

    table_data: list[list[Any]] = []

    # Header Row
    head_row: list[Any] = []
    for idx, col in enumerate(cols):
        style = styles["table_head_right"] if idx in numeric_cols else styles["table_head"]
        head_row.append(Paragraph(html.escape(col.replace("_", " ").title()), style))
    table_data.append(head_row)

    # Data Rows
    for r in records:
        row: list[Any] = []
        if not isinstance(r, dict):
            continue
        for idx, col in enumerate(cols):
            val = r.get(col)
            formatted = format_cell_value(val)
            style = styles["table_cell_right"] if idx in numeric_cols else styles["table_cell"]
            row.append(Paragraph(html.escape(formatted), style))
        table_data.append(row)

    t = Table(table_data, colWidths=col_widths, repeatRows=1)
    t_style = [
        ("BACKGROUND", (0, 0), (-1, 0), table_head_bg),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("GRID", (0, 0), (-1, -1), 0.5, border_col),
    ]

    # Alternating row background
    for i in range(1, len(table_data)):
        if i % 2 == 0:
            t_style.append(("BACKGROUND", (0, i), (-1, i), table_alt_bg))

    t.setStyle(TableStyle(t_style))
    return t


def _build_process_history_table(
    process_history: list[dict[str, Any]],
    theme: dict[str, str],
    styles: dict[str, ParagraphStyle],
    usable_width: float,
) -> Optional[Table]:
    """Renders an audit trail / process history table."""
    if not process_history or not isinstance(process_history, list):
        return None

    labels = ["Stage", "Action User", "Received On", "Processed By", "Processed On", "Status"]
    col_w = [
        usable_width * 0.16,
        usable_width * 0.18,
        usable_width * 0.16,
        usable_width * 0.18,
        usable_width * 0.16,
        usable_width * 0.16,
    ]

    table_head_bg = colors.HexColor(theme.get("table_head_bg", "#1E40AF"))
    table_alt_bg = colors.HexColor(theme.get("table_alt_bg", "#F1F5F9"))
    border_col = colors.HexColor(theme.get("border", "#E2E8F0"))

    table_data: list[list[Any]] = []
    # Header
    head_row = [Paragraph(l, styles["table_head"]) for l in labels]
    table_data.append(head_row)

    for item in process_history:
        if not isinstance(item, dict):
            continue
        stage = format_cell_value(item.get("stage") or item.get("stage_name") or "-")
        user = format_cell_value(item.get("actionUser") or item.get("action_user") or item.get("user") or "-")
        rec_on = format_cell_value(item.get("receivedOn") or item.get("received_on") or "-")
        proc_by = format_cell_value(item.get("processedBy") or item.get("processed_by") or "-")
        proc_on = format_cell_value(item.get("processedOn") or item.get("processed_on") or "-")
        status = format_cell_value(item.get("status") or "-")

        table_data.append(
            [
                Paragraph(html.escape(stage), styles["table_cell_bold"]),
                Paragraph(html.escape(user), styles["table_cell"]),
                Paragraph(html.escape(rec_on), styles["table_cell"]),
                Paragraph(html.escape(proc_by), styles["table_cell"]),
                Paragraph(html.escape(proc_on), styles["table_cell"]),
                Paragraph(html.escape(status), styles["table_cell_bold"]),
            ]
        )

    if len(table_data) <= 1:
        return None

    t = Table(table_data, colWidths=col_w, repeatRows=1)
    t_style = [
        ("BACKGROUND", (0, 0), (-1, 0), table_head_bg),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("GRID", (0, 0), (-1, -1), 0.5, border_col),
    ]
    for i in range(1, len(table_data)):
        if i % 2 == 0:
            t_style.append(("BACKGROUND", (0, i), (-1, i), table_alt_bg))

    t.setStyle(TableStyle(t_style))
    return t


def _build_signature_grid(
    signatures: list[Any] | dict[str, Any],
    theme: dict[str, str],
    styles: dict[str, ParagraphStyle],
    usable_width: float,
) -> Optional[Table]:
    """Renders styled signature and approval boxes."""
    if not signatures:
        return None

    norm_sigs: list[dict[str, Any]] = []
    if isinstance(signatures, dict):
        for k, v in signatures.items():
            if isinstance(v, dict):
                norm_sigs.append({
                    "role": k,
                    "name": v.get("name") or v.get("signedBy") or "Authorized Signer",
                    "date": v.get("date") or v.get("timestamp") or v.get("SignedAt") or "",
                })
            else:
                norm_sigs.append({
                    "role": k,
                    "name": str(v),
                    "date": "",
                })
    elif isinstance(signatures, list):
        for sig in signatures:
            if isinstance(sig, dict):
                name = sig.get("name") or sig.get("signedBy") or sig.get("signer") or "Authorized Signer"
                role = sig.get("role") or sig.get("stageName") or sig.get("title") or "Approver"
                date_val = sig.get("date") or sig.get("signedAt") or sig.get("SignedAt") or sig.get("timestamp") or ""
                norm_sigs.append({"role": role, "name": name, "date": date_val})
            else:
                norm_sigs.append({"role": "Approver", "name": str(sig), "date": ""})

    if not norm_sigs:
        return None

    border_col = colors.HexColor(theme.get("border", "#E2E8F0"))
    bg_card = colors.HexColor(theme.get("bg_card", "#F8FAFC"))

    card_count = min(len(norm_sigs), 3)
    card_width = usable_width / card_count

    rows: list[list[Any]] = []
    current_row: list[Any] = []

    for sig in norm_sigs:
        role = sig.get("role", "Approver")
        name = sig.get("name", "Authorized Signer")
        date_val = sig.get("date") or datetime.now(timezone.utc).strftime("%Y-%m-%d")

        content = [
            Paragraph("<b>" + html.escape(str(role).upper()) + "</b>", styles["meta_label"]),
            Spacer(1, 14),
            Paragraph(f"<u>{html.escape(str(name))}</u>", styles["body_bold"]),
            Paragraph(f"Date: {html.escape(str(date_val))}", styles["meta_label"]),
        ]
        sub_t = Table([[c] for c in content], colWidths=[card_width - 8])
        sub_t.setStyle(
            TableStyle(
                [
                    ("BOX", (0, 0), (-1, -1), 0.8, border_col),
                    ("BACKGROUND", (0, 0), (-1, -1), bg_card),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        current_row.append(sub_t)
        if len(current_row) == card_count:
            rows.append(current_row)
            current_row = []

    if current_row:
        while len(current_row) < card_count:
            current_row.append(Paragraph("", styles["meta_label"]))
        rows.append(current_row)

    t = Table(rows, colWidths=[card_width] * card_count)
    t.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 2),
                ("RIGHTPADDING", (0, 0), (-1, -1), 2),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    return t


def _pick_str(data: dict[str, Any], *keys: str) -> Optional[str]:
    for key in keys:
        val = data.get(key)
        if val is None:
            continue
        text = str(val).strip()
        if text:
            return text
    return None


def _pick_mapping(data: dict[str, Any], *keys: str) -> Optional[dict[str, Any]]:
    for key in keys:
        val = data.get(key)
        if isinstance(val, dict):
            return val
    return None


def normalize_direct_pdf_request(body: Any) -> dict[str, Any]:
    """
    Normalize POST /api/pdf/generate bodies.

    Accepts any pdf schema JSON in:
      templateJson, schemaJson, pdfSchema, pdfTemplate, schema, template
    with corresponding form data in:
      formData, form_data, data, values, fields
    or a standalone schema JSON object containing 'schemas'.
    """
    template_json: Optional[dict[str, Any]] = None
    template_name: Optional[str] = None
    title: Optional[str] = None
    output_filename: Optional[str] = None
    data: dict[str, Any] | list[Any]

    if not isinstance(body, dict):
        if isinstance(body, list):
            return {
                "data": body,
                "template_json": None,
                "template_name": None,
                "title": None,
                "output_filename": None,
            }
        raise ValueError("Request body must be a JSON object or array.")

    # Full workflow export: extract pdfTemplate from a block when present.
    if "blocks" in body and isinstance(body.get("blocks"), list):
        for block in body["blocks"]:
            if not isinstance(block, dict):
                continue
            settings = block.get("settings") or {}
            if settings.get("generatePDF") and isinstance(settings.get("pdfTemplate"), dict):
                template_json = settings["pdfTemplate"]
                break

    template_json = template_json or _pick_mapping(
        body,
        "templateJson",
        "template_json",
        "pdfSchema",
        "pdf_schema",
        "schemaJson",
        "schema_json",
        "pdfTemplate",
        "pdf_template",
        "schema",
        "template",
    )

    if template_json and not is_pdfme_template(template_json):
        # In case a string template identifier was passed under "template" or "schema"
        if _pick_str(body, "template", "template_name", "templateName", "template_id", "templateId"):
            template_name = _pick_str(body, "template", "template_name", "templateName", "template_id", "templateId")
            template_json = None

    form_data = _pick_mapping(body, "formData", "form_data", "data", "values", "fields", "formfields", "formFields")
    if is_pdfme_template(body):
        template_json = body
        if form_data is not None:
            data = form_data
        else:
            inner = body.get("data") or body.get("formData")
            data = inner if isinstance(inner, dict) else {}
    elif form_data is not None:
        data = form_data
    elif "data" in body and isinstance(body["data"], (dict, list)):
        data = body["data"]
        template_name = template_name or _pick_str(body, "template_name", "templateName", "template", "template_id")
        title = title or _pick_str(body, "title", "pdf_title")
    else:
        data = body

    title = title or _pick_str(body, "title", "pdf_title", "documentTitle", "document_title")
    template_name = template_name or _pick_str(
        body, "template_name", "templateName", "template_id", "templateId"
    )
    if not template_name:
        template_name = _pick_str(body, "template")

    raw_name = _pick_str(body, "fileName", "filename", "file_name", "outputFilename", "output_filename")
    if raw_name:
        base = os.path.basename(raw_name)
        if not base.lower().endswith(".pdf"):
            base = f"{base}.pdf"
        safe = re.sub(r"[^A-Za-z0-9._-]+", "_", base).strip("._")
        output_filename = safe or None

    return {
        "data": data,
        "template_json": template_json,
        "template_name": template_name,
        "title": title,
        "output_filename": output_filename,
    }


def list_available_templates(templates_dir: Optional[str] = None) -> list[dict[str, Any]]:
    """Returns available templates. Built-in static templates are removed; templates are supplied dynamically via schema JSON."""
    return []


def load_template(name_or_path: Any, templates_dir: Optional[str] = None) -> Optional[dict[str, Any]]:
    """Parses a schema JSON dictionary or JSON string."""
    if not name_or_path:
        return None
    if isinstance(name_or_path, dict) and is_pdfme_template(name_or_path):
        return name_or_path
    raw = str(name_or_path).strip()
    if not raw:
        return None

    # Direct JSON string
    if raw.startswith("{") and raw.endswith("}"):
        try:
            tpl = json.loads(raw)
            if is_pdfme_template(tpl):
                return tpl
        except Exception:
            pass

    return None


def generate_pdf_from_json(
    json_data: dict[str, Any] | list[Any] | str,
    *,
    template_name: Optional[str] = None,
    template_id: Optional[str] = None,
    template_json: Optional[dict[str, Any] | str] = None,
    template: Optional[dict[str, Any] | str] = None,
    schema_json: Optional[dict[str, Any] | str] = None,
    schema: Optional[dict[str, Any] | str] = None,
    pdf_schema: Optional[dict[str, Any] | str] = None,
    output_path: Optional[str] = None,
    title: Optional[str] = None,
    theme: Optional[str] = None,
    theme_name: Optional[str] = None,
    page_size: str = "A4",
) -> PdfGenerationResult:
    """Renders a complete, beautifully styled PDF from a dynamic schema JSON or structured JSON."""
    now_str = datetime.now(timezone.utc).strftime("%d %b %Y, %H:%M UTC")

    # If string JSON data passed, parse it
    if isinstance(json_data, str):
        trimmed = json_data.strip()
        if (trimmed.startswith("{") and trimmed.endswith("}")) or (trimmed.startswith("[") and trimmed.endswith("]")):
            try:
                json_data = json.loads(trimmed)
            except Exception:
                pass

    # Resolve schema from any keyword alias
    raw_template = schema_json or schema or pdf_schema or template or template_json
    active_template: Optional[dict[str, Any]] = None
    if isinstance(raw_template, dict):
        active_template = raw_template
    elif isinstance(raw_template, str) and raw_template.strip():
        active_template = load_template(raw_template.strip())

    tpl_identifier = template_name or template_id or (json_data.get("template_name") if isinstance(json_data, dict) else None)
    if not active_template and tpl_identifier and str(tpl_identifier).strip().lower() not in {"none", "dynamic", "flowable", "null", ""}:
        active_template = load_template(str(tpl_identifier).strip())

    if isinstance(json_data, dict) and is_pdfme_template(json_data):
        active_template = json_data
        inner_data = json_data.get("data") or json_data.get("formData")
        data = inner_data if isinstance(inner_data, (dict, list)) else json_data
    elif isinstance(json_data, list):
        if len(json_data) == 1 and isinstance(json_data[0], dict):
            data = dict(json_data[0])
        elif len(json_data) > 0 and isinstance(json_data[0], dict) and any("Customer" in k or "Vessel" in k or "Document" in k or "Actual Cost" in k for k in json_data[0].keys()):
            data = dict(json_data[0])
        else:
            data = {"records": json_data}
    elif isinstance(json_data, dict):
        data = dict(json_data)
    else:
        raise ValueError("json_data must be a dictionary or a list of records.")

    doc_title = infer_document_title(data, title)

    # Determine output file path
    if not output_path:
        filename = sanitize_filename(doc_title)
        temp_dir = tempfile.gettempdir()
        output_path = os.path.join(temp_dir, f"ezofis_{datetime.now().strftime('%Y%m%d%H%M%S')}_{filename}")
    else:
        filename = os.path.basename(output_path)

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)

    # If an active schema template is present, render via coordinate-based schema template engine
    if active_template and is_pdfme_template(active_template):
        render_data = data if isinstance(data, dict) else {"records": data}
        out_path, pdf_bytes, page_count = render_pdfme_template_to_pdf(
            template=active_template,
            data=render_data,
            output_path=output_path,
            title=doc_title,
        )
        b64_str = base64.b64encode(pdf_bytes).decode("utf-8")
        return PdfGenerationResult(
            status="success",
            filename=filename,
            file_path=out_path,
            pdf_bytes=pdf_bytes,
            pdf_base64=b64_str,
            page_count=page_count,
            file_size_bytes=len(pdf_bytes),
            title=doc_title,
            generated_at=now_str,
        )

    active_theme = theme or theme_name or data.get("theme") or data.get("pdf_theme")
    theme_dict = resolve_theme(active_theme)

    # Document Geometry
    selected_page_size = letter if page_size.lower() == "letter" else A4
    page_w, page_h = selected_page_size
    margin = 40.0  # ~0.55 inch
    usable_w = page_w - (margin * 2)

    doc = SimpleDocTemplate(
        output_path,
        pagesize=selected_page_size,
        leftMargin=margin,
        rightMargin=margin,
        topMargin=margin + 10.0,
        bottomMargin=margin + 10.0,
    )

    styles = _make_styles(theme_dict)
    story: list[Any] = []

    # 1. Header Banner
    subtitle = data.get("subtitle") or data.get("description") or data.get("summary") or None
    if isinstance(subtitle, dict) or isinstance(subtitle, list):
        subtitle = None
    now_str = datetime.now(timezone.utc).strftime("%d %b %Y, %H:%M UTC")
    logo_src = data.get("tenantLogoUrl") or data.get("logo") or data.get("tenant_logo_url")
    workflow_nm = data.get("workflowName") or data.get("workflow_name") or data.get("documentType")

    story.extend(
        _build_header_banner(
            doc_title,
            subtitle,
            now_str,
            theme_dict,
            styles,
            usable_w,
            logo_source=str(logo_src) if logo_src else None,
            workflow_name=str(workflow_nm) if workflow_nm else None,
        )
    )

    # 2. Extract Top-level Scalar Metadata vs Sub-sections vs Tables vs Process History
    scalar_metadata: list[tuple[str, str]] = []
    sub_sections: list[tuple[str, dict[str, Any]]] = []
    tables_list: list[tuple[str, list[dict[str, Any]]]] = []
    paragraphs_list: list[tuple[str, str]] = []
    signatures_list: list[Any] = []
    process_history_list: list[dict[str, Any]] = []

    # Priority keys to place in main metadata box
    priority_keys = {
        "id",
        "invoice_number",
        "invoice_no",
        "invoiceNo",
        "po_number",
        "poNumber",
        "date",
        "due_date",
        "dueDate",
        "status",
        "payment_status",
        "vendor",
        "vendor_name",
        "customer",
        "customer_name",
        "total",
        "amount",
        "currency",
        "requestNo",
        "requestedBy",
        "requestedOn",
        "workflowName",
        "documentType",
    }

    # Keys to skip from generic sections (already handled)
    skip_keys = {
        "title",
        "document_title",
        "documentTitle",
        "subtitle",
        "description",
        "summary",
        "theme",
        "pdf_theme",
        "tenantLogoUrl",
        "tenant_logo_url",
        "logo",
        "hasFooter",
        "footerText",
    }

    # Classify fields
    for k, v in data.items():
        if k in skip_keys:
            continue

        if k.lower() in {"signature", "signatures", "formsignature", "form_signature", "approvals"}:
            if isinstance(v, list):
                signatures_list.extend(v)
            elif isinstance(v, dict):
                signatures_list.append(v)
            continue

        if k.lower() in {"processhistory", "process_history", "audit_trail", "history"}:
            if isinstance(v, list) and all(isinstance(x, dict) for x in v):
                process_history_list = v
                continue

        if isinstance(v, (str, int, float, bool)) or v is None:
            formatted_val = format_cell_value(v)
            scalar_metadata.append((k, formatted_val))
        elif isinstance(v, list):
            if v and all(isinstance(x, dict) for x in v):
                tables_list.append((k, v))
            elif v and all(isinstance(x, (str, int, float, bool)) for x in v):
                scalar_metadata.append((k, ", ".join(str(x) for x in v)))
            elif v and isinstance(v[0], str) and len(v) > 0:
                paragraphs_list.append((k, "\n".join(f"• {x}" for x in v)))
        elif isinstance(v, dict):
            # Check if nested workflow form or standard sub-dict
            if k == "formFields" and "panels" in v:
                # Workflow form panels
                for panel in v.get("panels", []):
                    p_title = panel.get("title", "Form Section")
                    main_fields_raw = panel.get("mainFields", [])
                    p_dict: dict[str, Any] = {}
                    if isinstance(main_fields_raw, list):
                        for f in main_fields_raw:
                            if isinstance(f, dict):
                                f_name = f.get("label") or f.get("name") or "Field"
                                f_val = f.get("value", "-")
                                p_dict[f_name] = format_cell_value(f_val)
                    elif isinstance(main_fields_raw, dict):
                        for f_name, f_val in main_fields_raw.items():
                            p_dict[f_name] = format_cell_value(f_val)

                    if p_dict:
                        sub_sections.append((p_title, p_dict))

                    for t_item in panel.get("tables", []):
                        if isinstance(t_item, dict):
                            for t_name, t_rows in t_item.items():
                                if isinstance(t_rows, list) and t_rows and all(isinstance(r, dict) for r in t_rows):
                                    tables_list.append((t_name if t_name != "Table" else p_title, t_rows))
                                elif t_name in ("rows", "data") and isinstance(t_rows, list):
                                    tables_list.append((p_title, t_rows))
            else:
                sub_sections.append((k, v))

    # 3. Render Top Metadata Box
    if scalar_metadata:
        meta_table = _build_metadata_box(scalar_metadata, theme_dict, styles, usable_w)
        if meta_table:
            story.append(meta_table)
            story.append(Spacer(1, 10))

    # 4. Render Sub-sections (Key-Value Cards)
    for sec_name, sec_dict in sub_sections:
        story.append(Paragraph(html.escape(sec_name.replace("_", " ").title()), styles["section_h1"]))
        sec_items = [(sk, format_cell_value(sv)) for sk, sv in sec_dict.items() if not isinstance(sv, (list, dict))]
        if sec_items:
            sec_table = _build_metadata_box(sec_items, theme_dict, styles, usable_w)
            if sec_table:
                story.append(sec_table)
                story.append(Spacer(1, 8))

        # Nested tables inside sub_dict
        for sk, sv in sec_dict.items():
            if isinstance(sv, list) and sv and all(isinstance(x, dict) for x in sv):
                story.append(Paragraph(html.escape(sk.replace("_", " ").title()), styles["section_h2"]))
                tbl = _build_table_from_list_of_dicts(sv, theme_dict, styles, usable_w)
                if tbl:
                    story.append(tbl)
                    story.append(Spacer(1, 8))

    # 5. Render Tables (e.g. Items, Transactions, Records)
    for tbl_name, tbl_rows in tables_list:
        story.append(Paragraph(html.escape(tbl_name.replace("_", " ").title()), styles["section_h1"]))
        t_flowable = _build_table_from_list_of_dicts(tbl_rows, theme_dict, styles, usable_w)
        if t_flowable:
            story.append(t_flowable)
            story.append(Spacer(1, 10))

    # 6. Render Paragraphs / Notes / Terms
    for p_name, p_text in paragraphs_list:
        story.append(Paragraph(html.escape(p_name.replace("_", " ").title()), styles["section_h1"]))
        for line in p_text.splitlines():
            if line.strip():
                story.append(Paragraph(html.escape(line), styles["body"]))
        story.append(Spacer(1, 8))

    # 7. Render Process History Table
    if process_history_list:
        story.append(Spacer(1, 10))
        story.append(Paragraph("Process History & Workflow Audit", styles["section_h1"]))
        proc_tbl = _build_process_history_table(process_history_list, theme_dict, styles, usable_w)
        if proc_tbl:
            story.append(KeepTogether([proc_tbl]))
            story.append(Spacer(1, 8))

    # 8. Render Signatures / Approvals
    if signatures_list:
        story.append(Spacer(1, 10))
        story.append(Paragraph("Authorization & Signatures", styles["section_h1"]))
        sig_grid = _build_signature_grid(signatures_list, theme_dict, styles, usable_w)
        if sig_grid:
            story.append(KeepTogether([sig_grid]))
            story.append(Spacer(1, 8))

    # Build the document using NumberedCanvas
    def _canvas_factory(*args: Any, **kwargs: Any) -> NumberedCanvas:
        c = NumberedCanvas(*args, **kwargs)
        c.doc_title = doc_title
        c.theme_colors = theme_dict
        return c

    doc.build(story, canvasmaker=_canvas_factory)

    # Read the output bytes
    with open(output_path, "rb") as f:
        pdf_bytes = f.read()

    # Inspect page count using fitz
    page_count = 1
    try:
        with fitz.open(stream=pdf_bytes, filetype="pdf") as pdf_doc:
            page_count = len(pdf_doc)
    except Exception as exc:
        logger.warning("fitz_page_count_fallback", extra={"error": str(exc)})

    b64_str = base64.b64encode(pdf_bytes).decode("utf-8")

    return PdfGenerationResult(
        status="success",
        filename=filename,
        file_path=output_path,
        pdf_bytes=pdf_bytes,
        pdf_base64=b64_str,
        page_count=page_count,
        file_size_bytes=len(pdf_bytes),
        title=doc_title,
        generated_at=now_str,
    )
